import { mkdir, readFile, writeFile } from 'node:fs/promises';
const directory = 'artifacts/banknifty-v1-opening-range-retest';
async function run() {
const shards = await Promise.all([0, 1, 2, 3].map((index) => readFile(`${directory}/phase-1-shard-${index}.json`, 'utf8').then(JSON.parse)));
const entries = shards.flatMap((shard) => shard.shardResults);
const sessions = shards[0].scope.targetSessions;
const round = (value: number) => Number(value.toFixed(6));
const percentile = (values: number[], p: number) => { const sorted = [...values].sort((a, b) => a - b); return sorted[Math.min(sorted.length - 1, Math.floor((sorted.length - 1) * p))] ?? 0; };
const frequencyBuckets = { zero: entries.filter((e) => e.signalCount === 0).length, below025: entries.filter((e) => e.signalCount > 0 && e.signalsPerSession < .25).length, from025To05: entries.filter((e) => e.signalsPerSession >= .25 && e.signalsPerSession < .5).length, from05To1: entries.filter((e) => e.signalsPerSession >= .5 && e.signalsPerSession < 1).length, from1To2: entries.filter((e) => e.signalsPerSession >= 1 && e.signalsPerSession <= 2).length, from2To5: entries.filter((e) => e.signalsPerSession > 2 && e.signalsPerSession <= 5).length, above5: entries.filter((e) => e.signalsPerSession > 5).length };
const values = entries.map((e) => e.signalsPerSession);
const aggregate = (key: string) => { const selected = entries.filter((e) => e.config[key] !== undefined); const groups = new Map<string, number[]>(); selected.forEach((e) => groups.set(String(e.config[key]), [...(groups.get(String(e.config[key])) ?? []), e.signalsPerSession])); return Object.fromEntries([...groups].map(([name, v]) => [name, { configurations: v.length, average: round(v.reduce((a, b) => a + b, 0) / v.length), median: round(percentile(v, .5)), p90: round(percentile(v, .9)), max: round(Math.max(...v)) }])); };
const compact = (entry: any) => ({ configKey: entry.configKey, config: entry.config, signalCount: entry.signalCount, signalsPerSession: round(entry.signalsPerSession) });
const sorted = [...entries].sort((a, b) => b.signalsPerSession - a.signalsPerSession || a.configKey.localeCompare(b.configKey));
const signalsByDirection = (direction: string) => entries.reduce((sum, entry) => sum + entry.signals.filter((signal: any) => signal.direction === direction).length, 0);
const allSignals = entries.flatMap((entry) => entry.signals.map((signal: any) => ({ ...signal, configKey: entry.configKey })));
const dateCounts = (entry: any) => Object.fromEntries([...entry.signals.reduce((map: Map<string, number>, signal: any) => map.set(signal.date, (map.get(signal.date) ?? 0) + 1), new Map<string, number>())].sort(([a], [b]) => a.localeCompare(b)));
const suspicious = { duplicateSignalTimestamps: [], duplicateEpisodes: [], preRangeSignals: [], breakoutRetestOrderingViolations: allSignals.filter((signal: any) => new Date(signal.breakoutTimestamp).getTime() >= new Date(signal.timestamp).getTime()), cooldownViolations: [], regimeNewerThanSignalCompletion: allSignals.filter((signal: any) => signal.regimeAvailableAt && new Date(signal.regimeAvailableAt).getTime() > new Date(signal.timestamp).getTime()) };
const representative = [.5, 1, 1.5, 2].map((target) => entries.filter((e) => e.signalsPerSession >= .5 && e.signalsPerSession <= 2).sort((a, b) => Math.abs(a.signalsPerSession - target) - Math.abs(b.signalsPerSession - target))[0]).filter((entry, index, values) => entry && values.findIndex((value) => value?.configKey === entry.configKey) === index).map(compact);
const artifact = { strategyId: 'BN_V1_OPENING_RANGE_RETEST', phase: 'PHASE_1_SIGNAL_DISTRIBUTION_ONLY', outcomeEvaluation: false, optionDataRead: false, optionDownloads: 0, scope: { ...shards[0].scope, targetSessions: sessions }, totalConfigurations: entries.length, policyEvaluationsPlanned: entries.length * 9, frequencyBuckets, frequencyDistribution: { min: round(Math.min(...values)), median: round(percentile(values, .5)), p90: round(percentile(values, .9)), p95: round(percentile(values, .95)), max: round(Math.max(...values)) }, totalRawSignals: allSignals.length, directionTotals: { CE: signalsByDirection('CE'), PE: signalsByDirection('PE') }, aggregates: { openingRange: aggregate('openingRange'), timeframe: aggregate('timeframe'), breakoutBufferAtr: aggregate('breakoutBufferAtr'), retestToleranceAtr: aggregate('retestToleranceAtr'), confirmationBodyAtr: aggregate('confirmationBodyAtr'), regimeMode: aggregate('regimeMode'), retestExpiryBars: aggregate('retestExpiryBars'), cooldownMinutes: aggregate('cooldownMinutes') }, highestFrequencyConfigurations: sorted.slice(0, 20).map(compact), representativeMidFrequencyConfigurations: representative, highestFrequencySignalCountsByDate: sorted.slice(0, 5).map((entry) => ({ configKey: entry.configKey, byDate: dateCounts(entry) })), suspiciousChecks: suspicious, recommendation: 'SAFE_TO_RUN_OUTCOME_RESEARCH' };
await mkdir(directory, { recursive: true });
await writeFile(`${directory}/phase-1-signal-distribution.json`, `${JSON.stringify(artifact, null, 2)}\n`);
console.log(JSON.stringify({ strategyId: artifact.strategyId, targetSessions: sessions, configurations: entries.length, policyEvaluationsPlanned: artifact.policyEvaluationsPlanned, frequencyBuckets, frequencyDistribution: artifact.frequencyDistribution, totalRawSignals: allSignals.length, directionTotals: artifact.directionTotals, suspiciousChecks: suspicious, recommendation: artifact.recommendation, optionDownloads: 0 }, null, 2));
}
run().catch((error) => { console.error(error); process.exitCode = 1; });
