import assert from 'node:assert/strict';
import test from 'node:test';
import { ExpiredOptionCandleDto } from '../modules/options/dto/upstox-expired-option-candle.dto';
import { OptionExitPolicyEvaluationResult, TargetStopOptionExitPolicy } from '../modules/options/dto/option-exit-policy.dto';
import OptionPremiumPathAnalysisService from '../modules/options/services/option-premium-path-analysis.service';

const changeHorizons = [1, 2, 3, 4, 5, 10, 15]; const excursionHorizons = [3, 5, 10, 15]; const targets = [3, 5, 7.5, 10, 15, 20];
function candles(): ExpiredOptionCandleDto[] { const start = new Date('2026-07-15T09:15:00+05:30').getTime(); return Array.from({ length: 375 }, (_, index) => ({ instrumentKey: 'NSE_FO|TEST', candleTime: new Date(start + index * 60_000), open: 100 + index / 10, high: 100 + index, low: 100 - index / 2, close: 100 + index / 4, volume: 1n })); }
function legacyChange(rows: readonly ExpiredOptionCandleDto[], signal: Date, entry: number, horizon: number): number | null { const future = rows.find((row) => row.candleTime.getTime() === signal.getTime() + horizon * 60_000); return future === undefined ? null : (future.close - entry) / entry * 100; }
function legacyExcursion(rows: readonly ExpiredOptionCandleDto[], signal: Date, entry: number, horizon: number): { mfe: number | null; mae: number | null } { const future = rows.filter((row) => row.candleTime.getTime() > signal.getTime() && row.candleTime.getTime() <= signal.getTime() + horizon * 60_000); if (future.length !== horizon) return { mfe: null, mae: null }; return { mfe: (Math.max(...future.map((row) => row.high)) - entry) / entry * 100, mae: (entry - Math.min(...future.map((row) => row.low))) / entry * 100 }; }
function legacyReach(rows: readonly ExpiredOptionCandleDto[], signal: Date, entry: number, percent: number, upside: boolean): number | null { const threshold = entry * (1 + (upside ? percent : -percent) / 100); const found = rows.filter((row) => row.candleTime.getTime() > signal.getTime()).find((row) => upside ? row.high >= threshold : row.low <= threshold); return found === undefined ? null : (found.candleTime.getTime() - signal.getTime()) / 60_000; }
function legacyPolicy(rows: readonly ExpiredOptionCandleDto[], signal: Date, entry: number, policy: TargetStopOptionExitPolicy): OptionExitPolicyEvaluationResult { const targetPremium = entry * (1 + policy.targetPercent / 100); const stopPremium = entry * (1 - policy.stopLossPercent / 100); for (let offset = 1; offset <= policy.maximumHoldingMinutes; offset += 1) { const candle = rows.find((row) => row.candleTime.getTime() === signal.getTime() + offset * 60_000); if (!candle) continue; const target = candle.high >= targetPremium; const stop = candle.low <= stopPremium; if (target && stop) return { signalTimestamp: signal, entryPremium: entry, exitTimestamp: new Date(candle.candleTime.getTime()), exitPremium: null, exitReason: 'AMBIGUOUS', holdingMinutes: offset, premiumChange: null, premiumChangePercent: null, targetPremium, stopPremium, ambiguous: true, unavailable: false }; if (target || stop) { const premium = target ? targetPremium : stopPremium; return { signalTimestamp: signal, entryPremium: entry, exitTimestamp: new Date(candle.candleTime.getTime()), exitPremium: premium, exitReason: target ? 'TARGET' : 'STOP_LOSS', holdingMinutes: offset, premiumChange: premium - entry, premiumChangePercent: (premium - entry) / entry * 100, targetPremium, stopPremium, ambiguous: false, unavailable: false }; } } const time = rows.find((row) => row.candleTime.getTime() === signal.getTime() + policy.maximumHoldingMinutes * 60_000); return time ? { signalTimestamp: signal, entryPremium: entry, exitTimestamp: new Date(time.candleTime.getTime()), exitPremium: time.close, exitReason: 'TIME_EXIT', holdingMinutes: policy.maximumHoldingMinutes, premiumChange: time.close - entry, premiumChangePercent: (time.close - entry) / entry * 100, targetPremium, stopPremium, ambiguous: false, unavailable: false } : { signalTimestamp: signal, entryPremium: entry, exitTimestamp: null, exitPremium: null, exitReason: 'UNAVAILABLE', holdingMinutes: null, premiumChange: null, premiumChangePercent: null, targetPremium, stopPremium, ambiguous: false, unavailable: true }; }
function analytics(rows: readonly ExpiredOptionCandleDto[], signal: Date) { return new OptionPremiumPathAnalysisService(signal, rows).researchAnalytics({ changeHorizons, excursionHorizons, upsideTargets: targets, downsideStops: targets }); }

test('one path pass exactly matches legacy changes, excursions, reaches, and target/stop results', () => { const rows = candles(); const signal = rows[30].candleTime; const entry = rows[30].close; const optimized = analytics(rows, signal); assert.equal(optimized.entryPremium, entry); changeHorizons.forEach((horizon) => assert.equal(optimized.changes.get(horizon), legacyChange(rows, signal, entry, horizon))); excursionHorizons.forEach((horizon) => assert.deepEqual(optimized.excursions.get(horizon), legacyExcursion(rows, signal, entry, horizon))); targets.forEach((percent) => { assert.equal(optimized.reaches.get(percent), legacyReach(rows, signal, entry, percent, true)); assert.equal(optimized.reaches.get(-percent), legacyReach(rows, signal, entry, percent, false)); }); const policy: TargetStopOptionExitPolicy = { type: 'TARGET_STOP', targetPercent: 5, stopLossPercent: 5, maximumHoldingMinutes: 15 }; assert.deepEqual(new OptionPremiumPathAnalysisService(signal, rows).evaluate(policy), legacyPolicy(rows, signal, entry, policy)); });

test('ambiguous same-candle target and stop remains ambiguous', () => { const rows = candles(); const signal = rows[20].candleTime; rows[21] = { ...rows[21], high: rows[20].close * 1.1, low: rows[20].close * 0.9 }; const policy: TargetStopOptionExitPolicy = { type: 'TARGET_STOP', targetPercent: 5, stopLossPercent: 5, maximumHoldingMinutes: 3 }; assert.deepEqual(new OptionPremiumPathAnalysisService(signal, rows).evaluate(policy), legacyPolicy(rows, signal, rows[20].close, policy)); });

test('market-close horizons and target/stop time exits preserve unavailable behavior', () => { const rows = candles(); const signal = rows[373].candleTime; const optimized = analytics(rows, signal); assert.equal(optimized.changes.get(1), legacyChange(rows, signal, rows[373].close, 1)); assert.equal(optimized.changes.get(3), null); assert.deepEqual(optimized.excursions.get(3), { mfe: null, mae: null }); const policy: TargetStopOptionExitPolicy = { type: 'TARGET_STOP', targetPercent: 99, stopLossPercent: 99, maximumHoldingMinutes: 3 }; assert.deepEqual(new OptionPremiumPathAnalysisService(signal, rows).evaluate(policy), legacyPolicy(rows, signal, rows[373].close, policy)); });

test('missing minutes preserve exact horizon nulls while reaches still use later available candles', () => { const rows = candles(); const signal = rows[50].candleTime; const missing = rows.filter((_, index) => index !== 52); const optimized = analytics(missing, signal); assert.equal(optimized.changes.get(3), legacyChange(missing, signal, rows[50].close, 3)); assert.deepEqual(optimized.excursions.get(3), legacyExcursion(missing, signal, rows[50].close, 3)); targets.forEach((percent) => { assert.equal(optimized.reaches.get(percent), legacyReach(missing, signal, rows[50].close, percent, true)); assert.equal(optimized.reaches.get(-percent), legacyReach(missing, signal, rows[50].close, percent, false)); }); const policy: TargetStopOptionExitPolicy = { type: 'TARGET_STOP', targetPercent: 5, stopLossPercent: 5, maximumHoldingMinutes: 5 }; assert.deepEqual(new OptionPremiumPathAnalysisService(signal, missing).evaluate(policy), legacyPolicy(missing, signal, rows[50].close, policy)); });
