import 'dotenv/config';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'; import { resolve } from 'node:path';
import HistoricalCandleRepository from '../modules/historical-candles/repositories/historical-candle.repository';
import HistoricalOptionCandleRepository from '../modules/options/repositories/historical-option-candle.repository';
import HistoricalOptionCandleCacheService from '../modules/options/services/historical-option-candle-cache.service';
import UpstoxExpiredOptionCandleClient from '../modules/options/client/upstox-expired-option-candle.client';
import UpstoxExpiredOptionClient from '../modules/options/client/upstox-expired-option.client';
import ResearchSplitService from '../modules/research-validation/services/research-split.service';
import { OptionContract } from '../modules/options/types';
import { deduplicateSurfaceRequirements, istExpiryDate, regularSessionTimes, selectNiftyOptionSurface, SurfaceRequirement } from '../modules/research/v11-nifty-iv-skew/option-surface';
import { solveEuropeanImpliedVolatility } from '../modules/research/v11-nifty-iv-skew/implied-volatility';
const UNDERLYING='NSE_INDEX|Nifty 50', DIR=resolve(process.cwd(),'artifacts','v11-nifty-iv-skew'), TIMES=['09:30','10:30','12:00','14:00'] as const;
type Requirement=SurfaceRequirement & { observations:string[] };
type State='COMPLETE'|'USABLE_SPARSE'|'INCOMPLETE_DATA'|'NO_TRADES';
const date=(d:Date)=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);
const percent=(n:number,d:number)=>d?Number((n/d*100).toFixed(2)):0;
function state(rows:readonly any[], day:string):State { if(!rows.length)return'NO_TRADES'; const t=rows.map(r=>new Date(r.candleTime).getTime()), expected=regularSessionTimes(day), set=new Set(t); const valid=rows.every(r=>[r.open,r.high,r.low,r.close].every((v:any)=>Number.isFinite(Number(v)))&&Number(r.high)>=Math.max(Number(r.open),Number(r.close),Number(r.low))&&Number(r.low)<=Math.min(Number(r.open),Number(r.close),Number(r.high))); if(rows.length===375&&set.size===375&&expected.every(x=>set.has(x))&&valid)return'COMPLETE'; return valid&&set.size===t.length?'USABLE_SPARSE':'INCOMPLETE_DATA'; }
async function concurrent<T>(items:readonly T[], f:(v:T)=>Promise<void>):Promise<void>{
  // SQLite's transaction scheduler serializes the cache repository. One worker avoids
  // retried network reads caused solely by competing otherwise-idempotent upserts.
  for (const item of items) await f(item);
}
function write(name:string,v:unknown){mkdirSync(DIR,{recursive:true});writeFileSync(resolve(DIR,name),JSON.stringify(v,null,2)+'\n');}
async function run(){
 if(process.env.RESEARCH_LOCAL_ONLY==='true') throw Error('V11 surface preparation requires the explicitly authorized remote cache fill; unset RESEARCH_LOCAL_ONLY for this preparation command.');
 const token=process.env.UPSTOX_ACCESS_TOKEN?.trim();if(!token)throw Error('UPSTOX_ACCESS_TOKEN is required.');
 const split=JSON.parse(readFileSync(resolve(process.cwd(),'artifacts/research-validation/nifty-104-split-v1.json'),'utf8'));const dates:string[]=split.sessions.filter((r:any)=>r.split==='TRAIN'||r.split==='VALIDATION').map((r:any)=>r.tradingDate);new ResearchSplitService().assertOutcomeAccess(split,dates,'TRAIN_VALIDATION_ONLY');
 const under=await new HistoricalCandleRepository().findByInstrumentAndTimeframe(UNDERLYING,'1minute');const spot=new Map<string,number>();under.forEach((r:any)=>{if(dates.includes(date(r.candleTime)))spot.set(`${date(r.candleTime)}|${new Date(r.candleTime).getTime()}`,Number(r.close));});
 const meta=new UpstoxExpiredOptionClient(token);let metadataRequests=1;const expiries=(await meta.fetchAvailableExpiries(UNDERLYING)).sort();const expiryFor=new Map<string,string>();dates.forEach(d=>{const e=expiries.find(x=>x>=d);if(e)expiryFor.set(d,e);});const used=[...new Set(expiryFor.values())];const chains=new Map<string,OptionContract[]>();for(const e of used){metadataRequests++;chains.set(e,await meta.fetchExpiredOptionContracts(UNDERLYING,e));}
 const observations:any[]=[];const raw:Requirement[]=[];for(const d of dates)for(const tm of TIMES){const at=new Date(`${d}T${tm}:00+05:30`), prior=new Date(at.getTime()-60000), s=spot.get(`${d}|${prior.getTime()}`), e=expiryFor.get(d);if(!s||!e){observations.push({tradingDate:d,observationIst:tm,status:'SPOT_OR_METADATA_UNAVAILABLE'});continue;}let surface;try{surface=selectNiftyOptionSurface(chains.get(e)??[],d,s);}catch(error){observations.push({tradingDate:d,observationIst:tm,status:'METADATA_INVALID',error:String(error)});continue;} const legs:any[]=[];Object.entries(surface.legs).forEach(([leg,c])=>{const contract=c!;legs.push({leg,instrumentKey:contract.instrumentKey,strike:contract.strikePrice,optionType:contract.optionType});raw.push({instrumentKey:contract.instrumentKey,tradingDate:d,expiryDate:surface.expiryDate,strike:contract.strikePrice,optionType:contract.optionType,tradingSymbol:contract.tradingSymbol,leg:leg as any,observations:[tm]});});observations.push({tradingDate:d,observationIst:tm,premiumObservationIst:date(prior)+' '+new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(prior),expiry:surface.expiryDate,spot:s,atmStrike:surface.atmStrike,strikes:surface.strikes,legs,missingLegs:surface.missingLegs});}
 const req0=deduplicateSurfaceRequirements(raw);const byKey=new Map<string,Requirement>();raw.forEach(r=>{const k=`${r.instrumentKey}|${r.tradingDate}`;const old=byKey.get(k);if(old)old.observations.push(...r.observations);else byKey.set(k,{...r});});const requirements=[...byKey.values()]; const repo=new HistoricalOptionCandleRepository();let rows=await repo.findByInstrumentDateSessions(requirements,'1minute');const groups=new Map<string,any[]>();rows.forEach(r=>{const k=`${r.instrumentKey}|${date(r.candleTime)}`;groups.set(k,[...(groups.get(k)??[]),r]);});const pre=requirements.map(r=>({...r,status:state(groups.get(`${r.instrumentKey}|${r.tradingDate}`)??[],r.tradingDate)}));const missing=pre.filter(r=>r.status!=='COMPLETE');
 const preReport={protectedSessions:dates.length,observationCount:observations.length,expiries:used,uniqueOptionInstruments:new Set(requirements.map(r=>r.instrumentKey)).size,uniqueInstrumentDateSessions:requirements.length,alreadyCompleteLocally:pre.filter(r=>r.status==='COMPLETE').length,usableSparseLocally:pre.filter(r=>r.status==='USABLE_SPARSE').length,missingLocally:missing.length,estimatedNetworkRequests:missing.length,estimatedRows:missing.length*375,estimatedDiskBytes:missing.length*375*112};console.log('V11_PRE_DOWNLOAD_REPORT',JSON.stringify(preReport));if(requirements.length>5000)throw Error(`Refusing V11 surface fill: ${requirements.length} required sessions exceeds 5000.`);
 const cache=new HistoricalOptionCandleCacheService(repo,new UpstoxExpiredOptionCandleClient(token));await concurrent(missing,async r=>{try{await cache.getCandles(r.instrumentKey,r.tradingDate,{tradingSymbol:r.tradingSymbol,optionType:r.optionType,strikePrice:r.strike,expiry:new Date(`${r.expiryDate}T00:00:00+05:30`)});}catch{}});const results=cache.getSessionResults();rows=await repo.findByInstrumentDateSessions(requirements,'1minute');groups.clear();rows.forEach(r=>{const k=`${r.instrumentKey}|${date(r.candleTime)}`;groups.set(k,[...(groups.get(k)??[]),r]);});const final=requirements.map(r=>({...r,status:state(groups.get(`${r.instrumentKey}|${r.tradingDate}`)??[],r.tradingDate)}));
 const lookup=new Map<string,any>();rows.forEach(r=>lookup.set(`${r.instrumentKey}|${new Date(r.candleTime).getTime()}`,r));const featureRows:any[]=[];const ivs:number[]=[];let attempted=0,converged=0,missingPremium=0,rejected=0;for(const o of observations){if(!o.legs)continue;const prior=new Date(`${o.tradingDate}T${o.observationIst}:00+05:30`);prior.setTime(prior.getTime()-60000);const get=(leg:string,at=prior)=>{const l=o.legs.find((x:any)=>x.leg===leg);return l&&lookup.get(`${l.instrumentKey}|${at.getTime()}`)?{...l,row:lookup.get(`${l.instrumentKey}|${at.getTime()}`)}:undefined};const iv=(leg:string,at=prior,spotValue=o.spot)=>{const v=get(leg,at);if(!v||Number(v.row.close)<=0){missingPremium++;return null;}attempted++;const r=solveEuropeanImpliedVolatility({optionType:v.optionType,spot:spotValue,strike:v.strike,premium:Number(v.row.close),timeToExpiryYears:(new Date(`${o.expiry}T15:30:00+05:30`).getTime()-at.getTime())/(365*86400000),riskFreeRate:.06,dividendYield:0});if(r.converged&&r.impliedVolatility!==null){converged++;ivs.push(r.impliedVolatility);return r.impliedVolatility;}rejected++;return null;};const ace=iv('ATM_CE'),ape=iv('ATM_PE'),d1=iv('DOWN1_PE'),u1=iv('UP1_CE'),d2=iv('DOWN2_PE'),u2=iv('UP2_CE'),d3=iv('DOWN3_PE'),u3=iv('UP3_CE');const atm=ace!==null&&ape!==null?(ace+ape)/2:null;const delta=(n:number)=>{const p=new Date(prior.getTime()-n*60000), ps=spot.get(`${o.tradingDate}|${p.getTime()}`);if(!ps||u1===null||d1===null)return false;const a=iv('UP1_CE',p,ps),b=iv('DOWN1_PE',p,ps);return a!==null&&b!==null;};featureRows.push({date:o.tradingDate,time:o.observationIst,expiry:o.expiry,atmIv:atm!==null,wing1:d1!==null&&u1!==null,wing2:d2!==null&&u2!==null,wing3:d3!==null&&u3!==null,downsideSkew:d1!==null&&atm!==null,upsideSkew:u1!==null&&atm!==null,riskReversal:d1!==null&&u1!==null,delta1m:delta(1),delta3m:delta(3),delta5m:delta(5)});}
 const cov=(key:string)=>({available:featureRows.filter(x=>x[key]).length,percent:percent(featureRows.filter(x=>x[key]).length,featureRows.length)});const sort=[...ivs].sort((a,b)=>a-b);const coverage={observations:featureRows.length,atmIv:cov('atmIv'),symmetricPlusMinus1:cov('wing1'),symmetricPlusMinus2:cov('wing2'),symmetricPlusMinus3:cov('wing3'),downsideSkew:cov('downsideSkew'),upsideSkew:cov('upsideSkew'),riskReversal:cov('riskReversal'),delta1m:cov('delta1m'),delta3m:cov('delta3m'),delta5m:cov('delta5m'),byTimeOfDay:TIMES.map(t=>({time:t,observations:featureRows.filter(x=>x.time===t).length,riskReversal:percent(featureRows.filter(x=>x.time===t&&x.riskReversal).length,featureRows.filter(x=>x.time===t).length)})),byExpiry:used.map(e=>({expiry:e,observations:featureRows.filter(x=>x.expiry===e).length,riskReversal:percent(featureRows.filter(x=>x.expiry===e&&x.riskReversal).length,featureRows.filter(x=>x.expiry===e).length)}))};const quality={attempted,converged,convergencePercent:percent(converged,attempted),missingPremium,rejected,ivMin:sort[0]??null,ivMedian:sort[Math.floor(sort.length*.5)]??null,ivP95:sort[Math.floor(sort.length*.95)]??null,ivMax:sort.at(-1)??null,suspiciousIvCount:ivs.filter(x=>x<.01||x>3).length,assumptions:{riskFreeRate:.06,dividendYield:0,expiryTime:'15:30 IST actual expiry date',spotAndPremium:'prior completed 1-minute observation'}};const failed=results.filter(r=>r.status==='failed'||r.status==='overfull');const statusCount=(s:State)=>final.filter(r=>r.status===s).length;const verdict=coverage.atmIv.percent>=90&&coverage.symmetricPlusMinus1.percent>=80&&coverage.riskReversal.percent>=80?'READY_FOR_V11_SIGNAL_RESEARCH':coverage.atmIv.percent>=90?'READY_WITH_LIMITED_WING_DEPTH':'V11_SURFACE_DATA_NOT_RELIABLE';
 write('phase-0-chain-metadata.json',{underlying:UNDERLYING,protectedSessions:dates.length,expiries:used,chains:used.map(e=>{const c=chains.get(e)??[];const strikes=[...new Set(c.map(x=>x.strikePrice))].sort((a,b)=>a-b);return{expiry:e,contracts:c.length,ce:c.filter(x=>x.optionType==='CE').length,pe:c.filter(x=>x.optionType==='PE').length,strikes,spacing:strikes.slice(1).map((x,i)=>x-strikes[i]),metadataComplete:true};})});write('phase-0-required-surface-manifest.json',{selection:'nearest metadata ATM; lower strike tie-break; actual adjacent +/-1..3; same expiry only; prior completed 1m spot',observations,requirements});write('phase-0-surface-cache-manifest.json',{preDownload:preReport,results,required:final,counts:{complete:statusCount('COMPLETE'),usableSparse:statusCount('USABLE_SPARSE'),incomplete:statusCount('INCOMPLETE_DATA'),noTrades:statusCount('NO_TRADES')}});write('phase-0-expanded-iv-quality.json',quality);write('phase-0-expanded-feature-coverage.json',coverage);write('phase-0-data-prep-summary.json',{verdict,preDownload:preReport,metadataRequests,networkRequests:metadataRequests+results.filter(r=>r.status!=='hit').length,cacheWrites:cache.getStats().stored,downloaded:results.filter(r=>r.status==='downloaded').length,failed,coverage,quality,finalStates:{complete:statusCount('COMPLETE'),usableSparse:statusCount('USABLE_SPARSE'),incomplete:statusCount('INCOMPLETE_DATA'),noTrades:statusCount('NO_TRADES')}});console.log('V11_SURFACE_PREP',JSON.stringify({verdict,preDownload:preReport,metadataRequests,cache:cache.getStats(),resultCounts:{downloaded:results.filter(r=>r.status==='downloaded').length,failed:failed.length},coverage},null,2));if(failed.length)process.exitCode=1;
}
void run().catch(e=>{console.error('V11 surface preparation failed:',e instanceof Error?e.stack??e.message:String(e));process.exitCode=1;});
