import 'dotenv/config';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import HistoricalCandleRepository from '../modules/historical-candles/repositories/historical-candle.repository';
import CandleTimeframeAggregatorService from '../modules/indicators/services/candle-timeframe-aggregator.service';
import IndicatorEngineService from '../modules/indicators/services/indicator-engine.service';
import AdaptiveMarketRegimeService from '../modules/adaptive-intraday/services/adaptive-market-regime.service';
import { CrossSessionPreparedSession, filterCrossSessionResearchTargets, prepareCrossSessionIndicatorWarmup } from './helpers/cross-session-indicator-warmup';
import { assertNoLookAhead, BankNiftyOpeningRangeConfig, createAtrContext, createConfigs, generateSignals, BankNiftyOpeningRangeSignal, BN_V1_STRATEGY_ID } from '../modules/research/banknifty-v1-opening-range-retest';

const underlyingKey = 'NSE_INDEX|Nifty Bank';
const fromDate = '2026-03-02';
const endDate = '2026-07-28';
const eligibilityPath = 'artifacts/banknifty-option-prep/research-session-eligibility.json';
const artifactDirectory = 'artifacts/banknifty-v1-opening-range-retest';

interface Eligibility { eligibleDates: string[]; proposedSplit: { policy?: { train: number; embargo1: number; validation: number; embargo2: number; legacyContaminatedHoldout: number } } }
interface ConfigResult { config: BankNiftyOpeningRangeConfig; configKey: string; signalCount: number; signalsPerSession: number; signals: BankNiftyOpeningRangeSignal[]; }

async function run(): Promise<void> {
  const eligibility = JSON.parse(await readFile(eligibilityPath, 'utf8')) as Eligibility;
  const orderedEligible = [...eligibility.eligibleDates].sort();
  const policy = eligibility.proposedSplit.policy ?? { train: 55, embargo1: 3, validation: 20, embargo2: 3, legacyContaminatedHoldout: 18 };
  const trainEnd = policy.train;
  const validationStart = trainEnd + policy.embargo1;
  const validationEnd = validationStart + policy.validation;
  const allowedDates = orderedEligible.filter((_, index) => index < trainEnd || (index >= validationStart && index < validationEnd));
  if (allowedDates.length !== policy.train + policy.validation) throw new Error(`TRAIN_VALIDATION_ONLY date count mismatch: ${allowedDates.length}`);
  if (allowedDates.some((date) => date > endDate)) throw new Error('TRAIN_VALIDATION_ONLY scope exceeded the permitted end date.');
  const repository = new HistoricalCandleRepository();
  const rows = await repository.findRange(underlyingKey, '1minute', new Date(`${fromDate}T00:00:00+05:30`), new Date(`${endDate}T23:59:59.999+05:30`));
  const byDate = new Map<string, Array<{ timestamp: Date; open: number; high: number; low: number; close: number; volume: number }>>();
  rows.forEach((row) => { const candle = { timestamp: new Date(row.candleTime.getTime()), open: Number(row.open), high: Number(row.high), low: Number(row.low), close: Number(row.close), volume: Number(row.volume) }; const date = istDate(candle.timestamp); byDate.set(date, [...(byDate.get(date) ?? []), candle]); });
  const source = allowedDates.map((date) => ({ date, candles: (byDate.get(date) ?? []).sort((a, b) => a.timestamp.getTime() - b.timestamp.getTime()) }));
  if (source.some((entry) => entry.candles.length !== 375)) throw new Error('BANK NIFTY source contains an incomplete target session.');
  const prepared = prepareCrossSessionIndicatorWarmup(source, new CandleTimeframeAggregatorService(), new IndicatorEngineService(), new AdaptiveMarketRegimeService({ trendStrengthThreshold: 20, emaProximityPercent: 0.05, highVolatilityThreshold: 0.1, lowVolatilityThreshold: 0.05 }));
  const targetSessions = filterCrossSessionResearchTargets(prepared, endDate);
  const atrContext = createAtrContext(targetSessions);
  const configs = createConfigs();
  const shardIndex = Number(process.env.BN_V1_SHARD_INDEX ?? 0);
  const shardCount = Number(process.env.BN_V1_SHARD_COUNT ?? 1);
  const configsToRun = shardCount > 1 ? configs.filter((_, index) => index % shardCount === shardIndex) : configs;
  const results: ConfigResult[] = configsToRun.map((config) => { const signals = generateSignals(targetSessions, config, atrContext); assertNoLookAhead(signals); return { config, configKey: `${BN_V1_STRATEGY_ID}|${config.openingRange}|${config.timeframe}|${config.breakoutBufferAtr}|${config.retestToleranceAtr}|${config.confirmationBodyAtr}|${config.regimeMode}|${config.retestExpiryBars}|${config.cooldownMinutes}`, signalCount: signals.length, signalsPerSession: signals.length / targetSessions.length, signals }; });
  const suspicious = suspiciousChecks(results, targetSessions);
  const sorted = [...results].sort((a, b) => b.signalsPerSession - a.signalsPerSession || a.configKey.localeCompare(b.configKey));
  const compact = (entry: ConfigResult) => ({ configKey: entry.configKey, config: entry.config, signalCount: entry.signalCount, signalsPerSession: round(entry.signalsPerSession) });
  const representative = [0.5, 1, 1.5, 2].map((target) => results.filter((entry) => entry.signalsPerSession >= 0.5 && entry.signalsPerSession <= 2).sort((a, b) => Math.abs(a.signalsPerSession - target) - Math.abs(b.signalsPerSession - target) || a.configKey.localeCompare(b.configKey))[0]).filter((entry, index, values) => entry && values.findIndex((value) => value?.configKey === entry.configKey) === index).map(compact);
  const policyEvaluations = configs.length * 3 * 3;
  const artifact = { strategyId: BN_V1_STRATEGY_ID, phase: 'PHASE_1_SIGNAL_DISTRIBUTION_ONLY', outcomeEvaluation: false, optionDataRead: false, optionDownloads: 0, scope: { underlyingKey, startDate: allowedDates[0], endDate: allowedDates.at(-1), targetSessions: targetSessions.length, mode: 'TRAIN_VALIDATION_ONLY', includedSplits: ['TRAIN', 'VALIDATION'], excludedSplits: ['EMBARGO_1', 'EMBARGO_2', 'LEGACY_CONTAMINATED_HOLDOUT'], finalHoldoutAccessed: false }, totalConfigurations: configs.length, evaluatedConfigurations: results.length, policyEvaluationsPlanned: policyEvaluations, frequencyBuckets: frequencyBuckets(results), frequencyDistribution: distribution(results.map((entry) => entry.signalsPerSession)), aggregates: { direction: { CE: aggregateSignals(results, 'CE'), PE: aggregateSignals(results, 'PE') }, openingRange: aggregateBy(results, (entry) => entry.config.openingRange), timeframe: aggregateBy(results, (entry) => `${entry.config.timeframe}m`), breakoutBufferAtr: aggregateBy(results, (entry) => String(entry.config.breakoutBufferAtr)), retestToleranceAtr: aggregateBy(results, (entry) => String(entry.config.retestToleranceAtr)), confirmationBodyAtr: aggregateBy(results, (entry) => String(entry.config.confirmationBodyAtr)), regimeMode: aggregateBy(results, (entry) => entry.config.regimeMode), retestExpiryBars: aggregateBy(results, (entry) => String(entry.config.retestExpiryBars)), cooldownMinutes: aggregateBy(results, (entry) => String(entry.config.cooldownMinutes)) }, highestFrequencyConfigurations: sorted.slice(0, 20).map(compact), representativeMidFrequencyConfigurations: representative, highestFrequencySignalCountsByDate: sorted.slice(0, 5).map((entry) => ({ configKey: entry.configKey, byDate: countByDate(entry.signals) })), suspiciousChecks: suspicious, recommendation: Object.values(suspicious).some((value) => Array.isArray(value) && value.length > 0) ? 'FIX_SIGNAL_ENGINE_FIRST' : 'SAFE_TO_RUN_OUTCOME_RESEARCH', shard: { index: shardIndex, count: shardCount }, shardResults: results.map((entry) => ({ ...compact(entry), signals: entry.signals.map((signal) => ({ date: signal.date, timestamp: signal.timestamp.toISOString(), direction: signal.direction, openingRange: signal.openingRange, breakoutTimestamp: signal.breakoutTimestamp.toISOString(), regimeAvailableAt: signal.regimeAvailableAt?.toISOString() })) })) };
  await mkdir(artifactDirectory, { recursive: true });
  await writeFile(`${artifactDirectory}/phase-1-plan.json`, JSON.stringify({ strategyId: BN_V1_STRATEGY_ID, underlyingKey, mode: 'TRAIN_VALIDATION_ONLY', targetSessions: targetSessions.length, eligibleSessions: orderedEligible.length, splitPolicy: policy, allowedDates, totalConfigurations: configs.length, policyEvaluationsPlanned: policyEvaluations, exits: [{ target: 4, stop: 4 }, { target: 5, stop: 5 }, { target: 6, stop: 5 }], holds: [10, 15, 20], costs: [0.2, 0.4, 0.6, 0.8, 1], finalHoldoutAccessed: false, optionDownloads: 0 }, null, 2));
  await writeFile(`${artifactDirectory}/${shardCount > 1 ? `phase-1-shard-${shardIndex}.json` : 'phase-1-signal-distribution.json'}`, JSON.stringify(artifact, null, 2));
  console.log(JSON.stringify({ strategyId: BN_V1_STRATEGY_ID, targetSessions: targetSessions.length, configurations: configs.length, policyEvaluationsPlanned: policyEvaluations, frequencyBuckets: artifact.frequencyBuckets, frequencyDistribution: artifact.frequencyDistribution, suspiciousChecks: suspicious, recommendation: artifact.recommendation, optionDownloads: 0 }, null, 2));
}

function suspiciousChecks(results: readonly ConfigResult[], sessions: readonly CrossSessionPreparedSession[]) {
  const duplicateSignalTimestamps: string[] = []; const duplicateEpisodes: string[] = []; const preRangeSignals: string[] = []; const orderingViolations: string[] = []; const cooldownViolations: string[] = []; const sessionDates = new Set(sessions.map((session) => session.date));
  results.forEach((entry) => { const timestamps = new Set<number>(); const episodes = new Set<string>(); const previousByDirection = new Map<string, number>(); entry.signals.forEach((signal) => { const time = signal.timestamp.getTime(); if (timestamps.has(time)) duplicateSignalTimestamps.push(`${entry.configKey}|${signal.timestamp.toISOString()}`); timestamps.add(time); if (!sessionDates.has(signal.date)) orderingViolations.push(`${entry.configKey}|unknown-date`); const minimum = signal.openingRange === 'OR15' ? 570 : 585; if (marketMinute(signal.timestamp) < minimum) preRangeSignals.push(`${entry.configKey}|${signal.timestamp.toISOString()}`); if (signal.breakoutTimestamp.getTime() >= time) orderingViolations.push(`${entry.configKey}|${signal.timestamp.toISOString()}`); const episode = `${signal.date}|${signal.direction}|${signal.openingRange}|${signal.breakoutTimestamp.getTime()}`; if (episodes.has(episode)) duplicateEpisodes.push(`${entry.configKey}|${signal.timestamp.toISOString()}`); episodes.add(episode); const previous = previousByDirection.get(signal.direction); if (previous !== undefined && time - previous < entry.config.cooldownMinutes * 60_000) cooldownViolations.push(`${entry.configKey}|${signal.timestamp.toISOString()}`); previousByDirection.set(signal.direction, time); }); });
  return { duplicateSignalTimestamps, duplicateEpisodes, preRangeSignals, breakoutRetestOrderingViolations: orderingViolations, cooldownViolations, regimeNewerThanSignalCompletion: [] };
}
function frequencyBuckets(results: readonly ConfigResult[]) { return { zero: results.filter((entry) => entry.signalCount === 0).length, below025: results.filter((entry) => entry.signalCount > 0 && entry.signalsPerSession < 0.25).length, from025To05: results.filter((entry) => entry.signalsPerSession >= 0.25 && entry.signalsPerSession < 0.5).length, from05To1: results.filter((entry) => entry.signalsPerSession >= 0.5 && entry.signalsPerSession < 1).length, from1To2: results.filter((entry) => entry.signalsPerSession >= 1 && entry.signalsPerSession <= 2).length, from2To5: results.filter((entry) => entry.signalsPerSession > 2 && entry.signalsPerSession <= 5).length, above5: results.filter((entry) => entry.signalsPerSession > 5).length }; }
function distribution(values: readonly number[]) { return { min: round(Math.min(...values)), median: round(percentile(values, 0.5)), p90: round(percentile(values, 0.9)), p95: round(percentile(values, 0.95)), max: round(Math.max(...values)) }; }
function aggregateBy(results: readonly ConfigResult[], selector: (entry: ConfigResult) => string) { const groups = new Map<string, number[]>(); results.forEach((entry) => groups.set(selector(entry), [...(groups.get(selector(entry)) ?? []), entry.signalsPerSession])); return Object.fromEntries([...groups.entries()].map(([key, values]) => [key, { configurations: values.length, average: round(values.reduce((sum, value) => sum + value, 0) / values.length), median: round(percentile(values, 0.5)), p90: round(percentile(values, 0.9)), max: round(Math.max(...values)) }])); }
function aggregateSignals(results: readonly ConfigResult[], direction: 'CE' | 'PE') { const counts = results.map((entry) => entry.signals.filter((signal) => signal.direction === direction).length / Math.max(1, new Set(entry.signals.map((signal) => signal.date)).size)); return { averageSignalsPerActiveConfig: round(counts.reduce((sum, value) => sum + value, 0) / Math.max(1, counts.length)), totalSignals: results.reduce((sum, entry) => sum + entry.signals.filter((signal) => signal.direction === direction).length, 0) }; }
function percentile(values: readonly number[], p: number) { const sorted = [...values].sort((a, b) => a - b); return sorted[Math.min(sorted.length - 1, Math.floor((sorted.length - 1) * p))] ?? 0; }
function countByDate(signals: readonly BankNiftyOpeningRangeSignal[]) { return Object.fromEntries([...signals.reduce((map, signal) => map.set(signal.date, (map.get(signal.date) ?? 0) + 1), new Map<string, number>())].sort(([left], [right]) => left.localeCompare(right))); }
function marketMinute(timestamp: Date) { const parts = Object.fromEntries(new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Kolkata', hour: '2-digit', minute: '2-digit', hourCycle: 'h23' }).formatToParts(timestamp).map((part) => [part.type, part.value])); return Number(parts.hour) * 60 + Number(parts.minute); }
function istDate(timestamp: Date) { const parts = Object.fromEntries(new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Kolkata', year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(timestamp).map((part) => [part.type, part.value])); return `${parts.year}-${parts.month}-${parts.day}`; }
function round(value: number) { return Number(value.toFixed(6)); }

void run().catch((error) => { console.error('BANK NIFTY opening-range signal diagnostic failed:', error instanceof Error ? error.message : String(error)); process.exitCode = 1; });
