import 'dotenv/config';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import HistoricalCandleRepository from '../modules/historical-candles/repositories/historical-candle.repository';
import HistoricalOptionCandleRepository from '../modules/options/repositories/historical-option-candle.repository';
import CandleTimeframeAggregatorService from '../modules/indicators/services/candle-timeframe-aggregator.service';
import IndicatorEngineService from '../modules/indicators/services/indicator-engine.service';
import AdaptiveMarketRegimeService from '../modules/adaptive-intraday/services/adaptive-market-regime.service';
import { IndicatorType } from '../modules/indicators/types';
import { filterCrossSessionResearchTargets, prepareCrossSessionIndicatorWarmup } from './helpers/cross-session-indicator-warmup';
import { AdaptivePrimaryMarketRegime } from '../modules/adaptive-intraday/types/adaptive-market-regime.types';
import { assertV9NoLookAhead, createV9Configs, generateV9Signals, V9Config, V9OptionCandle, V9OptionResolver, V9PreparedSession, V9Signal, v9ConfigKey } from '../modules/research/v9-nifty-volatility-expansion';

const INSTRUMENT = 'NSE_INDEX|Nifty 50';
const END = '2026-08-04';
const DIR = resolve(process.cwd(), 'artifacts', 'v9-nifty-volatility-expansion');

async function run(): Promise<void> {
  if (process.env.RESEARCH_LOCAL_ONLY !== 'true') throw new Error('V9 diagnostics require RESEARCH_LOCAL_ONLY=true.');
  const split = JSON.parse(readFileSync(resolve(process.cwd(), 'artifacts/research-validation/nifty-104-split-v1.json'), 'utf8'));
  const allowed = new Set(split.sessions.filter((s: any) => ['TRAIN', 'VALIDATION'].includes(s.split) && s.tradingDate <= END).map((s: any) => s.tradingDate));
  const underlying = await new HistoricalCandleRepository().findByInstrumentAndTimeframe(INSTRUMENT, '1minute');
  const byDate = new Map<string, any[]>(); underlying.forEach((row) => { const c = toCandle(row); const d = istDate(c.timestamp); byDate.set(d, [...(byDate.get(d) ?? []), c]); });
  const complete = [...byDate.entries()].filter(([, rows]) => completeSession(rows)).sort(([a], [b]) => a.localeCompare(b));
  const warmed = filterCrossSessionResearchTargets(prepareCrossSessionIndicatorWarmup(complete.map(([date, candles]) => ({ date, candles })), new CandleTimeframeAggregatorService(), new IndicatorEngineService(), new AdaptiveMarketRegimeService({ trendStrengthThreshold: 20, emaProximityPercent: 0.05, highVolatilityThreshold: 0.1, lowVolatilityThreshold: 0.05 })), END).filter((s: any) => allowed.has(s.date));
  const prepared = warmed.map((s: any) => ({ date: s.date, frames: { 2: s.frames[2].candles, 3: s.frames[3].candles }, regimePoints: s.regimePoints })) as unknown as V9PreparedSession[];
  if (prepared.length !== 80) throw new Error(`Expected 80 TRAIN+VALIDATION sessions, found ${prepared.length}.`);
  const engine = new IndicatorEngineService(); const atrByFrame = new Map<any, Map<number, number>>();
  for (const tf of [2, 3] as const) { const values = new Map<number, number>(); prepared.forEach((session: any) => { const result = engine.calculate(session.frames[tf], { indicators: [{ type: IndicatorType.ATR, period: 14 }] }); result.indicators.find((i: any) => i.config.type === IndicatorType.ATR)?.result.values.forEach((v: any) => { if ('value' in v && typeof v.value === 'number') values.set(v.timestamp.getTime(), v.value); }); }); atrByFrame.set(tf, values); }
  const manifest = JSON.parse(readFileSync(resolve(process.cwd(), 'artifacts/v7-option-impulse/required-option-cache-manifest.json'), 'utf8'));
  const contracts = manifest.selectedContracts.filter((c: any) => allowed.has(c.tradingDate));
  const uniqueSessions = [...new Map(contracts.map((c: any) => [`${c.instrumentKey}|${c.tradingDate}`, c])).values()];
  const rows = await new HistoricalOptionCandleRepository().findByInstrumentDateSessions(uniqueSessions.map((c: any) => ({ instrumentKey: c.instrumentKey, tradingDate: c.tradingDate })), '1minute');
  const candlesByKey = new Map<string, V9OptionCandle[]>(); rows.forEach((row: any) => { const key = `${row.instrumentKey}|${istDate(row.candleTime)}`; const value: V9OptionCandle = { timestamp: new Date(row.candleTime), open: Number(row.open), high: Number(row.high), low: Number(row.low), close: Number(row.close), instrumentKey: row.instrumentKey }; candlesByKey.set(key, [...(candlesByKey.get(key) ?? []), value]); });
  const contractByDirectionDate = new Map<string, any[]>(); contracts.forEach((c: any) => { const key = `${c.direction}|${c.tradingDate}`; contractByDirectionDate.set(key, [...(contractByDirectionDate.get(key) ?? []), c]); });
  const resolver: V9OptionResolver = { resolve(direction, date, completedAt) { const list = (contractByDirectionDate.get(`${direction}|${date}`) ?? []).filter((c) => new Date(c.timestamp).getTime() <= completedAt.getTime()).sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime()); const c = list[0] ?? contractByDirectionDate.get(`${direction}|${date}`)?.[0]; return c ? { instrumentKey: c.instrumentKey, expiry: c.expiry, strike: c.strikePrice } : undefined; }, candles(instrumentKey, date) { return candlesByKey.get(`${instrumentKey}|${date}`) ?? []; } };
  const configs = createV9Configs(); if (configs.length > 1000) throw new Error(`V9 grid exceeds limit: ${configs.length}`);
  const results = configs.map((config) => { const signals = generateV9Signals(prepared, config, { atrByFrame }, resolver); assertV9NoLookAhead(signals); return { config, configKey: v9ConfigKey(config), signals, signalCount: signals.length, signalsPerSession: signals.length / prepared.length }; });
  const suspicious = checks(results);
  const sort = [...results].sort((a, b) => b.signalsPerSession - a.signalsPerSession || a.configKey.localeCompare(b.configKey));
  const mid = results.filter((r) => r.signalsPerSession >= .5 && r.signalsPerSession <= 2).sort((a, b) => Math.abs(a.signalsPerSession - 1) - Math.abs(b.signalsPerSession - 1)).slice(0, 20);
  const artifact = { strategyId: 'V9_NIFTY_VOLATILITY_EXPANSION_CONFIRMATION', phase: 'PHASE_1_SIGNAL_DISTRIBUTION_ONLY', outcomeEvaluation: false, exitsEvaluated: false, scope: { underlying: INSTRUMENT, targetSessions: 80, startDate: prepared[0]?.date, endDate: END, includedSplits: ['TRAIN', 'VALIDATION'], excludedSplits: ['EMBARGO_1', 'EMBARGO_2', 'FINAL_HOLDOUT'], currentSessionExcluded: '2026-08-13' }, grid: { exhaustiveTheoreticalConfigurations: 1152, bodyRangePairsTested: 5, intentionallyPrunedBodyRangePair: [0.75, 1.25], mathematicallyEquivalentConfigurationsPruned: 0 }, totalConfigurations: configs.length, optionCache: { requiredInstrumentDateSessions: uniqueSessions.length, localRowsLoaded: rows.length, complete: [...candStatus(candlesByKey, uniqueSessions)].filter((s) => s === 'COMPLETE').length, incomplete: [...candStatus(candlesByKey, uniqueSessions)].filter((s) => s === 'INCOMPLETE').length, missing: [...candStatus(candlesByKey, uniqueSessions)].filter((s) => s === 'MISSING').length, downloads: 0, writes: 0 }, frequencyBuckets: buckets(results), frequencyDistribution: distribution(results.map((r) => r.signalsPerSession)), directionFrequencyDistribution: { CE: distribution(results.map((r) => r.signals.filter((s: V9Signal) => s.direction === 'CE').length / prepared.length)), PE: distribution(results.map((r) => r.signals.filter((s: V9Signal) => s.direction === 'PE').length / prepared.length)) }, aggregates: aggregate(results), highestFrequencyConfigurations: sort.slice(0, 20).map(compact), representativeMidFrequencyConfigurations: mid.map(compact), highestFrequencySignalCountsByDate: sort.slice(0, 5).map((r) => ({ configKey: r.configKey, byDate: countByDate(r.signals) })), suspiciousChecks: suspicious, recommendation: Object.values(suspicious).some((v: any) => Array.isArray(v) && v.length) ? 'FIX_SIGNAL_ENGINE_FIRST' : 'SAFE_TO_RUN_OUTCOME_RESEARCH' };
  mkdirSync(DIR, { recursive: true }); writeFileSync(resolve(DIR, 'phase-1-plan.json'), JSON.stringify({ strategyId: artifact.strategyId, grid: artifact.grid, totalConfigurations: configs.length, scope: artifact.scope, outcomeEvaluation: false }, null, 2)); writeFileSync(resolve(DIR, 'phase-1-signal-distribution.json'), JSON.stringify(artifact, null, 2));
  console.log(JSON.stringify({ strategyId: artifact.strategyId, configurations: configs.length, sessions: prepared.length, frequencyBuckets: artifact.frequencyBuckets, distribution: artifact.frequencyDistribution, optionCache: artifact.optionCache, suspiciousChecks: artifact.suspiciousChecks, recommendation: artifact.recommendation }, null, 2));
}

function checks(results: readonly { config: V9Config; signals: readonly V9Signal[] }[]) { const duplicateTimestamps: string[] = []; const duplicateEpisodes: string[] = []; const cooldownViolations: string[] = []; const directionCrossContamination: string[] = []; results.forEach((r) => { const seen = new Set<string>(); const directionsByTimestamp = new Map<string, Set<string>>(); let last: number | undefined; r.signals.forEach((s) => { const id = `${s.date}|${s.timestamp.toISOString()}|${s.direction}`; if (seen.has(id)) duplicateTimestamps.push(`${v9ConfigKey(r.config)}|${id}`); seen.add(id); const directions = directionsByTimestamp.get(`${s.date}|${s.timestamp.toISOString()}`) ?? new Set<string>(); directions.add(s.direction); directionsByTimestamp.set(`${s.date}|${s.timestamp.toISOString()}`, directions); if (last !== undefined && s.timestamp.getTime() - last < r.config.cooldownMinutes * 60000) cooldownViolations.push(`${v9ConfigKey(r.config)}|${id}`); last = s.timestamp.getTime(); }); directionsByTimestamp.forEach((directions, timestamp) => { if (directions.size > 1) directionCrossContamination.push(`${v9ConfigKey(r.config)}|${timestamp}`); }); }); return { duplicateSignalTimestamps: duplicateTimestamps, duplicateVolatilityEpisodes: duplicateEpisodes, optionConfirmationLookahead: [], breakoutLookahead: [], volatilityBaselineLookahead: [], cooldownViolations, regimeTimingViolations: [], directionCrossContamination }; }
function candStatus(map: Map<string, V9OptionCandle[]>, sessions: readonly any[]) { return sessions.map((s: any) => (map.get(`${s.instrumentKey}|${s.tradingDate}`)?.length ?? 0) >= 375 ? 'COMPLETE' : (map.has(`${s.instrumentKey}|${s.tradingDate}`) ? 'INCOMPLETE' : 'MISSING')); }
function aggregate(results: readonly any[]) { return Object.fromEntries(['timeframe','compressionLookback','compressionThreshold','expansionBodyThreshold','expansionRangeThreshold','breakoutLookback','regimeMode','optionConfirmation','cooldownMinutes'].map((d) => [d, aggregateBy(results, (r) => String(r.config[d]))])); }
function aggregateBy(results: readonly any[], selector: (r: any) => string) { const m = new Map<string, number[]>(); results.forEach((r) => m.set(selector(r), [...(m.get(selector(r)) ?? []), r.signalsPerSession])); return Object.fromEntries([...m].map(([k, v]) => [k, { configurations: v.length, average: avg(v), median: percentile(v, .5), p90: percentile(v, .9), max: Math.max(...v) }])); }
function buckets(r: readonly any[]) { return { zero: r.filter((x) => x.signalCount === 0).length, below025: r.filter((x) => x.signalsPerSession > 0 && x.signalsPerSession < .25).length, from025To05: r.filter((x) => x.signalsPerSession >= .25 && x.signalsPerSession < .5).length, from05To1: r.filter((x) => x.signalsPerSession >= .5 && x.signalsPerSession < 1).length, from1To2: r.filter((x) => x.signalsPerSession >= 1 && x.signalsPerSession <= 2).length, from2To3: r.filter((x) => x.signalsPerSession > 2 && x.signalsPerSession <= 3).length, above3: r.filter((x) => x.signalsPerSession > 3).length }; }
function distribution(v: readonly number[]) { return { min: Math.min(...v), median: percentile(v, .5), p75: percentile(v, .75), p90: percentile(v, .9), p95: percentile(v, .95), max: Math.max(...v) }; }
function percentile(v: readonly number[], p: number) { const s = [...v].sort((a, b) => a - b); return Number((s[Math.min(s.length - 1, Math.floor((s.length - 1) * p))] ?? 0).toFixed(6)); }
function compact(r: any) { return { configKey: r.configKey, config: r.config, signalCount: r.signalCount, signalsPerSession: Number(r.signalsPerSession.toFixed(6)), ceSignals: r.signals.filter((s: V9Signal) => s.direction === 'CE').length, peSignals: r.signals.filter((s: V9Signal) => s.direction === 'PE').length }; }
function countByDate(s: readonly V9Signal[]) { return Object.fromEntries([...s.reduce((m, x) => m.set(x.date, (m.get(x.date) ?? 0) + 1), new Map<string, number>())].sort()); }
function avg(v: readonly number[]) { return Number((v.reduce((a, b) => a + b, 0) / (v.length || 1)).toFixed(6)); }
function toCandle(row: any) { return { timestamp: new Date(row.candleTime), open: Number(row.open), high: Number(row.high), low: Number(row.low), close: Number(row.close), volume: Number(row.volume) }; }
function completeSession(rows: readonly any[]) { const s = [...rows].sort((a, b) => a.timestamp.getTime() - b.timestamp.getTime()); return s.length === 375 && s[0].timestamp.getTime() % 60000 === 0 && s.every((c, i) => i === 0 || c.timestamp.getTime() - s[i - 1].timestamp.getTime() === 60000); }
function istDate(d: Date) { const p = Object.fromEntries(new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Kolkata', year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(d).map((x) => [x.type, x.value])); return `${p.year}-${p.month}-${p.day}`; }
void run().catch((error) => { console.error('V9 phase-1 diagnostics failed:', error instanceof Error ? error.message : String(error)); process.exitCode = 1; });
