import 'dotenv/config';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import HistoricalCandleRepository from '../modules/historical-candles/repositories/historical-candle.repository';
import CandleTimeframeAggregatorService from '../modules/indicators/services/candle-timeframe-aggregator.service';
import IndicatorEngineService from '../modules/indicators/services/indicator-engine.service';
import { IndicatorType } from '../modules/indicators/types';
import AdaptiveMarketRegimeService from '../modules/adaptive-intraday/services/adaptive-market-regime.service';
import { filterCrossSessionResearchTargets, prepareCrossSessionIndicatorWarmup } from './helpers/cross-session-indicator-warmup';
import ResearchSplitService from '../modules/research-validation/services/research-split.service';
import { assertV10NoLookAhead, createV10Configs, generateV10Signals, v10ConfigKey, v10TheoreticalConfigurationCount, V10PreparedSession, V10Signal } from '../modules/research/v10-nifty-banknifty-lead-lag';

const NIFTY = 'NSE_INDEX|Nifty 50'; const BANK = 'NSE_INDEX|Nifty Bank'; const END = '2026-08-04'; const DIRECTORY = resolve(process.cwd(), 'artifacts', 'v10-nifty-banknifty-lead-lag');

async function run(): Promise<void> {
  if (process.env.RESEARCH_LOCAL_ONLY !== 'true') throw new Error('V10 phase-1 diagnostics require RESEARCH_LOCAL_ONLY=true.');
  const split = JSON.parse(readFileSync(resolve(process.cwd(), 'artifacts/research-validation/nifty-104-split-v1.json'), 'utf8'));
  const dates = split.sessions.filter((row: any) => ['TRAIN', 'VALIDATION'].includes(row.split) && row.tradingDate <= END).map((row: any) => row.tradingDate);
  new ResearchSplitService().assertOutcomeAccess(split, dates, 'TRAIN_VALIDATION_ONLY');
  if (dates.length !== 80) throw new Error(`Expected 80 protected V10 sessions, found ${dates.length}.`);
  const repository = new HistoricalCandleRepository(); const [niftyRows, bankRows] = await Promise.all([repository.findByInstrumentAndTimeframe(NIFTY, '1minute'), repository.findByInstrumentAndTimeframe(BANK, '1minute')]);
  const nifty = completeByDate(niftyRows); const bank = completeByDate(bankRows); const common = [...nifty.keys()].filter((date) => bank.has(date)).sort();
  const niftyPrepared = prepareCrossSessionIndicatorWarmup(common.map((date) => ({ date, candles: nifty.get(date)! })), new CandleTimeframeAggregatorService(), new IndicatorEngineService(), new AdaptiveMarketRegimeService({ trendStrengthThreshold: 20, emaProximityPercent: .05, highVolatilityThreshold: .1, lowVolatilityThreshold: .05 }));
  const bankPrepared = prepareCrossSessionIndicatorWarmup(common.map((date) => ({ date, candles: bank.get(date)! })), new CandleTimeframeAggregatorService(), new IndicatorEngineService(), new AdaptiveMarketRegimeService({ trendStrengthThreshold: 20, emaProximityPercent: .05, highVolatilityThreshold: .1, lowVolatilityThreshold: .05 }));
  const bankByDate = new Map(bankPrepared.map((session) => [session.date, session]));
  const sessions = filterCrossSessionResearchTargets(niftyPrepared, END).filter((session) => dates.includes(session.date)).map((session) => { const bankSession = bankByDate.get(session.date); if (!bankSession) throw new Error(`Missing prepared BANK NIFTY session ${session.date}.`); return { date: session.date, niftyFrames: { 1: session.frames[1].candles, 2: session.frames[2].candles, 3: session.frames[3].candles }, bankFrames: { 1: bankSession.frames[1].candles, 2: bankSession.frames[2].candles, 3: bankSession.frames[3].candles }, niftyRegimePoints: session.regimePoints }; }) as V10PreparedSession[];
  if (sessions.length !== 80) throw new Error(`V10 needs 80 synchronized protected sessions, found ${sessions.length}.`);
  const indicators = { niftyAtrByFrame: atrMaps(niftyPrepared.filter((session) => dates.includes(session.date))), bankAtrByFrame: atrMaps(bankPrepared.filter((session) => dates.includes(session.date))) };
  const configs = createV10Configs(); if (configs.length > 500) throw new Error(`V10 grid exceeds 500 configurations: ${configs.length}.`);
  const results = configs.map((config) => { const signals = generateV10Signals(sessions, config, indicators); assertV10NoLookAhead(signals); return { config, configKey: v10ConfigKey(config), signals, count: signals.length, perSession: signals.length / sessions.length }; });
  const checks = suspicious(results);
  const sorted = [...results].sort((left, right) => right.perSession - left.perSession || left.configKey.localeCompare(right.configKey));
  const mid = results.filter((row) => row.perSession >= .3 && row.perSession <= 1.5).sort((left, right) => Math.abs(left.perSession - .9) - Math.abs(right.perSession - .9)).slice(0, 20);
  const allSignals = results.flatMap((result) => result.signals); const ce = allSignals.filter((signal) => signal.direction === 'CE'); const pe = allSignals.filter((signal) => signal.direction === 'PE');
  const artifact = {
    strategyId: 'V10_NIFTY_BANKNIFTY_LEAD_LAG', phase: 'PHASE_1_SIGNAL_DIAGNOSTICS_ONLY', outcomeEvaluation: false,
    scope: { mode: 'TRAIN_VALIDATION_ONLY', underlying: { nifty: NIFTY, bankNifty: BANK }, sessions: sessions.length, startDate: sessions[0]?.date, endDate: sessions.at(-1)?.date, excluded: ['EMBARGO_1', 'EMBARGO_2', 'FINAL_HOLDOUT', '2026-08-13'], localOnly: true, networkRequests: 0, cacheWrites: 0 },
    grid: { theoreticalCartesianConfigurations: v10TheoreticalConfigurationCount(), structuralReduction: 'Two predeclared execution-context profiles; no outcome-based pruning.', profiles: ['NO_REGIME_FILTER|FULL_SESSION|5m', 'ANY_EXCEPT_OPPOSITE|EXCLUDE_FIRST_15M|10m'], finalConfigurations: configs.length },
    frequencyBuckets: buckets(results), frequencyDistribution: distribution(results.map((result) => result.perSession)), CE: directionStats(ce, sessions.length), PE: directionStats(pe, sessions.length), combinedUniqueTimestamps: new Set(allSignals.map((signal) => signal.timestamp.getTime())).size,
    aggregates: aggregates(results), highestFrequencyConfigurations: sorted.slice(0, 20).map(compact), representativeConfigurations: mid.map(compact), highestFrequencyDateCounts: sorted.slice(0, 5).map((result) => ({ configKey: result.configKey, byTradingDate: countByDate(result.signals) })),
    leadLagMeasurements: measurements(allSignals), suspiciousChecks: checks,
    recommendation: Object.values(checks).some((value: any) => Array.isArray(value) && value.length > 0) ? 'FIX_SIGNAL_ENGINE_FIRST' : recommendation(results, measurements(allSignals)),
  };
  mkdirSync(DIRECTORY, { recursive: true }); write('phase-1-plan.json', { strategyId: artifact.strategyId, scope: artifact.scope, grid: artifact.grid, outcomeEvaluation: false }); write('phase-1-signal-distribution.json', artifact);
  console.log(JSON.stringify({ strategyId: artifact.strategyId, protectedSessions: sessions.length, grid: artifact.grid, frequencyBuckets: artifact.frequencyBuckets, distribution: artifact.frequencyDistribution, CE: artifact.CE, PE: artifact.PE, leadLagMeasurements: artifact.leadLagMeasurements, suspiciousChecks: checks, recommendation: artifact.recommendation }, null, 2));
}

function completeByDate(rows: readonly any[]) { const map = new Map<string, any[]>(); rows.forEach((row) => { const candle = { timestamp: new Date(row.candleTime), open: Number(row.open), high: Number(row.high), low: Number(row.low), close: Number(row.close), volume: Number(row.volume) }; const date = istDate(candle.timestamp); map.set(date, [...(map.get(date) ?? []), candle]); }); return new Map([...map].filter(([, candles]) => complete(candles))); }
function atrMaps(sessions: readonly any[]) { const engine = new IndicatorEngineService(); const maps = new Map<any, Map<number, number>>(); for (const timeframe of [1, 2, 3] as const) { const values = new Map<number, number>(); sessions.forEach((session) => engine.calculate(session.frames[timeframe].allCandles, { indicators: [{ type: IndicatorType.ATR, period: 14 }] }).indicators.find((indicator: any) => indicator.config.type === IndicatorType.ATR)?.result.values.forEach((value: any) => { if ('value' in value && typeof value.value === 'number') values.set(value.timestamp.getTime(), value.value); })); maps.set(timeframe, values); } return maps; }
function suspicious(results: readonly any[]) { const duplicateTimestamps: string[] = []; const duplicateEpisodes: string[] = []; const futureConfirmation: string[] = []; const futureBank: string[] = []; const timestampMisalignment: string[] = []; const crossSessionLeakage: string[] = []; const atrLookahead: string[] = []; const cooldownViolations: string[] = []; const directionMismatch: string[] = []; results.forEach((result) => { const seen = new Set<string>(); const last: Partial<Record<'CE' | 'PE', number>> = {}; result.signals.forEach((signal: V10Signal) => { const id = `${signal.date}|${signal.timestamp.toISOString()}|${signal.direction}`; if (seen.has(id)) duplicateTimestamps.push(`${result.configKey}|${id}`); seen.add(id); if (signal.bankImpulseCompletedAt > signal.timestamp) futureBank.push(id); if (signal.regimeAvailableAt && signal.regimeAvailableAt > signal.timestamp) futureConfirmation.push(id); if (signal.bankImpulseTimestamp.getTime() % (result.config.timeframe * 60000) !== signal.timestamp.getTime() % (result.config.timeframe * 60000)) timestampMisalignment.push(id); if (signal.bankImpulseTimestamp.getTime() > signal.timestamp.getTime() || signal.date !== istDate(signal.timestamp)) crossSessionLeakage.push(id); if (Math.sign(signal.bankNormalizedImpulse) !== (signal.direction === 'CE' ? 1 : -1)) directionMismatch.push(id); if (last[signal.direction] !== undefined && signal.timestamp.getTime() - last[signal.direction]! < result.config.cooldownMinutes * 60000) cooldownViolations.push(id); last[signal.direction] = signal.timestamp.getTime(); }); }); return { duplicateTimestamps, duplicateEpisodes, futureConfirmationUsage: futureConfirmation, futureBankNiftyUsage: futureBank, timestampMisalignment, crossSessionLeakage, atrLookahead, cooldownViolations, directionMismatch }; }
function directionStats(signals: readonly V10Signal[], sessions: number) { return { totalSignalsAcrossConfigurations: signals.length, uniqueTimestamps: new Set(signals.map((signal) => signal.timestamp.getTime())).size, averageUniqueSignalsPerSession: round(new Set(signals.map((signal) => `${signal.date}|${signal.timestamp.getTime()}`)).size / sessions), activeSessions: new Set(signals.map((signal) => signal.date)).size, maxUniqueSignalsPerDay: Math.max(0, ...Object.values(countByDate(signals))) }; }
function measurements(signals: readonly V10Signal[]) { return { averageBankNormalizedImpulse: round(avg(signals.map((signal) => Math.abs(signal.bankNormalizedImpulse))), 6), averageNiftyNormalizedMoveBeforeConfirmation: round(avg(signals.map((signal) => Math.abs(signal.niftyNormalizedMoveBeforeConfirmation))), 6), averageLeadTimeMinutes: round(avg(signals.map((signal) => signal.leadTimeMinutes)), 6), sameBarPercent: round(signals.filter((signal) => signal.confirmationDelayBars === 0).length / Math.max(1, signals.length) * 100), delayedConfirmationPercent: round(signals.filter((signal) => signal.confirmationDelayBars > 0).length / Math.max(1, signals.length) * 100), CEPercent: round(signals.filter((signal) => signal.direction === 'CE').length / Math.max(1, signals.length) * 100), PEPercent: round(signals.filter((signal) => signal.direction === 'PE').length / Math.max(1, signals.length) * 100) }; }
function aggregates(results: readonly any[]) { const fields = ['timeframe', 'bankImpulseLookbackBars', 'bankImpulseThresholdAtr', 'niftyLagRatioMaximum', 'confirmationDelayBars', 'confirmation', 'regimeMode', 'timeFilter', 'cooldownMinutes']; return Object.fromEntries(fields.map((field) => [field, aggregateBy(results, (result) => String(result.config[field]))])); }
function aggregateBy(results: readonly any[], pick: (result: any) => string) { const groups = new Map<string, number[]>(); results.forEach((result) => groups.set(pick(result), [...(groups.get(pick(result)) ?? []), result.perSession])); return Object.fromEntries([...groups].map(([key, values]) => [key, { configurations: values.length, averageSignalsPerSession: round(avg(values), 6), medianSignalsPerSession: percentile(values, .5), p90SignalsPerSession: percentile(values, .9), maximumSignalsPerSession: round(Math.max(...values), 6) }])); }
function buckets(results: readonly any[]) { return { zero: results.filter((row) => row.count === 0).length, below025: results.filter((row) => row.perSession > 0 && row.perSession < .25).length, from025To05: results.filter((row) => row.perSession >= .25 && row.perSession < .5).length, from05To1: results.filter((row) => row.perSession >= .5 && row.perSession < 1).length, from1To15: results.filter((row) => row.perSession >= 1 && row.perSession < 1.5).length, from15To2: results.filter((row) => row.perSession >= 1.5 && row.perSession <= 2).length, above2: results.filter((row) => row.perSession > 2).length }; }
function compact(result: any) { return { configKey: result.configKey, config: result.config, signals: result.count, signalsPerSession: round(result.perSession, 6), CE: result.signals.filter((signal: V10Signal) => signal.direction === 'CE').length, PE: result.signals.filter((signal: V10Signal) => signal.direction === 'PE').length, measurements: measurements(result.signals) }; }
function countByDate(signals: readonly V10Signal[]) { return Object.fromEntries([...signals.reduce((map, signal) => map.set(signal.date, (map.get(signal.date) ?? 0) + 1), new Map<string, number>())].sort()); }
function recommendation(results: readonly any[], measured: ReturnType<typeof measurements>) { const meaningful = results.filter((row) => row.perSession >= .25 && row.perSession <= 1.5); if (!meaningful.length) return 'LEAD_LAG_HYPOTHESIS_NOT_SUPPORTED'; /* Same-bar confirmation cannot demonstrate a temporal lead. */ if (measured.averageLeadTimeMinutes < 1 || measured.sameBarPercent >= 50) return 'LEAD_LAG_HYPOTHESIS_NOT_SUPPORTED'; return 'SAFE_TO_RUN_OUTCOME_RESEARCH'; }
function distribution(values: readonly number[]) { return { min: round(Math.min(...values), 6), median: percentile(values, .5), p75: percentile(values, .75), p90: percentile(values, .9), p95: percentile(values, .95), max: round(Math.max(...values), 6) }; }
function percentile(values: readonly number[], p: number) { const ordered = [...values].sort((left, right) => left - right); return round(ordered[Math.floor((ordered.length - 1) * p)] ?? 0, 6); }
function avg(values: readonly number[]) { return values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : 0; }
function round(value: number, decimals = 4) { return Number(value.toFixed(decimals)); }
function complete(rows: readonly { timestamp: Date }[]) { const sorted = [...rows].sort((left, right) => left.timestamp.getTime() - right.timestamp.getTime()); return sorted.length === 375 && sorted.every((row, index) => index === 0 || row.timestamp.getTime() - sorted[index - 1].timestamp.getTime() === 60_000); }
function istDate(value: Date) { const parts = Object.fromEntries(new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Kolkata', year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(value).map((part) => [part.type, part.value])); return `${parts.year}-${parts.month}-${parts.day}`; }
function write(name: string, value: unknown) { writeFileSync(resolve(DIRECTORY, name), `${JSON.stringify(value, null, 2)}\n`); }
void run().catch((error) => { console.error('V10 phase-1 diagnostics failed:', error instanceof Error ? error.stack ?? error.message : String(error)); process.exitCode = 1; });
