import dotenv from 'dotenv';
import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import logger from '../core/logger/logger';
import HistoricalCandleRepository from '../modules/historical-candles/repositories/historical-candle.repository';
import CandleTimeframeAggregatorService from '../modules/indicators/services/candle-timeframe-aggregator.service';
import IndicatorEngineService from '../modules/indicators/services/indicator-engine.service';
import { IndicatorType } from '../modules/indicators/types';
import AdaptiveMarketRegimeService from '../modules/adaptive-intraday/services/adaptive-market-regime.service';
import { AdaptivePrimaryMarketRegime } from '../modules/adaptive-intraday/types/adaptive-market-regime.types';
import UpstoxExpiredOptionCandleClient from '../modules/options/client/upstox-expired-option-candle.client';
import UpstoxExpiredOptionClient from '../modules/options/client/upstox-expired-option.client';
import { OptionExitPolicyEvaluationResult } from '../modules/options/dto/option-exit-policy.dto';
import HistoricalOptionCandleRepository from '../modules/options/repositories/historical-option-candle.repository';
import HistoricalOptionResearchPreloaderService from '../modules/options/services/historical-option-research-preloader.service';
import HistoricalOptionCandleCacheService from '../modules/options/services/historical-option-candle-cache.service';
import OptionContractSelectorService from '../modules/options/services/option-contract-selector.service';
import OptionPremiumPathAnalysisService from '../modules/options/services/option-premium-path-analysis.service';
import { OptionContract } from '../modules/options/types';
import { StrategySignal } from '../modules/strategies/dto/strategy-signal.dto';
import { filterCrossSessionResearchTargets, prepareCrossSessionIndicatorWarmup, CrossSessionPreparedSession } from './helpers/cross-session-indicator-warmup';
import { PreparedOptionSignalResolution, prepareOptionSignalResolution } from './helpers/prepared-option-signal-resolution';
import { chooseHistoricalOptionExpiry } from './helpers/v3-option-cache-diagnostics';
import { matchesTrendDirectionalEma35Pullback } from './helpers/trend-directional-ema35-pullback';
import { V4IndicatorContext, V4Signal, createV4Configs, generateV4Signals } from './helpers/v4-structural-signal-generation';
import { assertV5NoLookAhead, createV5ScalpingConfigs, deduplicateV5Signals, generateV5Signals, prepareV5IndicatorContext, v5ConfigKey, V5Direction, V5ScalpingConfig, V5Signal } from './helpers/v5-nifty-scalping-signal-generation';

dotenv.config();
logger.silent = true;

const instrumentKey = 'NSE_INDEX|Nifty 50';
const endDate = process.env.RESEARCH_END_DATE?.trim() || '2026-08-04';
const policies = [
  { target: 2, stop: 2, hold: 3 }, { target: 2, stop: 2, hold: 5 }, { target: 3, stop: 2, hold: 5 },
  { target: 3, stop: 3, hold: 5 }, { target: 4, stop: 3, hold: 7 },
] as const;
const costs = [0.2, 0.4, 0.6] as const;
const minimumTrades = 30;
const artifactsDirectory = resolve(process.cwd(), 'artifacts', 'v5-scalping');

interface Resolution { entryPremium: number; mfe5: number | null; mae5: number | null; exits: ReadonlyMap<string, OptionExitPolicyEvaluationResult>; }
interface Trade { signal: V5Signal; resolution: Resolution; }
interface Report { config: V5ScalpingConfig; signals: readonly V5Signal[]; trades: readonly Trade[]; unavailableEntryCount: number; }
interface Metric { target: number; stop: number; hold: number; resolvedTrades: number; settledTrades: number; targetCount: number; stopCount: number; timeoutCount: number; ambiguousCount: number; unavailableCount: number; grossAverage: number; grossMedian: number; net20: number; net40: number; net60: number; targetRate: number; stopRate: number; timeoutRate: number; ambiguousRate: number; mfe5: number; mae5: number; returns: number[]; }
interface Candidate { report: Report; metric: Metric; }

async function run(): Promise<void> {
  if (process.env.RESEARCH_LOCAL_ONLY !== 'true') throw new Error('V5 outcomes require RESEARCH_LOCAL_ONLY=true.');
  const token = process.env.UPSTOX_ACCESS_TOKEN?.trim();
  if (!token) throw new Error('Set UPSTOX_ACCESS_TOKEN in .env.');
  const underlyingRepository = new HistoricalCandleRepository();
  const optionRepository = new HistoricalOptionCandleRepository();
  const cache = new HistoricalOptionCandleCacheService(optionRepository, new UpstoxExpiredOptionCandleClient(token));
  const preloader = new HistoricalOptionResearchPreloaderService(underlyingRepository, optionRepository, cache, true);
  const engine = new IndicatorEngineService(); const aggregator = new CandleTimeframeAggregatorService();
  const regime = new AdaptiveMarketRegimeService({ trendStrengthThreshold: 20, emaProximityPercent: 0.05, highVolatilityThreshold: 0.1, lowVolatilityThreshold: 0.05 });
  const underlying = await preloader.preloadUnderlying(instrumentKey, '1minute');
  const complete = [...underlying.underlyingByDate.entries()].filter(([, candles]) => completeSession(candles)).sort(([a], [b]) => a.localeCompare(b));
  const sessions = filterCrossSessionResearchTargets(prepareCrossSessionIndicatorWarmup(complete.map(([date, candles]) => ({ date, candles })), aggregator, engine, regime), endDate);
  if (sessions.length !== 104) throw new Error(`Expected 104 validated V5 target sessions through ${endDate}; found ${sessions.length}.`);
  const configs = createV5ScalpingConfigs(); const indicators = prepareV5IndicatorContext(sessions, engine);
  const signalSets = new Map<string, V5Signal[]>();
  configs.forEach((config) => { const signals = generateV5Signals(sessions, config, indicators); assertV5NoLookAhead(signals); signalSets.set(v5ConfigKey(config), signals); });
  const uniqueSignals = deduplicateV5Signals([...signalSets.values()].flat());
  console.log('V5 NIFTY SCALPING PHASE 2 | OUTCOME RESEARCH', { targetSessions: sessions.length, range: `${sessions[0].date}..${sessions.at(-1)?.date}`, configurations: configs.length, ceConfigurations: configs.filter((c) => c.direction === 'CE').length, peConfigurations: configs.filter((c) => c.direction === 'PE').length, uniqueDirectionalSignalTimestamps: uniqueSignals.length, policiesPerConfiguration: policies.length, policyEvaluations: configs.length * policies.length, localOnly: true });
  const optionClient = new UpstoxExpiredOptionClient(token); const selector = new OptionContractSelectorService();
  const expiryCache = new Map<string, Promise<string[]>>(); const contractCache = new Map<string, Promise<OptionContract[]>>();
  const prepared = await mapConcurrent(uniqueSignals, 3, (signal) => prepare(signal, optionClient, selector, expiryCache, contractCache));
  await preloader.preloadOptionSessions(prepared);
  const resolutionBySignal = new Map<string, Resolution>(); const failures: string[] = [];
  await mapConcurrent(prepared, 12, async (item) => { try { resolutionBySignal.set(signalKey(item.signal), await resolvePath(item, preloader)); } catch (error) { failures.push(`${item.signal.direction} ${item.signal.timestamp.toISOString()} ${error instanceof Error ? error.message : String(error)}`); } });
  const preload = preloader.getStats();
  if (preload.upstoxMissingSessionDownloads !== 0 || preload.dbFallbackHits !== 0) throw new Error('V5 outcome research violated local preloaded option-cache requirements.');
  const reports: Report[] = configs.map((config) => {
    const signals = signalSets.get(v5ConfigKey(config)) ?? [];
    const trades = signals.flatMap((signal) => { const resolution = resolutionBySignal.get(signalKey(signal)); return resolution ? [{ signal, resolution }] : []; });
    return { config, signals, trades, unavailableEntryCount: signals.length - trades.length };
  });
  const v2 = frozenV2Signals(sessions); const v4 = frozenV4Signals(sessions, engine);
  const ce = reports.filter((report) => report.config.direction === 'CE'); const pe = reports.filter((report) => report.config.direction === 'PE');
  const ceResult = analyzeDirection('CE', ce, sessions, v2, v4); const peResult = analyzeDirection('PE', pe, sessions, v2, v4);
  const combined = analyzeCombined(ceResult.bestBalanced, peResult.bestBalanced, sessions);
  const tier = frequencyTiers([...ceResult.allCandidates, ...peResult.allCandidates], sessions);
  mkdirSync(artifactsDirectory, { recursive: true });
  write('outcome-grid-results.json', reports.flatMap((report) => policies.map((policy) => serializeCandidate({ report, metric: metric(report.trades, policy.target, policy.stop, policy.hold) }, sessions))));
  const combinedDetails = 'robustness' in combined ? combined : undefined;
  write('ce-ranking.json', rankingArtifact(ceResult, sessions)); write('pe-ranking.json', rankingArtifact(peResult, sessions)); write('combined-ranking.json', combined); write('robustness-report.json', { CE: ceResult.leaderRobustness, PE: peResult.leaderRobustness, combined: combinedDetails?.robustness });
  write('daily-results.json', { CE: ceResult.leaderDaily, PE: peResult.leaderDaily, combined: combinedDetails?.daily }); write('monthly-results.json', { CE: ceResult.leaderRobustness, PE: peResult.leaderRobustness, combined: combinedDetails?.robustness }); write('frequency-tier-analysis.json', tier); write('overlap-report.json', { CE: ceResult.overlap, PE: peResult.overlap });
  const final = { targetSessions: sessions.length, configurations: configs.length, policiesPerConfiguration: policies.length, totalPolicyEvaluations: configs.length * policies.length, CE: summary(ceResult, sessions), PE: summary(peResult, sessions), combined, frequencyTiers: tier, preloader: preload, pathAnalyses: resolutionBySignal.size, unresolvedEntries: failures.length, finalVerdict: verdict(ceResult.bestBalanced, peResult.bestBalanced) };
  write('final-v5-research-summary.json', final);
  console.log('\nV5 CE FINDINGS', summary(ceResult, sessions)); console.log('\nV5 PE FINDINGS', summary(peResult, sessions)); console.log('\nV5 COMBINED PORTFOLIO', combined); console.log('\nV5 HIGH-FREQUENCY TIERS', tier); console.log('\nV5 CACHE / PERFORMANCE', { ...preload, optionPathAnalyses: resolutionBySignal.size, unresolvedEntryPremiums: failures.length, upstoxDownloads: preload.upstoxMissingSessionDownloads, dbFallbackHits: preload.dbFallbackHits }); console.log('\nV5 FINAL VERDICT', final.finalVerdict); console.log('V5 ARTIFACTS', { directory: 'artifacts/v5-scalping', files: ['outcome-grid-results.json', 'ce-ranking.json', 'pe-ranking.json', 'combined-ranking.json', 'robustness-report.json', 'daily-results.json', 'monthly-results.json', 'frequency-tier-analysis.json', 'overlap-report.json', 'final-v5-research-summary.json'] });
}

function analyzeDirection(direction: V5Direction, reports: readonly Report[], sessions: readonly CrossSessionPreparedSession[], v2: readonly V5Signal[], v4: readonly V4Signal[]) {
  const all = reports.flatMap((report) => policies.map((policy) => ({ report, metric: metric(report.trades, policy.target, policy.stop, policy.hold) })).filter((candidate) => candidate.metric.resolvedTrades >= minimumTrades));
  const credible = all.filter(isCredible); const pool = credible.length ? credible : all; const ranked = [...pool].sort(rank);
  const highestFrequency = [...pool].sort((a, b) => b.metric.resolvedTrades - a.metric.resolvedTrades || rank(a, b))[0];
  const highestQuality = ranked[0]; const bestBalanced = [...pool].filter((candidate) => candidate.metric.resolvedTrades / sessions.length >= 1).sort(rank)[0] ?? highestQuality;
  const leaders = unique([highestFrequency, highestQuality, bestBalanced].filter((value): value is Candidate => !!value));
  console.log(`\nV5 ${direction} | configs=${reports.length} policies/config=${policies.length}`, { policyCandidates: all.length, credibleAfter040Cost: credible.length, highestSustainableFrequencyPerSession: round(Math.max(0, ...credible.map((candidate) => candidate.metric.resolvedTrades / sessions.length)))});
  console.log('Highest frequency:', highestFrequency ? line(highestFrequency, sessions) : 'NONE'); console.log('Highest quality:', highestQuality ? line(highestQuality, sessions) : 'NONE'); console.log('Best balanced:', bestBalanced ? line(bestBalanced, sessions) : 'NONE');
  ranked.slice(0, 20).forEach((candidate, index) => console.log(`${direction} TOP ${index + 1}. ${line(candidate, sessions)}`));
  const leaderRobustness = leaders.map((candidate) => ({ candidate: serializeCandidate(candidate, sessions), robustness: robustness(candidate, sessions) }));
  const leaderDaily = leaders.map((candidate) => ({ candidate: serializeCandidate(candidate, sessions), daily: daily(candidate, sessions) }));
  const overlap = bestBalanced ? overlapFor(bestBalanced, v2, v4, sessions) : undefined;
  return { direction, policyCandidates: all.length, credibleAfter040Cost: credible.length, allCandidates: all, ranked: ranked.slice(0, 20), highestFrequency, highestQuality, bestBalanced, leaderRobustness, leaderDaily, overlap };
}

function analyzeCombined(ce: Candidate | undefined, pe: Candidate | undefined, sessions: readonly CrossSessionPreparedSession[]) {
  if (!ce || !pe || !isCredible(ce) || !isCredible(pe)) return { status: 'NOT_COMBINED: both CE and PE must independently pass the 0.40%-cost credibility screen.' };
  const records = [...settledRecords(ce), ...settledRecords(pe)].sort((a, b) => a.trade.signal.timestamp.getTime() - b.trade.signal.timestamp.getTime()); const returns = records.map((entry) => entry.exit.premiumChangePercent!);
  const dates = new Map<string, number>(); records.forEach((record) => dates.set(record.trade.signal.date, (dates.get(record.trade.signal.date) ?? 0) + record.exit.premiumChangePercent!));
  const dailyRows = [...dates.entries()]
    .map(([date, grossReturn]) => ({
      date,
      grossReturn: round(grossReturn),
      netAt040: round(grossReturn - .4 * records.filter((record) => record.trade.signal.date === date).length),
    }))
    .sort((a, b) => a.date.localeCompare(b.date));
  const result = { status: 'COMBINED', CE: serializeCandidate(ce, sessions), PE: serializeCandidate(pe, sessions), trades: records.length, tradesPerSession: round(records.length / sessions.length), grossAverage: round(average(returns)), grossMedian: round(median(returns)), netAverageAt040: round(average(returns) - .4), profitableDayPercent: round([...dates.values()].filter((value) => value > 0).length / Math.max(1, dates.size) * 100), maxLosingTradeStreak: streak(records.map((record) => record.exit.premiumChangePercent! < 0)), CEContribution: records.filter((record) => record.trade.signal.direction === 'CE').length, PEContribution: records.filter((record) => record.trade.signal.direction === 'PE').length, daily: dailyRows };
  return { ...result, robustness: combinedRobustness(records, sessions) };
}

async function prepare(signal: V5Signal, client: UpstoxExpiredOptionClient, selector: OptionContractSelectorService, expiryCache: Map<string, Promise<string[]>>, contractCache: Map<string, Promise<OptionContract[]>>): Promise<PreparedOptionSignalResolution<V5Signal>> {
  const expiries = await cached(expiryCache, instrumentKey, () => client.fetchAvailableExpiries(instrumentKey)); const expiry = chooseHistoricalOptionExpiry(expiries, signal.date); const contracts = await cached(contractCache, expiry, () => client.fetchExpiredOptionContracts(instrumentKey, expiry)); const underlying = contracts[0]?.underlying; if (!underlying) throw new Error(`Missing historical option metadata for ${expiry}.`);
  const selected = selector.select({ underlying, spotPrice: signal.spotPrice, signal: signal.direction === 'CE' ? StrategySignal.BUY_CE : StrategySignal.BUY_PE, timestamp: signal.timestamp, contracts });
  return prepareOptionSignalResolution(signal, { ...selected, exchange: '', segment: '' }, signal.date);
}

async function resolvePath(item: PreparedOptionSignalResolution<V5Signal>, preloader: HistoricalOptionResearchPreloaderService): Promise<Resolution> {
  const path = new OptionPremiumPathAnalysisService(item.signal.timestamp, await preloader.getOptionSession(item)); const analytics = path.researchAnalytics({ changeHorizons: [], excursionHorizons: [5], upsideTargets: [], downsideStops: [] });
  const exits = new Map<string, OptionExitPolicyEvaluationResult>(); policies.forEach((policy) => exits.set(policyKey(policy.target, policy.stop, policy.hold), path.evaluate({ type: 'TARGET_STOP', targetPercent: policy.target, stopLossPercent: policy.stop, maximumHoldingMinutes: policy.hold })));
  const excursion = analytics.excursions.get(5); return { entryPremium: analytics.entryPremium, mfe5: excursion?.mfe ?? null, mae5: excursion?.mae ?? null, exits };
}

function metric(trades: readonly Trade[], target: number, stop: number, hold: number): Metric { const exits = trades.map((trade) => trade.resolution.exits.get(policyKey(target, stop, hold))).filter((exit): exit is OptionExitPolicyEvaluationResult => !!exit); const settled = exits.filter((exit) => !exit.ambiguous && !exit.unavailable && exit.premiumChangePercent !== null); const returns = settled.map((exit) => exit.premiumChangePercent!); const targetCount = settled.filter((exit) => exit.exitReason === 'TARGET').length; const stopCount = settled.filter((exit) => exit.exitReason === 'STOP_LOSS').length; const timeoutCount = settled.filter((exit) => exit.exitReason === 'TIME_EXIT').length; return { target, stop, hold, resolvedTrades: trades.length, settledTrades: settled.length, targetCount, stopCount, timeoutCount, ambiguousCount: exits.filter((exit) => exit.ambiguous).length, unavailableCount: exits.filter((exit) => exit.unavailable).length, grossAverage: average(returns), grossMedian: median(returns), net20: average(returns)-.2, net40: average(returns)-.4, net60: average(returns)-.6, targetRate: rate(targetCount, settled.length), stopRate: rate(stopCount, settled.length), timeoutRate: rate(timeoutCount, settled.length), ambiguousRate: rate(exits.filter((exit) => exit.ambiguous).length, exits.length), mfe5: average(trades.map((trade) => trade.resolution.mfe5).filter((value): value is number => value !== null)), mae5: average(trades.map((trade) => trade.resolution.mae5).filter((value): value is number => value !== null)), returns }; }
function isCredible(candidate: Candidate): boolean { const m=candidate.metric; return m.resolvedTrades >= minimumTrades && m.net40 > 0 && m.grossMedian >= 0 && m.targetRate > m.stopRate; }
function rank(a: Candidate, b: Candidate): number { const x=a.metric,y=b.metric; return y.net40-x.net40 || y.grossMedian-x.grossMedian || y.targetRate-x.targetRate || x.stopRate-y.stopRate || y.resolvedTrades-x.resolvedTrades; }
function line(candidate: Candidate, sessions: readonly CrossSessionPreparedSession[]): string { const m=candidate.metric; return `${v5ConfigKey(candidate.report.config)} | +${m.target}/-${m.stop}/${m.hold}m | trades=${m.resolvedTrades} freq=${(m.resolvedTrades/sessions.length).toFixed(2)} gross=${m.grossAverage.toFixed(2)} med=${m.grossMedian.toFixed(2)} net20=${m.net20.toFixed(2)} net40=${m.net40.toFixed(2)} net60=${m.net60.toFixed(2)} target=${m.targetRate.toFixed(2)} stop=${m.stopRate.toFixed(2)} time=${m.timeoutRate.toFixed(2)} amb=${m.ambiguousRate.toFixed(2)} MFE5=${m.mfe5.toFixed(2)} MAE5=${m.mae5.toFixed(2)}`; }
function serializeCandidate(candidate: Candidate, sessions: readonly CrossSessionPreparedSession[]) { const { config }=candidate.report; const m=candidate.metric; return { configKey:v5ConfigKey(config), direction:config.direction, config, policy:{target:m.target,stop:m.stop,hold:m.hold}, resolvedTrades:m.resolvedTrades,tradesPerSession:round(m.resolvedTrades/sessions.length),activeSessionTrades:frequency(candidate,sessions).averageTradesPerActiveSession,maxTradesPerDay:frequency(candidate,sessions).maximumTradesInOneDay,grossAverage:round(m.grossAverage),grossMedian:round(m.grossMedian),netAverageAt020:round(m.net20),netAverageAt040:round(m.net40),netAverageAt060:round(m.net60),targetRate:round(m.targetRate),stopRate:round(m.stopRate),timeoutRate:round(m.timeoutRate),ambiguousRate:round(m.ambiguousRate),ambiguousCount:m.ambiguousCount,unavailableCount:m.unavailableCount,mfe5:round(m.mfe5),mae5:round(m.mae5),credibleAt040:isCredible(candidate) }; }
function frequency(candidate: Candidate, sessions: readonly CrossSessionPreparedSession[]) { const counts=sessions.map((session)=>candidate.report.trades.filter((trade)=>trade.signal.date===session.date).length); const active=counts.filter((count)=>count>0); return { tradesPerSession:round(candidate.metric.resolvedTrades/sessions.length),averageTradesPerActiveSession:round(candidate.metric.resolvedTrades/Math.max(1,active.length)),daysWith0Trades:counts.filter((count)=>count===0).length,daysWith1To4Trades:counts.filter((count)=>count>=1&&count<=4).length,daysWith5To9Trades:counts.filter((count)=>count>=5&&count<=9).length,daysWith10PlusTrades:counts.filter((count)=>count>=10).length,maximumTradesInOneDay:Math.max(...counts) }; }
function daily(candidate: Candidate, sessions: readonly CrossSessionPreparedSession[]) { const m=candidate.metric; return sessions.map((session)=>{const exits=settledRecords(candidate).filter((record)=>record.trade.signal.date===session.date).map((record)=>record.exit.premiumChangePercent!);return {date:session.date,trades:exits.length,grossAverage:round(average(exits)),grossSum:round(exits.reduce((a,b)=>a+b,0)),netSumAt040:round(exits.reduce((a,b)=>a+b,0)-.4*exits.length)};}); }
function robustness(candidate: Candidate, sessions: readonly CrossSessionPreparedSession[]) { const m=candidate.metric; const summary=(trades:readonly Trade[])=>{const value=metric(trades,m.target,m.stop,m.hold);return {trades:value.resolvedTrades,grossAverage:round(value.grossAverage),netAverageAt040:round(value.net40),median:round(value.grossMedian),targetRate:round(value.targetRate),stopRate:round(value.stopRate)};}; const month=[['March','2026-03'],['April','2026-04'],['May','2026-05'],['June','2026-06'],['July','2026-07'],['Aug 1-4','2026-08']].map(([month,prefix])=>({month,...summary(candidate.report.trades.filter((trade)=>trade.signal.date.startsWith(prefix)))})); const mid=Math.floor(sessions.length/2),h1=new Set(sessions.slice(0,mid).map((x)=>x.date)),h2=new Set(sessions.slice(mid).map((x)=>x.date)); const returns=m.returns,sorted=[...returns].sort((a,b)=>a-b),days=daily(candidate,sessions).map((x)=>x.grossSum),positive=returns.filter((x)=>x>0).reduce((a,b)=>a+b,0);return {monthly:month,halves:[{period:'First half',...summary(candidate.report.trades.filter((trade)=>h1.has(trade.signal.date)))},{period:'Second half',...summary(candidate.report.trades.filter((trade)=>h2.has(trade.signal.date)))}],frequency:frequency(candidate,sessions),profitableDayPercent:round(days.filter((x)=>x>0).length/Math.max(1,days.filter((x)=>x!==0).length)*100),maxConsecutiveLosses:streak(settledRecords(candidate).sort((a,b)=>a.trade.signal.timestamp.getTime()-b.trade.signal.timestamp.getTime()).map((x)=>x.exit.premiumChangePercent!<0)),maxLosingDayStreak:streak(days.map((x)=>x<0)),averageExcludingBest5:round(average(sorted.slice(0,Math.max(0,sorted.length-5)))),best5ContributionPercent:round(positive?sorted.slice(-5).filter((x)=>x>0).reduce((a,b)=>a+b,0)/positive*100:0),largestWinner:round(sorted.at(-1)??0),largestLoser:round(sorted[0]??0)}; }
function settledRecords(candidate: Candidate) { const m=candidate.metric; return candidate.report.trades.flatMap((trade)=>{const exit=trade.resolution.exits.get(policyKey(m.target,m.stop,m.hold));return exit&&!exit.ambiguous&&!exit.unavailable&&exit.premiumChangePercent!==null?[{trade,exit}]:[];}); }
function overlapFor(candidate:Candidate,v2:readonly V5Signal[],v4:readonly V4Signal[],sessions:readonly CrossSessionPreparedSession[]){const times=candidate.report.trades.map((trade)=>trade.signal.timestamp.getTime());const count=(other:readonly {timestamp:Date}[],minutes:number)=>times.filter((time)=>other.some((value)=>Math.abs(value.timestamp.getTime()-time)<=minutes*60_000)).length;const exactV2=count(v2,0),exactV4=count(v4,0);return {V2:{exact:exactV2,plusMinus2Minutes:count(v2,2),plusMinus5Minutes:count(v2,5)},V4:{exact:exactV4,plusMinus2Minutes:count(v4,2),plusMinus5Minutes:count(v4,5)},incrementalTradesPerSessionAfterExactDuplicates:round((candidate.metric.resolvedTrades-new Set(times.filter((time)=>v2.some((x)=>x.timestamp.getTime()===time)||v4.some((x)=>x.timestamp.getTime()===time))).size)/sessions.length)};}
function frequencyTiers(candidates:readonly Candidate[],sessions:readonly CrossSessionPreparedSession[]){return [3,5,8,10].map((threshold)=>{const matching=candidates.filter((candidate)=>candidate.metric.resolvedTrades/sessions.length>=threshold);const positive=matching.filter((candidate)=>candidate.metric.net40>0);const credible=matching.filter(isCredible);const highest=[...matching].sort((a,b)=>b.metric.resolvedTrades-a.metric.resolvedTrades||rank(a,b))[0];const best=[...positive].sort(rank)[0];return {minimumTradesPerSession:threshold,candidateCount:matching.length,positiveNetAt040Count:positive.length,credibleCount:credible.length,highestFrequency:highest?serializeCandidate(highest,sessions):null,bestPositiveNetAt040:best?serializeCandidate(best,sessions):null};});}
function combinedRobustness(records:ReadonlyArray<{trade:Trade;exit:OptionExitPolicyEvaluationResult}>,sessions:readonly CrossSessionPreparedSession[]){const dates=new Map<string,number[]>();records.forEach((x)=>dates.set(x.trade.signal.date,[...(dates.get(x.trade.signal.date)??[]),x.exit.premiumChangePercent!]));const summarise=(subset:ReadonlyArray<{trade:Trade;exit:OptionExitPolicyEvaluationResult}>)=>{const values=subset.map((x)=>x.exit.premiumChangePercent!);return {trades:values.length,grossAverage:round(average(values)),netAverageAt040:round(average(values)-.4),median:round(median(values))};};const mid=Math.floor(sessions.length/2),h1=new Set(sessions.slice(0,mid).map((x)=>x.date));return {monthly:[['March','2026-03'],['April','2026-04'],['May','2026-05'],['June','2026-06'],['July','2026-07'],['Aug 1-4','2026-08']].map(([month,prefix])=>({month,...summarise(records.filter((x)=>x.trade.signal.date.startsWith(prefix)))})),halves:[{period:'First half',...summarise(records.filter((x)=>h1.has(x.trade.signal.date)))},{period:'Second half',...summarise(records.filter((x)=>!h1.has(x.trade.signal.date)))}],dailyConsistency:{activeDays:dates.size,profitableDays:[...dates.values()].filter((x)=>x.reduce((a,b)=>a+b,0)>0).length}};}
function frozenV2Signals(sessions:readonly CrossSessionPreparedSession[]):V5Signal[]{const output:V5Signal[]=[];sessions.forEach((session)=>{let last:number|undefined;session.frames[5].candles.forEach((candle)=>{const timestamp=candle.timestamp.getTime()+300000,point=[...session.regimePoints].reverse().find((x)=>x.availableAt.getTime()<=timestamp),ema=session.frames[5].ema35.get(candle.timestamp.getTime()),rsi=session.frames[5].rsi14.get(candle.timestamp.getTime());if(point?.regime!==AdaptivePrimaryMarketRegime.TREND_DOWN||ema===undefined||rsi===undefined||!matchesTrendDirectionalEma35Pullback({direction:'DOWN',close:candle.close,high:candle.high,low:candle.low,ema35:ema,rsi,proximity:.2,rsiFilter:'RSI_LT_35'})||(last!==undefined&&timestamp-last<600000))return;output.push({configKey:'FROZEN_V2',date:session.date,timestamp:new Date(timestamp),spotPrice:candle.close,direction:'PE',regimeAvailableAt:point.availableAt,entryCandleStartedAt:candle.timestamp});last=timestamp;});});return output;}
function frozenV4Signals(sessions:readonly CrossSessionPreparedSession[],engine:IndicatorEngineService):V4Signal[]{const config=createV4Configs().MOMENTUM_EXPANSION.find((x)=>x.timeframe===3&&x.direction==='PE'&&x.compressionBars===3&&x.compressionRangeAtr===2&&x.bodyAtr===1&&x.breakoutAtr===.1&&!x.requireVwapAlignment&&x.requirePrimaryRegimeAlignment&&x.cooldownMinutes===5);if(!config)return[];const atr=new Map(sessions.flatMap((s)=>{const result=engine.calculate(s.frames[3].allCandles,{indicators:[{type:IndicatorType.ATR,period:14}]});const found=result.indicators.find((x)=>x.config.type===IndicatorType.ATR&&'period'in x.config&&x.config.period===14);return found?.result.values.flatMap((x)=>'value'in x&&typeof x.value==='number'?[[x.timestamp.getTime(),x.value] as [number,number]]:[])??[]}));const empty=new Map<number,number>();const context:V4IndicatorContext={atr14ByFrame:new Map([[1,empty],[2,empty],[3,atr],[5,empty]]),vwapByFrame:new Map([[1,empty],[2,empty],[3,empty],[5,empty]])};return generateV4Signals(sessions,config,context);}
function completeSession(candles:readonly {timestamp:Date}[]){if(candles.length!==375)return false;const ordered=[...candles].sort((a,b)=>a.timestamp.getTime()-b.timestamp.getTime());const minute=(d:Date)=>{const p=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(d).map((x)=>[x.type,x.value]));return Number(p.hour)*60+Number(p.minute);};return minute(ordered[0].timestamp)===555&&minute(ordered[374].timestamp)===929&&ordered.every((x,i)=>i===0||x.timestamp.getTime()-ordered[i-1].timestamp.getTime()===60000);}
function signalKey(signal:V5Signal){return `${signal.direction}\u0000${signal.timestamp.getTime()}`;}function policyKey(t:number,s:number,h:number){return `${t}|${s}|${h}`;}function cached<T>(map:Map<string,Promise<T>>,key:string,fn:()=>Promise<T>){const found=map.get(key);if(found)return found;const pending=fn();map.set(key,pending);return pending;}async function mapConcurrent<T,R>(items:readonly T[],limit:number,fn:(item:T)=>Promise<R>){const result=new Array<R>(items.length);let next=0;await Promise.all(Array.from({length:Math.min(limit,items.length)},async()=>{while(true){const index=next++;if(index>=items.length)return;result[index]=await fn(items[index]);}}));return result;}function average(values:readonly number[]){return values.length?values.reduce((a,b)=>a+b,0)/values.length:0;}function median(values:readonly number[]){if(!values.length)return 0;const s=[...values].sort((a,b)=>a-b),i=Math.floor(s.length/2);return s.length%2?s[i]:(s[i-1]+s[i])/2;}function rate(value:number,total:number){return total?value/total*100:0;}function round(value:number){return Number(value.toFixed(2));}function streak(values:readonly boolean[]){let current=0,best=0;values.forEach((value)=>{current=value?current+1:0;best=Math.max(best,current);});return best;}function unique<T>(values:readonly T[]){return [...new Set(values)];}function write(name:string,value:unknown){writeFileSync(resolve(artifactsDirectory,name),`${JSON.stringify(value,null,2)}\n`,'utf8');}function rankingArtifact(result:ReturnType<typeof analyzeDirection>,sessions:readonly CrossSessionPreparedSession[]){return {...summary(result,sessions),top20:result.ranked.map((candidate)=>serializeCandidate(candidate,sessions))};}function summary(result:ReturnType<typeof analyzeDirection>,sessions:readonly CrossSessionPreparedSession[]){return {direction:result.direction,policyCandidates:result.policyCandidates,credibleAfter040Cost:result.credibleAfter040Cost,highestFrequency:result.highestFrequency?serializeCandidate(result.highestFrequency,sessions):null,highestQuality:result.highestQuality?serializeCandidate(result.highestQuality,sessions):null,bestBalanced:result.bestBalanced?serializeCandidate(result.bestBalanced,sessions):null,overlap:result.overlap};}function verdict(ce:Candidate|undefined,pe:Candidate|undefined){const candidates=[ce,pe].filter((x):x is Candidate=>!!x&&isCredible(x));if(!candidates.length)return 'REJECT';return candidates.some((x)=>x.metric.resolvedTrades>=104&&x.metric.net40>.4)?'PROMISING':'WEAK';}

run().catch((error)=>{console.error('V5 NIFTY scalping outcome research failed.',error);process.exitCode=1;});
