import logger from '../core/logger/logger';
import HistoricalCandleRepository from '../modules/historical-candles/repositories/historical-candle.repository';
import { AdxValue } from '../modules/indicators/indicators/adx.indicator';
import CandleTimeframeAggregatorService from '../modules/indicators/services/candle-timeframe-aggregator.service';
import IndicatorEngineService, { IndicatorEngineResult } from '../modules/indicators/services/indicator-engine.service';
import { Candle, IndicatorType } from '../modules/indicators/types';
import AdaptiveMarketRegimeService from '../modules/adaptive-intraday/services/adaptive-market-regime.service';
import { AdaptivePrimaryMarketRegime } from '../modules/adaptive-intraday/types/adaptive-market-regime.types';

const instrumentKey = 'NSE_INDEX|Nifty 50';
const sourceTimeframe = '1minute';
const expectedOneMinuteCandlesPerSession = 375;
const marketSessionStartMinute = 9 * 60 + 15;
const marketSessionEndMinute = 15 * 60 + 29;
const anchors = [10, 15, 20] as const;
const deviations = [0.05, 0.10, 0.15, 0.20, 0.25, 0.30] as const;
const cooldowns = [0, 5, 10, 15] as const;
const horizons = [5, 10, 15, 30] as const;
const meanReachHorizons = [10, 15, 30, 60] as const;
const qualityMinimumSampleSize = 30;
const marketTimeFormatter = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Kolkata', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hourCycle: 'h23' });

type Anchor = (typeof anchors)[number];
type Direction = 'CE' | 'PE';
type Horizon = (typeof horizons)[number];
type MeanReachHorizon = (typeof meanReachHorizons)[number];
type RsiFilter = 'NO_RSI_FILTER' | 'RSI_40_60' | 'RSI_35_65' | 'RSI_30_70';

interface StoredCandle { candleTime: Date; open: { toString(): string }; high: { toString(): string }; low: { toString(): string }; close: { toString(): string }; volume: bigint; openInterest: bigint | null; }
interface Session { date: string; candles: Candle[]; regimes: Array<AdaptivePrimaryMarketRegime | undefined>; ema: Record<Anchor, Map<number, number>>; rsi14: Map<number, number>; }
interface Config { anchor: Anchor; deviation: number; rsiFilter: RsiFilter; cooldown: number; }
interface Opportunity { date: string; timestamp: Date; direction: Direction; close: number; anchor: number; movements: Partial<Record<Horizon, number>>; meanReach: Partial<Record<MeanReachHorizon, number | null>>; mfe?: number; mae?: number; }
interface HorizonMetric { positive: number; negative: number; neutral: number; accuracy: number; average: number; median: number; }
interface ReachMetric { reached: number; evaluated: number; rate: number; averageMinutes: number; medianMinutes: number; }
interface TimeMetric { total: number; ce: number; pe: number; accuracy15: number; average15: number; mean30Rate: number; }
interface Report { config: Config; opportunities: Opportunity[]; perSession: number[]; horizons: Record<Horizon, HorizonMetric>; meanReach: Record<MeanReachHorizon, ReachMetric>; avgMfe: number; medianMfe: number; avgMae: number; medianMae: number; time: Record<string, TimeMetric>; }

const rsiFilters: readonly RsiFilter[] = ['NO_RSI_FILTER', 'RSI_40_60', 'RSI_35_65', 'RSI_30_70'];

function marketDateAndMinute(timestamp: Date): { date: string; minute: number } { const parts = Object.fromEntries(marketTimeFormatter.formatToParts(timestamp).map((part) => [part.type, part.value])); return { date: `${parts.year}-${parts.month}-${parts.day}`, minute: Number(parts.hour) * 60 + Number(parts.minute) }; }
function isCompleteSession(candles: StoredCandle[]): boolean { if (candles.length !== expectedOneMinuteCandlesPerSession) return false; const ordered = [...candles].sort((a, b) => a.candleTime.getTime() - b.candleTime.getTime()); const first = marketDateAndMinute(ordered[0].candleTime); const last = marketDateAndMinute(ordered[ordered.length - 1].candleTime); return first.minute === marketSessionStartMinute && last.minute === marketSessionEndMinute && ordered.every((candle, index) => index === 0 || candle.candleTime.getTime() - ordered[index - 1].candleTime.getTime() === 60_000); }
function toCandle(candle: StoredCandle): Candle { const volume = Number(candle.volume); const openInterest = candle.openInterest === null ? undefined : Number(candle.openInterest); if (!Number.isSafeInteger(volume) || (openInterest !== undefined && !Number.isSafeInteger(openInterest))) throw new Error('Stored volume or open interest exceeds JavaScript safe-integer precision.'); return { timestamp: new Date(candle.candleTime.getTime()), open: Number(candle.open), high: Number(candle.high), low: Number(candle.low), close: Number(candle.close), volume, openInterest }; }
function average(values: readonly number[]): number { return values.length === 0 ? 0 : values.reduce((sum, value) => sum + value, 0) / values.length; }
function median(values: readonly number[]): number { if (values.length === 0) return 0; const sorted = [...values].sort((a, b) => a - b); const middle = Math.floor(sorted.length / 2); return sorted.length % 2 === 0 ? (sorted[middle - 1] + sorted[middle]) / 2 : sorted[middle]; }
function scalarMap(results: IndicatorEngineResult, type: IndicatorType, period: number): Map<number, number> { const indicator = results.indicators.find((entry) => entry.config.type === type && 'period' in entry.config && entry.config.period === period); if (!indicator) throw new Error(`Missing ${type}${period}.`); const values = new Map<number, number>(); indicator.result.values.forEach((entry) => { if ('value' in entry && typeof entry.value === 'number') values.set(entry.timestamp.getTime(), entry.value); }); return values; }
function adxMap(results: IndicatorEngineResult): Map<number, AdxValue> { const indicator = results.indicators.find((entry) => entry.config.type === IndicatorType.ADX && 'period' in entry.config && entry.config.period === 14); if (!indicator) throw new Error('Missing ADX14.'); const values = new Map<number, AdxValue>(); indicator.result.values.forEach((entry) => { if ('adx' in entry && 'plusDI' in entry && 'minusDI' in entry) values.set(entry.timestamp.getTime(), entry as AdxValue & { timestamp: Date }); }); return values; }

function prepareSessions(rawSessions: Array<[string, StoredCandle[]]>, aggregator: CandleTimeframeAggregatorService, engine: IndicatorEngineService, regimeService: AdaptiveMarketRegimeService): Session[] {
  return rawSessions.map(([date, stored]) => {
    const candles = aggregator.aggregate([...stored].sort((a, b) => a.candleTime.getTime() - b.candleTime.getTime()).map(toCandle), '5m');
    const indicators = engine.calculate(candles, { indicators: [{ type: IndicatorType.EMA, period: 10 }, { type: IndicatorType.EMA, period: 15 }, { type: IndicatorType.EMA, period: 20 }, { type: IndicatorType.EMA, period: 35 }, { type: IndicatorType.RSI, period: 14 }, { type: IndicatorType.ADX, period: 14 }, { type: IndicatorType.ATR, period: 14 }] });
    const ema = { 10: scalarMap(indicators, IndicatorType.EMA, 10), 15: scalarMap(indicators, IndicatorType.EMA, 15), 20: scalarMap(indicators, IndicatorType.EMA, 20) } as Record<Anchor, Map<number, number>>;
    const ema35 = scalarMap(indicators, IndicatorType.EMA, 35); const rsi14 = scalarMap(indicators, IndicatorType.RSI, 14); const adx14 = adxMap(indicators); const atr14 = scalarMap(indicators, IndicatorType.ATR, 14);
    const regimes = candles.map((candle) => { const key = candle.timestamp.getTime(); const fast = ema[15].get(key); const slow = ema35.get(key); const rsi = rsi14.get(key); const adx = adx14.get(key); const atr = atr14.get(key); return fast === undefined || slow === undefined || rsi === undefined || !adx || atr === undefined ? undefined : regimeService.classify({ timestamp: candle.timestamp, close: candle.close, ema15: fast, ema35: slow, rsi14: rsi, adx14: adx.adx, atr14: atr }).primaryRegime; });
    return { date, candles, regimes, ema, rsi14 };
  });
}

function passesRsiFilter(filter: RsiFilter, direction: Direction, rsi: number): boolean { if (filter === 'NO_RSI_FILTER') return true; const [lower, upper] = filter === 'RSI_40_60' ? [40, 60] : filter === 'RSI_35_65' ? [35, 65] : [30, 70]; return direction === 'CE' ? rsi <= lower : rsi >= upper; }
function evaluateOpportunity(session: Session, index: number, direction: Direction, anchor: number): Opportunity { const signal = session.candles[index]; const movements: Partial<Record<Horizon, number>> = {}; horizons.forEach((horizon) => { const future = session.candles[index + horizon / 5]; if (future) movements[horizon] = direction === 'CE' ? future.close - signal.close : signal.close - future.close; }); const meanReach: Partial<Record<MeanReachHorizon, number | null>> = {}; meanReachHorizons.forEach((horizon) => { const candles = session.candles.slice(index + 1, index + horizon / 5 + 1); if (candles.length !== horizon / 5) { meanReach[horizon] = undefined; return; } const hitIndex = candles.findIndex((candle) => direction === 'CE' ? candle.high >= anchor : candle.low <= anchor); meanReach[horizon] = hitIndex < 0 ? null : (hitIndex + 1) * 5; }); const futureThirty = session.candles.slice(index + 1, index + 7); const hasThirty = futureThirty.length === 6; return { date: session.date, timestamp: new Date(signal.timestamp.getTime()), direction, close: signal.close, anchor, movements, meanReach, mfe: hasThirty ? Math.max(0, direction === 'CE' ? Math.max(...futureThirty.map((candle) => candle.high)) - signal.close : signal.close - Math.min(...futureThirty.map((candle) => candle.low))) : undefined, mae: hasThirty ? Math.max(0, direction === 'CE' ? signal.close - Math.min(...futureThirty.map((candle) => candle.low)) : Math.max(...futureThirty.map((candle) => candle.high)) - signal.close) : undefined }; }

function collect(sessions: readonly Session[], config: Config): Opportunity[] { const opportunities: Opportunity[] = []; sessions.forEach((session) => { let lastCe: number | undefined; let lastPe: number | undefined; session.candles.forEach((candle, index) => { if (session.regimes[index] !== AdaptivePrimaryMarketRegime.SIDEWAYS) return; const timestamp = candle.timestamp.getTime(); const anchor = session.ema[config.anchor].get(timestamp); const rsi = session.rsi14.get(timestamp); if (anchor === undefined || rsi === undefined || anchor <= 0) return; const distance = ((candle.close - anchor) / anchor) * 100; const cooldownMs = config.cooldown * 60_000; if (distance <= -config.deviation && passesRsiFilter(config.rsiFilter, 'CE', rsi) && (lastCe === undefined || timestamp - lastCe >= cooldownMs)) { opportunities.push(evaluateOpportunity(session, index, 'CE', anchor)); lastCe = timestamp; } if (distance >= config.deviation && passesRsiFilter(config.rsiFilter, 'PE', rsi) && (lastPe === undefined || timestamp - lastPe >= cooldownMs)) { opportunities.push(evaluateOpportunity(session, index, 'PE', anchor)); lastPe = timestamp; } }); }); return opportunities.sort((a, b) => a.timestamp.getTime() - b.timestamp.getTime()); }

function horizonMetric(opportunities: readonly Opportunity[], horizon: Horizon): HorizonMetric { const values = opportunities.flatMap((opportunity) => opportunity.movements[horizon] === undefined ? [] : [opportunity.movements[horizon] as number]); return { positive: values.filter((value) => value > 0).length, negative: values.filter((value) => value < 0).length, neutral: values.filter((value) => value === 0).length, accuracy: values.length === 0 ? 0 : (values.filter((value) => value > 0).length / values.length) * 100, average: average(values), median: median(values) }; }
function reachMetric(opportunities: readonly Opportunity[], horizon: MeanReachHorizon): ReachMetric { const values = opportunities.map((opportunity) => opportunity.meanReach[horizon]).filter((value): value is number | null => value !== undefined); const reached = values.filter((value): value is number => value !== null); return { reached: reached.length, evaluated: values.length, rate: values.length === 0 ? 0 : (reached.length / values.length) * 100, averageMinutes: average(reached), medianMinutes: median(reached) }; }
function bucket(timestamp: Date): string { const minute = marketDateAndMinute(timestamp).minute; if (minute < 10 * 60 + 30) return '09:15-10:30'; if (minute < 12 * 60) return '10:30-12:00'; if (minute < 13 * 60 + 30) return '12:00-13:30'; return '13:30-15:30'; }
function createReport(config: Config, sessions: readonly Session[]): Report { const opportunities = collect(sessions, config); const perSession = sessions.map((session) => opportunities.filter((opportunity) => opportunity.date === session.date).length); const horizonsOutput = { 5: horizonMetric(opportunities, 5), 10: horizonMetric(opportunities, 10), 15: horizonMetric(opportunities, 15), 30: horizonMetric(opportunities, 30) }; const reachOutput = { 10: reachMetric(opportunities, 10), 15: reachMetric(opportunities, 15), 30: reachMetric(opportunities, 30), 60: reachMetric(opportunities, 60) }; const buckets = ['09:15-10:30', '10:30-12:00', '12:00-13:30', '13:30-15:30']; const time = Object.fromEntries(buckets.map((name) => [name, { total: 0, ce: 0, pe: 0, accuracy15: 0, average15: 0, mean30Rate: 0 }])) as Record<string, TimeMetric>; buckets.forEach((name) => { const entries = opportunities.filter((opportunity) => bucket(opportunity.timestamp) === name); const movements = entries.flatMap((opportunity) => opportunity.movements[15] === undefined ? [] : [opportunity.movements[15] as number]); const reaches = entries.map((opportunity) => opportunity.meanReach[30]).filter((value): value is number | null => value !== undefined); time[name] = { total: entries.length, ce: entries.filter((entry) => entry.direction === 'CE').length, pe: entries.filter((entry) => entry.direction === 'PE').length, accuracy15: movements.length === 0 ? 0 : (movements.filter((value) => value > 0).length / movements.length) * 100, average15: average(movements), mean30Rate: reaches.length === 0 ? 0 : (reaches.filter((value) => value !== null).length / reaches.length) * 100 }; }); return { config, opportunities, perSession, horizons: horizonsOutput, meanReach: reachOutput, avgMfe: average(opportunities.flatMap((opportunity) => opportunity.mfe === undefined ? [] : [opportunity.mfe])), medianMfe: median(opportunities.flatMap((opportunity) => opportunity.mfe === undefined ? [] : [opportunity.mfe])), avgMae: average(opportunities.flatMap((opportunity) => opportunity.mae === undefined ? [] : [opportunity.mae])), medianMae: median(opportunities.flatMap((opportunity) => opportunity.mae === undefined ? [] : [opportunity.mae])), time }; }
function configName(config: Config): string { return `EMA${config.anchor} dev=${config.deviation.toFixed(2)}% ${config.rsiFilter} cooldown=${config.cooldown}m`; }
function printReport(report: Report): void { const ce = report.opportunities.filter((opportunity) => opportunity.direction === 'CE').length; const pe = report.opportunities.length - ce; console.log(`${configName(report.config)} | total=${report.opportunities.length} CE=${ce} PE=${pe} avg/session=${average(report.perSession).toFixed(2)} median/session=${median(report.perSession).toFixed(2)} max/session=${Math.max(0, ...report.perSession)} zero=${report.perSession.filter((value) => value === 0).length} | 15m=${report.horizons[15].accuracy.toFixed(2)}% avg=${report.horizons[15].average.toFixed(2)} med=${report.horizons[15].median.toFixed(2)} | mean30=${report.meanReach[30].rate.toFixed(2)}% MFE=${report.avgMfe.toFixed(2)} MAE=${report.avgMae.toFixed(2)}`); }
function printDetailed(label: string, report: Report): void { console.log(`\n${label}: ${configName(report.config)}`); horizons.forEach((horizon) => { const metric = report.horizons[horizon]; console.log(`+${horizon}m positive=${metric.positive} negative=${metric.negative} neutral=${metric.neutral} accuracy=${metric.accuracy.toFixed(2)}% avg=${metric.average.toFixed(2)} median=${metric.median.toFixed(2)}`); }); ['CE', 'PE'].forEach((direction) => { const opportunities = report.opportunities.filter((opportunity) => opportunity.direction === direction); const metric = horizonMetric(opportunities, 15); const mean30 = reachMetric(opportunities, 30); console.log(`${direction} at +15m: opportunities=${opportunities.length} accuracy=${metric.accuracy.toFixed(2)}% avg=${metric.average.toFixed(2)} median=${metric.median.toFixed(2)} mean30=${mean30.rate.toFixed(2)}%`); }); meanReachHorizons.forEach((horizon) => { const metric = report.meanReach[horizon]; console.log(`mean reached <=${horizon}m: ${metric.reached}/${metric.evaluated} (${metric.rate.toFixed(2)}%) avg-time=${metric.averageMinutes.toFixed(2)}m median-time=${metric.medianMinutes.toFixed(2)}m`); }); console.log(`MFE avg=${report.avgMfe.toFixed(2)} median=${report.medianMfe.toFixed(2)} | MAE avg=${report.avgMae.toFixed(2)} median=${report.medianMae.toFixed(2)}`); Object.entries(report.time).forEach(([name, metric]) => console.log(`${name}: opportunities=${metric.total} CE=${metric.ce} PE=${metric.pe} 15m=${metric.accuracy15.toFixed(2)}% avg15=${metric.average15.toFixed(2)} mean30=${metric.mean30Rate.toFixed(2)}%`)); }

async function run(): Promise<void> {
  const repository = new HistoricalCandleRepository(); const aggregator = new CandleTimeframeAggregatorService(); const engine = new IndicatorEngineService(); const regimeService = new AdaptiveMarketRegimeService({ trendStrengthThreshold: 20, emaProximityPercent: 0.05, highVolatilityThreshold: 0.10, lowVolatilityThreshold: 0.05 });
  logger.info('Starting sideways mean-reversion opportunity research', { instrumentKey, sourceTimeframe });
  const stored = await repository.findByInstrumentAndTimeframe(instrumentKey, sourceTimeframe) as StoredCandle[]; const grouped = new Map<string, StoredCandle[]>(); stored.forEach((candle) => { const date = marketDateAndMinute(candle.candleTime).date; const values = grouped.get(date) ?? []; values.push(candle); grouped.set(date, values); }); const complete = Array.from(grouped.entries()).filter(([, candles]) => isCompleteSession(candles)).sort(([a], [b]) => a.localeCompare(b)); if (complete.length === 0) throw new Error('No complete NIFTY sessions are stored.');
  const sessions = prepareSessions(complete, aggregator, engine, regimeService); const reports = anchors.flatMap((anchor) => deviations.flatMap((deviation) => rsiFilters.flatMap((rsiFilter) => cooldowns.map((cooldown) => createReport({ anchor, deviation, rsiFilter, cooldown }, sessions)))));
  console.log(`Instrument=${instrumentKey} complete sessions=${sessions.length} configurations=${reports.length}`); console.log('Frozen regime: ADX>=20, EMA proximity<=0.05%, ATR high=0.10%, ATR low=0.05%.'); console.log('\nAll configuration summaries'); reports.forEach(printReport);
  const frequency = [...reports].sort((a, b) => average(b.perSession) - average(a.perSession) || b.opportunities.length - a.opportunities.length); const quality = reports.filter((report) => report.opportunities.length >= qualityMinimumSampleSize).sort((a, b) => b.horizons[15].accuracy - a.horizons[15].accuracy || b.horizons[15].average - a.horizons[15].average || b.meanReach[30].rate - a.meanReach[30].rate || b.avgMfe - a.avgMfe || a.avgMae - b.avgMae); const balanced = reports.filter((report) => average(report.perSession) >= 3 && report.opportunities.length >= qualityMinimumSampleSize).sort((a, b) => b.horizons[15].accuracy - a.horizons[15].accuracy || b.horizons[15].average - a.horizons[15].average || b.meanReach[30].rate - a.meanReach[30].rate || b.avgMfe - a.avgMfe || a.avgMae - b.avgMae);
  console.log('\nFREQUENCY ranking'); frequency.slice(0, 10).forEach((report, index) => console.log(`${index + 1}. ${configName(report.config)} | avg/session=${average(report.perSession).toFixed(2)} | 15m=${report.horizons[15].accuracy.toFixed(2)}% avg=${report.horizons[15].average.toFixed(2)} | mean30=${report.meanReach[30].rate.toFixed(2)}%`)); console.log(`\nQUALITY ranking (minimum ${qualityMinimumSampleSize} opportunities)`); quality.slice(0, 10).forEach((report, index) => console.log(`${index + 1}. ${configName(report.config)} | total=${report.opportunities.length} avg/session=${average(report.perSession).toFixed(2)} | 15m=${report.horizons[15].accuracy.toFixed(2)}% avg=${report.horizons[15].average.toFixed(2)} | mean30=${report.meanReach[30].rate.toFixed(2)}% MFE=${report.avgMfe.toFixed(2)} MAE=${report.avgMae.toFixed(2)}`)); console.log('\nBALANCED ranking (>=3 opportunities/session)'); balanced.slice(0, 10).forEach((report, index) => console.log(`${index + 1}. ${configName(report.config)} | avg/session=${average(report.perSession).toFixed(2)} | 15m=${report.horizons[15].accuracy.toFixed(2)}% avg=${report.horizons[15].average.toFixed(2)} | mean30=${report.meanReach[30].rate.toFixed(2)}% MFE=${report.avgMfe.toFixed(2)} MAE=${report.avgMae.toFixed(2)}`));
  [5, 10, 15].forEach((minimum) => { const matches = frequency.filter((report) => average(report.perSession) >= minimum); console.log(`\nConfigurations >=${minimum} opportunities/session: ${matches.length}`); matches.slice(0, 20).forEach((report) => console.log(`${configName(report.config)} | avg/session=${average(report.perSession).toFixed(2)} 15m=${report.horizons[15].accuracy.toFixed(2)}% avg=${report.horizons[15].average.toFixed(2)} mean30=${report.meanReach[30].rate.toFixed(2)}%`)); });
  if (frequency[0]) printDetailed('Highest frequency', frequency[0]); if (quality[0]) printDetailed('Highest quality', quality[0]); if (balanced[0]) printDetailed('Best balanced', balanced[0]);
  logger.info('Sideways mean-reversion opportunity research completed', { completeSessions: sessions.length, configurations: reports.length });
}

run().catch((error) => { logger.error('Sideways mean-reversion opportunity research failed', { error }); console.error('Sideways mean-reversion opportunity research failed.', error); process.exitCode = 1; });
