import dotenv from 'dotenv';
import logger from '../core/logger/logger';
import HistoricalCandleRepository from '../modules/historical-candles/repositories/historical-candle.repository';
import { AdxValue } from '../modules/indicators/indicators/adx.indicator';
import CandleTimeframeAggregatorService from '../modules/indicators/services/candle-timeframe-aggregator.service';
import IndicatorEngineService, { IndicatorEngineResult } from '../modules/indicators/services/indicator-engine.service';
import { Candle, IndicatorType } from '../modules/indicators/types';
import UpstoxExpiredOptionCandleClient from '../modules/options/client/upstox-expired-option-candle.client';
import UpstoxExpiredOptionClient from '../modules/options/client/upstox-expired-option.client';
import HistoricalOptionCandleRepository from '../modules/options/repositories/historical-option-candle.repository';
import HistoricalOptionCandleCacheService from '../modules/options/services/historical-option-candle-cache.service';
import HistoricalOptionResearchPreloaderService from '../modules/options/services/historical-option-research-preloader.service';
import { OptionExitPolicyEvaluationResult } from '../modules/options/dto/option-exit-policy.dto';
import OptionContractSelectorService from '../modules/options/services/option-contract-selector.service';
import OptionPremiumPathAnalysisService from '../modules/options/services/option-premium-path-analysis.service';
import { OptionContract } from '../modules/options/types';
import AdaptiveMarketRegimeService from '../modules/adaptive-intraday/services/adaptive-market-regime.service';
import { AdaptivePrimaryMarketRegime } from '../modules/adaptive-intraday/types/adaptive-market-regime.types';
import { StrategySignal } from '../modules/strategies/dto/strategy-signal.dto';
import { CrossSessionPreparedSession, isCooldownEligible, prepareCrossSessionIndicatorWarmup } from './helpers/cross-session-indicator-warmup';
import { PreparedOptionSignalResolution, prepareOptionSignalResolution } from './helpers/prepared-option-signal-resolution';

dotenv.config();
logger.silent = true;

const instrumentKey = 'NSE_INDEX|Nifty 50';
const expectedOneMinuteCandlesPerSession = 375;
const marketSessionStartMinute = 9 * 60 + 15;
const marketSessionEndMinute = 15 * 60 + 29;
const entryTimeframes = [1, 2, 3, 5] as const;
const proximities = [0.05, 0.10, 0.15, 0.20, 0.25] as const;
const cooldowns = [0, 2, 3, 5, 10] as const;
const outcomeHorizons = [1, 2, 3, 4, 5, 10, 15] as const;
const excursionHorizons = [3, 5, 10, 15] as const;
const upsideTargets = [3, 5, 7.5, 10, 15, 20] as const;
const downsideStops = [3, 5, 7.5, 10, 15, 20] as const;
const targetStopPairs = [[5, 5], [7.5, 5], [10, 5], [10, 7.5], [15, 7.5], [15, 10], [20, 10]] as const;
const maximumHolds = [3, 5, 10, 15] as const;
const qualityMinimumSampleSize = 30;
const resolutionConcurrency = 12;
const marketTimeFormatter = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Kolkata', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hourCycle: 'h23' });

type EntryTimeframe = (typeof entryTimeframes)[number];
type Proximity = (typeof proximities)[number];
type OutcomeHorizon = (typeof outcomeHorizons)[number];
type ExcursionHorizon = (typeof excursionHorizons)[number];
type RsiFilter = 'NO_RSI_FILTER' | 'RSI_LT_50' | 'RSI_LT_45' | 'RSI_LT_40' | 'RSI_LT_35';
type TimeBucket = '09:15-10:30' | '10:30-12:00' | '12:00-13:30' | '13:30-15:30';

interface StoredCandle { candleTime: Date; open: { toString(): string }; high: { toString(): string }; low: { toString(): string }; close: { toString(): string }; volume: bigint; openInterest: bigint | null; }
interface EntryFrame { minutes: EntryTimeframe; candles: Candle[]; ema15: Map<number, number>; ema35: Map<number, number>; rsi14: Map<number, number>; }
interface RegimePoint { availableAt: Date; regime: AdaptivePrimaryMarketRegime | undefined; }
type Session = CrossSessionPreparedSession;
interface EntryConfig { timeframe: EntryTimeframe; proximity: Proximity; rsiFilter: RsiFilter; cooldown: number; }
interface Signal { configKey: string; config: EntryConfig; date: string; timestamp: Date; spotPrice: number; regimeAvailableAt: Date; }
interface Resolution { entryPremium: number; changes: Map<OutcomeHorizon, number | null>; excursions: Map<ExcursionHorizon, { mfe: number | null; mae: number | null }>; reaches: Map<number, number | null>; stops: Map<number, number | null>; exits: Map<string, OptionExitPolicyEvaluationResult>; }
interface FailedResolution { error: string; }
interface PercentMetric { count: number; positive: number; negative: number; neutral: number; positivePercent: number; average: number; median: number; }
interface ConfigurationReport { config: EntryConfig; signals: Signal[]; resolved: Array<{ signal: Signal; resolution: Resolution }>; failed: Signal[]; outcomes: Record<OutcomeHorizon, PercentMetric>; excursions: Record<ExcursionHorizon, { mfe: PercentMetric; mae: PercentMetric }>; bestPolicy: PolicyMetric; }
interface PolicyMetric { key: string; target: number; stop: number; hold: number; total: number; targetCount: number; stopCount: number; timeCount: number; ambiguous: number; unavailable: number; targetPercent: number; stopPercent: number; averageReturn: number; medianReturn: number; }
interface ResearchProfile { expiryResolutionMs: number; optionContractResolutionMs: number; requiredSessionKeyConstructionMs: number; uniqueSignalResolutionConstructionMs: number; optionOutcomeEvaluationMs: number; inMemoryOptionSessionLookupMs: number; optionContractSelectionMs: number; premiumHorizonCalculationMs: number; mfeMaeCalculationMs: number; thresholdReachCalculationMs: number; targetStopPathPreparationMs: number; researchPathAnalyticsMs: number; policyOutcomeDerivationMs: number; configurationMetricCalculationMs: number; timeframeRankingConstructionMs: number; fastTradeRankingConstructionMs: number; targetReachSummaryConstructionMs: number; timeOfDaySummaryConstructionMs: number; finalFormattingStringConstructionMs: number; consoleOutputDurationMs: number; analyses: number; policies: number; }

const rsiFilters: readonly RsiFilter[] = ['NO_RSI_FILTER', 'RSI_LT_50', 'RSI_LT_45', 'RSI_LT_40', 'RSI_LT_35'];
const timeBuckets: readonly TimeBucket[] = ['09:15-10:30', '10:30-12:00', '12:00-13:30', '13:30-15:30'];
const quiet = process.env.RESEARCH_QUIET === 'true';
let activeProfile: ResearchProfile | undefined;

function report(...values: unknown[]): void { const started = Date.now(); console.log(...values); if (activeProfile) activeProfile.consoleOutputDurationMs += Date.now() - started; }
function measure<T>(profile: ResearchProfile, key: keyof ResearchProfile, work: () => T): T { const started = Date.now(); try { return work(); } finally { profile[key] = (profile[key] as number) + Date.now() - started; } }

function marketDateAndMinute(timestamp: Date): { date: string; minute: number } { const values = Object.fromEntries(marketTimeFormatter.formatToParts(timestamp).map((part) => [part.type, part.value])); return { date: `${values.year}-${values.month}-${values.day}`, minute: Number(values.hour) * 60 + Number(values.minute) }; }
function isCompleteSession(candles: StoredCandle[]): boolean { if (candles.length !== expectedOneMinuteCandlesPerSession) return false; const sorted = [...candles].sort((left, right) => left.candleTime.getTime() - right.candleTime.getTime()); const first = marketDateAndMinute(sorted[0].candleTime); const last = marketDateAndMinute(sorted[sorted.length - 1].candleTime); return first.minute === marketSessionStartMinute && last.minute === marketSessionEndMinute && sorted.every((candle, index) => index === 0 || candle.candleTime.getTime() - sorted[index - 1].candleTime.getTime() === 60_000); }
function isCompleteInternalSession(candles: readonly Candle[]): boolean { if (candles.length !== expectedOneMinuteCandlesPerSession) return false; const sorted = [...candles].sort((left, right) => left.timestamp.getTime() - right.timestamp.getTime()); const first = marketDateAndMinute(sorted[0].timestamp); const last = marketDateAndMinute(sorted[sorted.length - 1].timestamp); return first.minute === marketSessionStartMinute && last.minute === marketSessionEndMinute && sorted.every((candle, index) => index === 0 || candle.timestamp.getTime() - sorted[index - 1].timestamp.getTime() === 60_000); }
function toCandle(candle: StoredCandle): Candle { const volume = Number(candle.volume); const openInterest = candle.openInterest === null ? undefined : Number(candle.openInterest); if (!Number.isSafeInteger(volume) || (openInterest !== undefined && !Number.isSafeInteger(openInterest))) throw new Error('Stored volume or open interest exceeds JavaScript safe-integer precision.'); return { timestamp: new Date(candle.candleTime.getTime()), open: Number(candle.open), high: Number(candle.high), low: Number(candle.low), close: Number(candle.close), volume, openInterest }; }
function average(values: readonly number[]): number { return values.length === 0 ? 0 : values.reduce((total, value) => total + value, 0) / values.length; }
function median(values: readonly number[]): number { if (values.length === 0) return 0; const sorted = [...values].sort((left, right) => left - right); const middle = Math.floor(sorted.length / 2); return sorted.length % 2 === 0 ? (sorted[middle - 1] + sorted[middle]) / 2 : sorted[middle]; }
function scalarMap(results: IndicatorEngineResult, type: IndicatorType, period: number): Map<number, number> { const indicator = results.indicators.find((entry) => entry.config.type === type && 'period' in entry.config && entry.config.period === period); if (!indicator) throw new Error(`Missing ${type}${period}.`); const values = new Map<number, number>(); indicator.result.values.forEach((entry) => { if ('value' in entry && typeof entry.value === 'number') values.set(entry.timestamp.getTime(), entry.value); }); return values; }
function adxMap(results: IndicatorEngineResult): Map<number, AdxValue> { const indicator = results.indicators.find((entry) => entry.config.type === IndicatorType.ADX && 'period' in entry.config && entry.config.period === 14); if (!indicator) throw new Error('Missing ADX14.'); const values = new Map<number, AdxValue>(); indicator.result.values.forEach((entry) => { if ('adx' in entry && 'plusDI' in entry && 'minusDI' in entry) values.set(entry.timestamp.getTime(), entry as AdxValue & { timestamp: Date }); }); return values; }

function aggregateSessionAnchored(oneMinute: readonly Candle[], minutes: EntryTimeframe): Candle[] { if (minutes === 1) return [...oneMinute]; const result: Candle[] = []; for (let index = 0; index + minutes <= oneMinute.length; index += minutes) { const slice = oneMinute.slice(index, index + minutes); if (slice.length !== minutes) continue; result.push({ timestamp: new Date(slice[0].timestamp.getTime()), open: slice[0].open, high: Math.max(...slice.map((candle) => candle.high)), low: Math.min(...slice.map((candle) => candle.low)), close: slice[slice.length - 1].close, volume: slice.reduce((total, candle) => total + candle.volume, 0), openInterest: slice[slice.length - 1].openInterest }); } return result; }
function createEntryFrame(candles: Candle[], minutes: EntryTimeframe, engine: IndicatorEngineService): EntryFrame { const results = engine.calculate(candles, { indicators: [{ type: IndicatorType.EMA, period: 15 }, { type: IndicatorType.EMA, period: 35 }, { type: IndicatorType.RSI, period: 14 }] }); return { minutes, candles, ema15: scalarMap(results, IndicatorType.EMA, 15), ema35: scalarMap(results, IndicatorType.EMA, 35), rsi14: scalarMap(results, IndicatorType.RSI, 14) }; }
function configKey(config: EntryConfig): string { return `${config.timeframe}m|${config.proximity}|${config.rsiFilter}|${config.cooldown}`; }
function rsiThreshold(filter: RsiFilter): number | undefined { return filter === 'NO_RSI_FILTER' ? undefined : Number(filter.replace('RSI_LT_', '')); }
function latestKnownRegime(session: Session, timestamp: Date): RegimePoint | undefined { for (let index = session.regimePoints.length - 1; index >= 0; index -= 1) { const point = session.regimePoints[index]; if (point.availableAt.getTime() <= timestamp.getTime()) return point; } return undefined; }
function assertNoLookAhead(signal: Signal): void { if (signal.regimeAvailableAt.getTime() > signal.timestamp.getTime()) throw new Error(`Look-ahead detected for ${signal.timestamp.toISOString()}: regime became available after entry.`); }
function assertNoLookAheadAtSessionBoundaries(sessions: readonly Session[]): void { sessions.forEach((session) => { const start = session.oneMinute[0]?.timestamp; if (!start) throw new Error(`Session ${session.date} has no candles.`); [0, 2, 5].forEach((offsetMinutes) => { const timestamp = new Date(start.getTime() + offsetMinutes * 60_000); const regime = latestKnownRegime(session, timestamp); if (regime && regime.availableAt.getTime() > timestamp.getTime()) throw new Error(`Boundary look-ahead detected at ${timestamp.toISOString()}.`); }); }); }
function generateSignalsForConfig(sessions: readonly Session[], config: EntryConfig): Signal[] { const signals: Signal[] = []; sessions.forEach((session) => { const frame = session.frames[config.timeframe]; let lastTimestamp: number | undefined; frame.candles.forEach((candle) => { const entryTimestamp = new Date(candle.timestamp.getTime() + config.timeframe * 60_000); const regime = latestKnownRegime(session, entryTimestamp); if (regime?.regime !== AdaptivePrimaryMarketRegime.TREND_DOWN) return; const key = candle.timestamp.getTime(); const ema35 = frame.ema35.get(key); const rsi = frame.rsi14.get(key); if (ema35 === undefined || rsi === undefined) return; const threshold = rsiThreshold(config.rsiFilter); const highDistance = Math.abs(candle.high - ema35) / ema35 * 100; if (candle.close >= ema35 || highDistance > config.proximity || (threshold !== undefined && rsi >= threshold)) return; const timestamp = entryTimestamp.getTime(); if (!isCooldownEligible(lastTimestamp, timestamp, config.cooldown)) return; const signal: Signal = { configKey: configKey(config), config, date: session.date, timestamp: entryTimestamp, spotPrice: candle.close, regimeAvailableAt: regime.availableAt }; assertNoLookAhead(signal); signals.push(signal); lastTimestamp = timestamp; }); }); return signals; }

function getOrCreate<T>(cache: Map<string, Promise<T>>, key: string, create: () => Promise<T>, profile?: ResearchProfile, timer?: 'expiryResolutionMs' | 'optionContractResolutionMs'): Promise<T> { const existing = cache.get(key); if (existing) return existing; const started = Date.now(); const pending = create().finally(() => { if (profile && timer) profile[timer] += Date.now() - started; }); cache.set(key, pending); return pending; }
function chooseExpiry(expiries: readonly string[], date: string): string { const expiry = expiries.filter((candidate) => candidate >= date).sort((left, right) => left.localeCompare(right))[0]; if (!expiry) throw new Error(`No expired expiry exists on or after ${date}.`); return expiry; }
async function mapConcurrent<T, R>(items: readonly T[], concurrency: number, mapper: (item: T) => Promise<R>): Promise<R[]> { const result = new Array<R>(items.length); let next = 0; const worker = async (): Promise<void> => { while (next < items.length) { const index = next; next += 1; result[index] = await mapper(items[index]); } }; await Promise.all(Array.from({ length: Math.min(concurrency, items.length) }, () => worker())); return result; }
function exitPolicyKey(target: number, stop: number, hold: number): string { return `${target}|${stop}|${hold}`; }
async function resolveSignal(prepared: PreparedOptionSignalResolution<Signal>, preloader: HistoricalOptionResearchPreloaderService, profile: ResearchProfile): Promise<Resolution | FailedResolution> { try {
  const { signal, selectedContract: contract } = prepared;
  const candles = await (async () => { const started = Date.now(); try { return await preloader.getOptionSession({ instrumentKey: prepared.instrumentKey, tradingDate: prepared.tradingDate, metadata: prepared.metadata }); } finally { profile.inMemoryOptionSessionLookupMs += Date.now() - started; } })();
  const path = measure(profile, 'targetStopPathPreparationMs', () => new OptionPremiumPathAnalysisService(signal.timestamp, candles)); profile.analyses += 1;
  const analytics = measure(profile, 'researchPathAnalyticsMs', () => path.researchAnalytics({ changeHorizons: outcomeHorizons, excursionHorizons, upsideTargets, downsideStops })); const changes = analytics.changes as Map<OutcomeHorizon, number | null>; const excursions = analytics.excursions as Map<ExcursionHorizon, { mfe: number | null; mae: number | null }>; const reaches = analytics.reaches as Map<number, number | null>;
  const exits = measure(profile, 'policyOutcomeDerivationMs', () => { const values = new Map<string, OptionExitPolicyEvaluationResult>(); targetStopPairs.forEach(([target, stop]) => maximumHolds.forEach((hold) => values.set(exitPolicyKey(target, stop, hold), path.evaluate({ type: 'TARGET_STOP', targetPercent: target, stopLossPercent: stop, maximumHoldingMinutes: hold })))); return values; }); profile.policies += exits.size;
  return { entryPremium: analytics.entryPremium, changes, excursions, reaches, stops: new Map(), exits };
} catch (error) { return { error: error instanceof Error ? error.message : 'Unknown option resolution failure.' }; } }
async function prepareOptionSession(signal: Signal, optionClient: UpstoxExpiredOptionClient, selector: OptionContractSelectorService, expiryCache: Map<string, Promise<string[]>>, contractsCache: Map<string, Promise<OptionContract[]>>, profile: ResearchProfile): Promise<PreparedOptionSignalResolution<Signal>> {
  const expiries = await getOrCreate(expiryCache, instrumentKey, () => optionClient.fetchAvailableExpiries(instrumentKey), profile, 'expiryResolutionMs'); const expiry = chooseExpiry(expiries, signal.date);
  const contracts = await getOrCreate(contractsCache, `${instrumentKey}|${expiry}`, () => optionClient.fetchExpiredOptionContracts(instrumentKey, expiry), profile, 'optionContractResolutionMs'); const underlying = contracts[0]?.underlying; if (!underlying) throw new Error('Expired option contracts did not include underlying metadata.');
  const contract = measure(profile, 'optionContractSelectionMs', () => { const selection = selector.select({ underlying, spotPrice: signal.spotPrice, signal: StrategySignal.BUY_PE, timestamp: signal.timestamp, contracts }); const selected = contracts.find((value) => value.instrumentKey === selection.instrumentKey); if (!selected) throw new Error('Selected ATM PE contract was not present.'); return selected; });
  return measure(profile, 'requiredSessionKeyConstructionMs', () => prepareOptionSignalResolution(signal, contract, signal.date));
}

function percentMetric(values: readonly number[]): PercentMetric { const positive = values.filter((value) => value > 0).length; const negative = values.filter((value) => value < 0).length; const neutral = values.filter((value) => value === 0).length; return { count: values.length, positive, negative, neutral, positivePercent: values.length === 0 ? 0 : positive / values.length * 100, average: average(values), median: median(values) }; }
function policyMetric(records: readonly { signal: Signal; resolution: Resolution }[], target: number, stop: number, hold: number): PolicyMetric { const exits = records.map((record) => record.resolution.exits.get(exitPolicyKey(target, stop, hold))).filter((value): value is OptionExitPolicyEvaluationResult => value !== undefined); const resolved = exits.filter((exit) => !exit.unavailable && !exit.ambiguous && exit.premiumChangePercent !== null); const returns = resolved.map((exit) => exit.premiumChangePercent as number); const targetCount = exits.filter((exit) => exit.exitReason === 'TARGET').length; const stopCount = exits.filter((exit) => exit.exitReason === 'STOP_LOSS').length; const timeCount = exits.filter((exit) => exit.exitReason === 'TIME_EXIT').length; return { key: exitPolicyKey(target, stop, hold), target, stop, hold, total: exits.length, targetCount, stopCount, timeCount, ambiguous: exits.filter((exit) => exit.ambiguous).length, unavailable: exits.filter((exit) => exit.unavailable).length, targetPercent: resolved.length === 0 ? 0 : targetCount / resolved.length * 100, stopPercent: resolved.length === 0 ? 0 : stopCount / resolved.length * 100, averageReturn: average(returns), medianReturn: median(returns) }; }
function bestPolicy(records: readonly { signal: Signal; resolution: Resolution }[]): PolicyMetric { const metrics = targetStopPairs.flatMap(([target, stop]) => maximumHolds.map((hold) => policyMetric(records, target, stop, hold))); return metrics.sort((left, right) => right.targetPercent - left.targetPercent || left.stopPercent - right.stopPercent || right.averageReturn - left.averageReturn || right.medianReturn - left.medianReturn)[0]; }
function reportForConfig(config: EntryConfig, signals: Signal[], resolutions: Map<number, Resolution | FailedResolution>): ConfigurationReport { const resolved: Array<{ signal: Signal; resolution: Resolution }> = []; const failed: Signal[] = []; signals.forEach((signal) => { const value = resolutions.get(signal.timestamp.getTime()); if (value && !('error' in value)) resolved.push({ signal, resolution: value }); else failed.push(signal); }); const outcomes = Object.fromEntries(outcomeHorizons.map((horizon) => [horizon, percentMetric(resolved.map((record) => record.resolution.changes.get(horizon)).filter((value): value is number => value !== null && value !== undefined))])) as Record<OutcomeHorizon, PercentMetric>; const excursions = Object.fromEntries(excursionHorizons.map((horizon) => [horizon, { mfe: percentMetric(resolved.map((record) => record.resolution.excursions.get(horizon)?.mfe).filter((value): value is number => value !== null && value !== undefined)), mae: percentMetric(resolved.map((record) => record.resolution.excursions.get(horizon)?.mae).filter((value): value is number => value !== null && value !== undefined)) }])) as Record<ExcursionHorizon, { mfe: PercentMetric; mae: PercentMetric }>; return { config, signals, resolved, failed, outcomes, excursions, bestPolicy: bestPolicy(resolved) }; }
function qualityRank(left: ConfigurationReport, right: ConfigurationReport): number { return right.outcomes[3].positivePercent - left.outcomes[3].positivePercent || right.outcomes[5].positivePercent - left.outcomes[5].positivePercent || right.outcomes[5].median - left.outcomes[5].median || right.bestPolicy.targetPercent - left.bestPolicy.targetPercent || left.bestPolicy.stopPercent - right.bestPolicy.stopPercent || right.excursions[5].mfe.average - left.excursions[5].mfe.average || left.excursions[5].mae.average - right.excursions[5].mae.average; }
function formatConfig(config: EntryConfig): string { return `${config.timeframe}m proximity=${config.proximity.toFixed(2)}% ${config.rsiFilter} cooldown=${config.cooldown}m`; }
function printConfiguration(configReport: ConfigurationReport, sessions: readonly Session[]): void { const perSession = sessions.map((session) => configReport.resolved.filter((record) => record.signal.date === session.date).length); report(`${formatConfig(configReport.config)} | raw=${configReport.signals.length} resolved=${configReport.resolved.length} avg/session=${average(perSession).toFixed(2)} median/session=${median(perSession).toFixed(2)} max/session=${Math.max(...perSession)} zero=${perSession.filter((value) => value === 0).length} | +1=${configReport.outcomes[1].positivePercent.toFixed(2)}% +3=${configReport.outcomes[3].positivePercent.toFixed(2)}% +5=${configReport.outcomes[5].positivePercent.toFixed(2)}% avg5=${configReport.outcomes[5].average.toFixed(2)}% median5=${configReport.outcomes[5].median.toFixed(2)}% | MFE5=${configReport.excursions[5].mfe.average.toFixed(2)}% MAE5=${configReport.excursions[5].mae.average.toFixed(2)}% | bestPolicy=+${configReport.bestPolicy.target}/-${configReport.bestPolicy.stop}/${configReport.bestPolicy.hold}m target=${configReport.bestPolicy.targetPercent.toFixed(2)}% stop=${configReport.bestPolicy.stopPercent.toFixed(2)}% return=${configReport.bestPolicy.averageReturn.toFixed(2)}%`); }
function printTimeframeBest(timeframe: EntryTimeframe, reports: readonly ConfigurationReport[], sessionCount: number, profile: ResearchProfile): void { const ranked = measure(profile, 'timeframeRankingConstructionMs', () => { const matching = reports.filter((entry) => entry.config.timeframe === timeframe); return { frequency: [...matching].sort((left, right) => right.resolved.length - left.resolved.length)[0], quality: matching.filter((entry) => entry.resolved.length >= qualityMinimumSampleSize).sort(qualityRank)[0], balanced: matching.filter((entry) => entry.resolved.length / sessionCount >= 2 && entry.resolved.length >= qualityMinimumSampleSize).sort(qualityRank)[0] }; }); report(`\n${timeframe}m TIMEFRAME COMPARISON`); [['Highest frequency', ranked.frequency], ['Highest quality', ranked.quality], ['Best balanced', ranked.balanced]].forEach(([label, value]) => { if (!value) { report(`${label}: NONE`); return; } const entry = value as ConfigurationReport; const line = measure(profile, 'finalFormattingStringConstructionMs', () => `${label}: ${formatConfig(entry.config)} | resolved/session=${(entry.resolved.length / sessionCount).toFixed(2)} | +1=${entry.outcomes[1].positivePercent.toFixed(2)}% +3=${entry.outcomes[3].positivePercent.toFixed(2)}% +5=${entry.outcomes[5].positivePercent.toFixed(2)}% avg5=${entry.outcomes[5].average.toFixed(2)}% median5=${entry.outcomes[5].median.toFixed(2)}% MFE5=${entry.excursions[5].mfe.average.toFixed(2)}% MAE5=${entry.excursions[5].mae.average.toFixed(2)}%`); report(line); }); }
function bucket(timestamp: Date): TimeBucket { const minute = marketDateAndMinute(timestamp).minute; if (minute < 10 * 60 + 30) return '09:15-10:30'; if (minute < 12 * 60) return '10:30-12:00'; if (minute < 13 * 60 + 30) return '12:00-13:30'; return '13:30-15:30'; }
function printReachMetrics(records: readonly { signal: Signal; resolution: Resolution }[], profile: ResearchProfile): void { const lines = measure(profile, 'targetReachSummaryConstructionMs', () => [...upsideTargets.map((target) => { const values = records.map((record) => record.resolution.reaches.get(target)).filter((value): value is number => value !== null && value !== undefined); return `+${target}%: reached=${values.length}/${records.length} rate=${(records.length === 0 ? 0 : values.length / records.length * 100).toFixed(2)}% median=${median(values).toFixed(2)}m avg=${average(values).toFixed(2)}m`; }), ...downsideStops.map((stop) => { const values = records.map((record) => record.resolution.reaches.get(-stop)).filter((value): value is number => value !== null && value !== undefined); return `-${stop}%: reached=${values.length}/${records.length} rate=${(records.length === 0 ? 0 : values.length / records.length * 100).toFixed(2)}% median=${median(values).toFixed(2)}m avg=${average(values).toFixed(2)}m`; })]); report('\nFAST TARGET REACH TIMES'); lines.forEach((line) => report(line)); }

async function run(): Promise<void> {
  const startedAt = Date.now();
  const profile: ResearchProfile = { expiryResolutionMs: 0, optionContractResolutionMs: 0, requiredSessionKeyConstructionMs: 0, uniqueSignalResolutionConstructionMs: 0, optionOutcomeEvaluationMs: 0, inMemoryOptionSessionLookupMs: 0, optionContractSelectionMs: 0, premiumHorizonCalculationMs: 0, mfeMaeCalculationMs: 0, thresholdReachCalculationMs: 0, targetStopPathPreparationMs: 0, researchPathAnalyticsMs: 0, policyOutcomeDerivationMs: 0, configurationMetricCalculationMs: 0, timeframeRankingConstructionMs: 0, fastTradeRankingConstructionMs: 0, targetReachSummaryConstructionMs: 0, timeOfDaySummaryConstructionMs: 0, finalFormattingStringConstructionMs: 0, consoleOutputDurationMs: 0, analyses: 0, policies: 0 }; activeProfile = profile;
  const token = process.env.UPSTOX_ACCESS_TOKEN?.trim(); if (!token) throw new Error('Set UPSTOX_ACCESS_TOKEN in .env before running this integration test.');
  const repository = new HistoricalCandleRepository(); const aggregator = new CandleTimeframeAggregatorService(); const engine = new IndicatorEngineService(); const regimeService = new AdaptiveMarketRegimeService({ trendStrengthThreshold: 20, emaProximityPercent: 0.05, highVolatilityThreshold: 0.10, lowVolatilityThreshold: 0.05 }); const optionClient = new UpstoxExpiredOptionClient(token); const candleClient = new UpstoxExpiredOptionCandleClient(token); const optionCandleRepository = new HistoricalOptionCandleRepository(); const candleCacheService = new HistoricalOptionCandleCacheService(optionCandleRepository, candleClient); const preloader = new HistoricalOptionResearchPreloaderService(repository, optionCandleRepository, candleCacheService); const selector = new OptionContractSelectorService(); const initializationDurationMs = Date.now() - startedAt;
  const underlyingStartedAt = Date.now(); const underlying = await preloader.preloadUnderlying(instrumentKey, '1minute'); const complete = Array.from(underlying.underlyingByDate.entries()).filter(([, candles]) => isCompleteInternalSession(candles)).sort(([left], [right]) => left.localeCompare(right)); if (complete.length === 0) throw new Error('No complete NIFTY sessions are stored.'); const underlyingDurationMs = Date.now() - underlyingStartedAt;
  const requestedLimit = process.env.RESEARCH_SESSION_LIMIT === undefined ? undefined : Number(process.env.RESEARCH_SESSION_LIMIT); if (requestedLimit !== undefined && (!Number.isInteger(requestedLimit) || requestedLimit <= 0)) throw new Error('RESEARCH_SESSION_LIMIT must be a positive integer.'); const preparationStartedAt = Date.now(); const preparedSessions = prepareCrossSessionIndicatorWarmup(complete.map(([date, candles]) => ({ date, candles })), aggregator, engine, regimeService); const sessions = requestedLimit === undefined ? preparedSessions : preparedSessions.slice(0, requestedLimit); assertNoLookAheadAtSessionBoundaries(sessions); const readiness = { at0915: sessions.filter((session) => session.readiness.at0915).length, at0920: sessions.filter((session) => session.readiness.at0920).length, at0930: sessions.filter((session) => session.readiness.at0930).length }; report(`CROSS-SESSION INDICATOR READINESS | 09:15=${(readiness.at0915 / sessions.length * 100).toFixed(2)}% (${readiness.at0915}/${sessions.length}) | 09:20=${(readiness.at0920 / sessions.length * 100).toFixed(2)}% (${readiness.at0920}/${sessions.length}) | 09:30=${(readiness.at0930 / sessions.length * 100).toFixed(2)}% (${readiness.at0930}/${sessions.length})`); const configs = entryTimeframes.flatMap((timeframe) => proximities.flatMap((proximity) => rsiFilters.flatMap((rsiFilter) => cooldowns.map((cooldown) => ({ timeframe, proximity, rsiFilter, cooldown }))))) as EntryConfig[]; const signalsByConfig = new Map<string, Signal[]>(); configs.forEach((config) => signalsByConfig.set(configKey(config), generateSignalsForConfig(sessions, config))); const preparationDurationMs = Date.now() - preparationStartedAt;
  const uniqueSignals = Array.from(new Map(Array.from(signalsByConfig.values()).flat().map((signal) => [signal.timestamp.getTime(), signal])).values()); report(`Instrument=${instrumentKey} sessions=${sessions.length} configurations=${configs.length} unique PE entry timestamps=${uniqueSignals.length}`); timeBuckets.forEach((name) => report(`SIGNALS ${name}: ${uniqueSignals.filter((signal) => bucket(signal.timestamp) === name).length}`)); report('No-look-ahead validation passed: every entry used a fully completed 5m regime candle available at or before the entry timestamp.');
  const optionSessionResolutionStartedAt = Date.now(); const expiryCache = new Map<string, Promise<string[]>>(); const contractsCache = new Map<string, Promise<OptionContract[]>>(); const requiredOptionSessions = await mapConcurrent(uniqueSignals, resolutionConcurrency, (signal) => prepareOptionSession(signal, optionClient, selector, expiryCache, contractsCache, profile)); await preloader.preloadOptionSessions(requiredOptionSessions); const optionSessionResolutionDurationMs = Date.now() - optionSessionResolutionStartedAt;
  if (process.env.RESEARCH_PREPARE_ONLY === 'true') { const stats = preloader.getStats(startedAt); report('RESEARCH DATA PREPARATION', { targetSessions: sessions.length, uniqueSignalTimestamps: uniqueSignals.length, uniqueContracts: new Set(requiredOptionSessions.map((request) => request.instrumentKey)).size, uniqueContractDateSessions: stats.uniqueOptionContractDateSessions, completeLocal: stats.completeLocalSessions, incompleteLocal: stats.incompleteLocalSessions, missingLocal: stats.missingLocalSessions, downloaded: stats.upstoxMissingSessionDownloads, totalOptionCandlesStored: await optionCandleRepository.count(), totalDurationMs: Date.now() - startedAt, researchDataReady: true }); return; }
  const preparedByTimestamp = new Map(requiredOptionSessions.map((prepared) => [prepared.signal.timestamp.getTime(), prepared])); const resolutionStartedAt = Date.now(); const resolvedValues = await mapConcurrent(uniqueSignals, resolutionConcurrency, (signal) => { const prepared = preparedByTimestamp.get(signal.timestamp.getTime()); if (!prepared) throw new Error(`Missing prepared option resolution for ${signal.timestamp.toISOString()}.`); return resolveSignal(prepared, preloader, profile); }); const resolutions = new Map<number, Resolution | FailedResolution>(uniqueSignals.map((signal, index) => [signal.timestamp.getTime(), resolvedValues[index]])); profile.uniqueSignalResolutionConstructionMs = Date.now() - resolutionStartedAt; const aggregationStartedAt = Date.now(); const reports = configs.map((config) => reportForConfig(config, signalsByConfig.get(configKey(config)) ?? [], resolutions)); profile.configurationMetricCalculationMs = Date.now() - aggregationStartedAt;
  const summaryStartedAt = Date.now(); if (!quiet) { report('\nALL ENTRY CONFIGURATION SUMMARIES'); reports.forEach((configReport) => printConfiguration(configReport, sessions)); }
  entryTimeframes.forEach((timeframe) => printTimeframeBest(timeframe, reports, sessions.length, profile));
  const quality = measure(profile, 'fastTradeRankingConstructionMs', () => reports.filter((configReport) => configReport.resolved.length >= qualityMinimumSampleSize).sort(qualityRank)); report('\nFAST-TRADE QUALITY RANKING'); quality.slice(0, 20).forEach((configReport, index) => report(measure(profile, 'finalFormattingStringConstructionMs', () => `${index + 1}. ${formatConfig(configReport.config)} | resolved=${configReport.resolved.length} session=${(configReport.resolved.length / sessions.length).toFixed(2)} +3=${configReport.outcomes[3].positivePercent.toFixed(2)}% +5=${configReport.outcomes[5].positivePercent.toFixed(2)}% avg5=${configReport.outcomes[5].average.toFixed(2)}% med5=${configReport.outcomes[5].median.toFixed(2)}% policy=+${configReport.bestPolicy.target}/-${configReport.bestPolicy.stop}/${configReport.bestPolicy.hold}m target=${configReport.bestPolicy.targetPercent.toFixed(2)}% stop=${configReport.bestPolicy.stopPercent.toFixed(2)}% MFE5=${configReport.excursions[5].mfe.average.toFixed(2)}% MAE5=${configReport.excursions[5].mae.average.toFixed(2)}%`)));
  if (!quiet) [3, 5, 10, 15].forEach((minimum) => report(`Configurations >=${minimum} resolved signals/session: ${reports.filter((configReport) => configReport.resolved.length / sessions.length >= minimum).length}`));
  const bestOverall = quality[0]; if (!bestOverall) throw new Error('No configuration produced the minimum resolved option-premium sample.'); report(measure(profile, 'finalFormattingStringConstructionMs', () => `\nBEST OVERALL FAST ENTRY: ${formatConfig(bestOverall.config)} | resolved=${bestOverall.resolved.length} (${(bestOverall.resolved.length / sessions.length).toFixed(2)}/session)`)); printReachMetrics(bestOverall.resolved, profile); report('\nBEST OVERALL TIME-OF-DAY'); const timeOfDayLines = measure(profile, 'timeOfDaySummaryConstructionMs', () => timeBuckets.map((name) => { const records = bestOverall.resolved.filter((record) => bucket(record.signal.timestamp) === name); const plus3 = percentMetric(records.map((record) => record.resolution.changes.get(3)).filter((value): value is number => value !== null && value !== undefined)); const plus5 = percentMetric(records.map((record) => record.resolution.changes.get(5)).filter((value): value is number => value !== null && value !== undefined)); const mfe5 = percentMetric(records.map((record) => record.resolution.excursions.get(5)?.mfe).filter((value): value is number => value !== null && value !== undefined)); const mae5 = percentMetric(records.map((record) => record.resolution.excursions.get(5)?.mae).filter((value): value is number => value !== null && value !== undefined)); return `${name}: signals=${bestOverall.signals.filter((signal) => bucket(signal.timestamp) === name).length} resolved=${records.length} +3=${plus3.positivePercent.toFixed(2)}% +5=${plus5.positivePercent.toFixed(2)}% avg5=${plus5.average.toFixed(2)}% MFE5=${mfe5.average.toFixed(2)}% MAE5=${mae5.average.toFixed(2)}%`; })); timeOfDayLines.forEach((line) => report(line));
  const policyRankingStartedAt = Date.now(); const allPolicies = quality
    .flatMap((report) => targetStopPairs.flatMap(([target, stop]) => maximumHolds.map((hold) => ({
      report,
      metric: policyMetric(report.resolved, target, stop, hold),
    }))))
    .filter((entry) => entry.metric.total >= qualityMinimumSampleSize)
    .sort((left, right) => right.metric.targetPercent - left.metric.targetPercent || left.metric.stopPercent - right.metric.stopPercent || right.metric.averageReturn - left.metric.averageReturn);
  const policy = allPolicies[0]; profile.policyOutcomeDerivationMs += Date.now() - policyRankingStartedAt;
  if (policy) report(measure(profile, 'finalFormattingStringConstructionMs', () => `\nBEST FAST TARGET/STOP: ${formatConfig(policy.report.config)} | +${policy.metric.target}%/-${policy.metric.stop}% hold=${policy.metric.hold}m | target=${policy.metric.targetPercent.toFixed(2)}% stop=${policy.metric.stopPercent.toFixed(2)}% time=${policy.metric.timeCount} ambiguous=${policy.metric.ambiguous} unavailable=${policy.metric.unavailable} avgReturn=${policy.metric.averageReturn.toFixed(2)}% medianReturn=${policy.metric.medianReturn.toFixed(2)}%`));
  const cacheStats = candleCacheService.getStats(); const totalCachedCandles = await optionCandleRepository.count(); const summaryAndOutputDurationMs = Date.now() - summaryStartedAt; const preloadStats = preloader.getStats(startedAt); const totalDurationMs = Date.now() - startedAt;
  const accountedDurationMs = initializationDurationMs + underlyingDurationMs + preparationDurationMs + optionSessionResolutionDurationMs + profile.uniqueSignalResolutionConstructionMs + profile.configurationMetricCalculationMs + summaryAndOutputDurationMs; const unaccountedDurationMs = totalDurationMs - accountedDurationMs;
  report('PERFORMANCE PROFILE', { targetSessions: sessions.length, quiet, initializationDurationMs, underlyingPreloadMs: underlyingDurationMs, crossSessionWarmupIndicatorsAndCandidateGenerationMs: preparationDurationMs, uniqueOptionSessionResolutionMs: optionSessionResolutionDurationMs, expiryResolutionMs: profile.expiryResolutionMs, optionContractResolutionMs: profile.optionContractResolutionMs, requiredSessionKeyConstructionMs: profile.requiredSessionKeyConstructionMs, bulkPreloadMs: preloadStats.bulkPreloadDurationMs, uniqueSignalResolutionConstructionMs: profile.uniqueSignalResolutionConstructionMs, optionOutcomeEvaluationMs: profile.optionOutcomeEvaluationMs, inMemoryOptionSessionLookupMs: profile.inMemoryOptionSessionLookupMs, optionContractSelectionMs: profile.optionContractSelectionMs, premiumHorizonCalculationMs: profile.premiumHorizonCalculationMs, mfeMaeCalculationMs: profile.mfeMaeCalculationMs, thresholdReachCalculationMs: profile.thresholdReachCalculationMs, targetStopPathPreparationMs: profile.targetStopPathPreparationMs, researchPathAnalyticsMs: profile.researchPathAnalyticsMs, policyOutcomeDerivationMs: profile.policyOutcomeDerivationMs, configurationMetricCalculationMs: profile.configurationMetricCalculationMs, timeframeRankingConstructionMs: profile.timeframeRankingConstructionMs, fastTradeRankingConstructionMs: profile.fastTradeRankingConstructionMs, targetReachSummaryConstructionMs: profile.targetReachSummaryConstructionMs, timeOfDaySummaryConstructionMs: profile.timeOfDaySummaryConstructionMs, finalFormattingStringConstructionMs: profile.finalFormattingStringConstructionMs, summaryAndOutputDurationMs, consoleOutputDurationMs: profile.consoleOutputDurationMs, accountedDurationMs, unaccountedDurationMs, totalCandidateReferences: Array.from(signalsByConfig.values()).reduce((total, signals) => total + signals.length, 0), uniqueSignalTimestamps: uniqueSignals.length, uniqueOptionContractDateSessions: preloadStats.uniqueOptionContractDateSessions, optionSessionsLoadedFromMySql: preloadStats.optionSessionsLoadedFromMySql, optionCandlesLoadedFromMySql: preloadStats.optionCandlesLoadedFromMySql, completeLocalSessions: preloadStats.completeLocalSessions, incompleteLocalSessions: preloadStats.incompleteLocalSessions, missingLocalSessions: preloadStats.missingLocalSessions, inMemoryLookupHits: preloadStats.inMemoryLookupHits, dbFallbackHits: preloadStats.dbFallbackHits, upstoxDownloads: preloadStats.upstoxMissingSessionDownloads, bulkPreloadQueryCount: preloadStats.bulkPreloadQueryCount, bulkPreloadDurationMs: preloadStats.bulkPreloadDurationMs, optionPathAnalysesCreated: profile.analyses, policyOutcomesDerived: profile.policies, estimatedRawCandleScansAvoided: profile.policies - profile.analyses, totalDurationMs });
  report(measure(profile, 'finalFormattingStringConstructionMs', () => `\nOPTION CANDLE CACHE | hits=${cacheStats.hits} misses=${cacheStats.misses} stored=${cacheStats.stored} totalStored=${totalCachedCandles} durationMs=${totalDurationMs}`)); report('RESEARCH PRELOAD', preloader.getStats(startedAt));
  logger.info('TREND_DOWN multi-timeframe PE entry research completed', { sessions: sessions.length, configs: configs.length, uniqueSignals: uniqueSignals.length, cacheStats, totalCachedCandles, durationMs: totalDurationMs }); activeProfile = undefined;
}

run().catch((error) => { logger.error('TREND_DOWN multi-timeframe PE entry research failed', { error }); console.error('TREND_DOWN multi-timeframe PE entry research failed.', error); process.exitCode = 1; });
