import dotenv from 'dotenv';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import logger from '../core/logger/logger';
import HistoricalCandleRepository from '../modules/historical-candles/repositories/historical-candle.repository';
import CandleTimeframeAggregatorService from '../modules/indicators/services/candle-timeframe-aggregator.service';
import IndicatorEngineService from '../modules/indicators/services/indicator-engine.service';
import AdaptiveMarketRegimeService from '../modules/adaptive-intraday/services/adaptive-market-regime.service';
import { Candle } from '../modules/indicators/types';
import UpstoxExpiredOptionCandleClient from '../modules/options/client/upstox-expired-option-candle.client';
import HistoricalOptionCandleRepository from '../modules/options/repositories/historical-option-candle.repository';
import HistoricalOptionCandleCacheService from '../modules/options/services/historical-option-candle-cache.service';
import HistoricalOptionResearchPreloaderService from '../modules/options/services/historical-option-research-preloader.service';
import OptionPremiumPathAnalysisService from '../modules/options/services/option-premium-path-analysis.service';
import { OptionExitPolicyEvaluationResult } from '../modules/options/dto/option-exit-policy.dto';
import { filterCrossSessionResearchTargets, prepareCrossSessionIndicatorWarmup, CrossSessionPreparedSession } from './helpers/cross-session-indicator-warmup';
import { assertV7NoLookAhead, buildV7OptionPremiumFeatures, createV7OptionImpulseConfigs, deduplicateV7Signals, featureKey, generateV7Signals, prepareV7IndicatorContext, v7ConfigKey, v7GridDesign, V7Direction, V7OptionImpulseConfig, V7OptionPremiumFeature, V7Signal } from './helpers/v7-option-premium-impulse-signal-generation';

dotenv.config(); logger.silent = true;
const underlying = 'NSE_INDEX|Nifty 50'; const endDate = process.env.RESEARCH_END_DATE?.trim() || '2026-08-04'; const directory = resolve(process.cwd(), 'artifacts', 'v7-option-impulse');
const policies = [{ target: 2, stop: 2, hold: 3 }, { target: 2, stop: 2, hold: 5 }, { target: 3, stop: 2, hold: 5 }, { target: 3, stop: 3, hold: 5 }, { target: 4, stop: 3, hold: 7 }] as const;
type Policy = typeof policies[number];
interface ManifestContract { direction: V7Direction; timestamp: string; tradingDate: string; instrumentKey: string; tradingSymbol: string; strikePrice: number; expiry: string; }
interface Manifest { globalRequiredSessions: Array<{ instrumentKey: string; tradingDate: string; directions: V7Direction[]; completenessState: string }>; selectedContracts: ManifestContract[]; }
interface Resolution { entryPremium: number; mfe5: number | null; mae5: number | null; exits: ReadonlyMap<string, OptionExitPolicyEvaluationResult>; }
interface CandidateMetric { config: V7OptionImpulseConfig; policy: Policy; resolved: number; settled: number; targetCount: number; stopCount: number; timeoutCount: number; ambiguousCount: number; unavailableCount: number; grossAverage: number; grossMedian: number; net20: number; net40: number; net60: number; targetRate: number; stopRate: number; timeoutRate: number; ambiguousRate: number; mfe5: number; mae5: number; }
interface CandidateTrade { signal: V7Signal; resolution: Resolution; }
type ConfigMetric = CandidateMetric;
let compactSerialization = false;

async function run(): Promise<void> {
  if (process.env.RESEARCH_LOCAL_ONLY !== 'true') throw new Error('V7 Phase 2 requires RESEARCH_LOCAL_ONLY=true.');
  const token = process.env.UPSTOX_ACCESS_TOKEN?.trim(); if (!token) throw new Error('Set UPSTOX_ACCESS_TOKEN in .env.');
  const manifest = JSON.parse(readFileSync(resolve(directory, 'required-option-cache-manifest.json'), 'utf8')) as Manifest;
  const coverage = coverageOf(manifest);
  if (coverage.CE.required !== 541 || coverage.CE.complete !== 541 || coverage.PE.required !== 554 || coverage.PE.complete !== 554 || coverage.global.required !== 1095 || coverage.global.complete !== 1095 || coverage.global.missing !== 0 || coverage.global.incomplete !== 0) throw new Error(`V7 Phase 2 blocked by cache coverage: ${JSON.stringify(coverage)}.`);
  const optionRepository = new HistoricalOptionCandleRepository(); const preloader = new HistoricalOptionResearchPreloaderService(new HistoricalCandleRepository(), optionRepository, new HistoricalOptionCandleCacheService(optionRepository, new UpstoxExpiredOptionCandleClient(token)), true); const engine = new IndicatorEngineService(); const aggregator = new CandleTimeframeAggregatorService(); const regime = new AdaptiveMarketRegimeService({ trendStrengthThreshold: 20, emaProximityPercent: .05, highVolatilityThreshold: .1, lowVolatilityThreshold: .05 });
  const underlyingData = await preloader.preloadUnderlying(underlying, '1minute'); const complete = [...underlyingData.underlyingByDate.entries()].filter(([, rows]) => completeSession(rows)).sort(([a], [b]) => a.localeCompare(b)); const sessions = filterCrossSessionResearchTargets(prepareCrossSessionIndicatorWarmup(complete.map(([date, candles]) => ({ date, candles })), aggregator, engine, regime), endDate); if (sessions.length !== 104) throw new Error(`Expected 104 V7 sessions, found ${sessions.length}.`);
  await preloader.preloadOptionSessions(manifest.globalRequiredSessions); const preload = preloader.getStats(); if (preload.upstoxMissingSessionDownloads !== 0 || preload.dbFallbackHits !== 0) throw new Error('V7 local-only preload used an unexpected fallback/download.');
  const indicators = prepareV7IndicatorContext(sessions, engine); const configs = createV7OptionImpulseConfigs(); const broad = manifest.selectedContracts; const selectionBySignal = new Map<string, ManifestContract>(); broad.forEach((entry) => selectionBySignal.set(featureKey(entry.direction, new Date(entry.timestamp).getTime()), selectionBySignal.get(featureKey(entry.direction, new Date(entry.timestamp).getTime())) ?? entry));
  const featureBySignal = await buildFeatureMap(broad, preloader, engine); phaseIndicators = indicators; phaseFeatures = featureBySignal; const pathMap = new Map<string, Resolution>(); const allSignals = new Map<string, V7Signal>(); const metrics: ConfigMetric[] = [];
  for (const config of configs) {
    const signals = generateV7Signals(sessions, config, indicators, featureBySignal); assertV7NoLookAhead(signals); signals.forEach((signal) => allSignals.set(`${signal.direction}\u0000${signal.timestamp.getTime()}`, allSignals.get(`${signal.direction}\u0000${signal.timestamp.getTime()}`) ?? signal));
    for (const signal of signals) { const key = `${signal.direction}\u0000${signal.timestamp.getTime()}`; if (pathMap.has(key)) continue; const selected = selectionBySignal.get(featureKey(signal.direction, signal.timestamp.getTime())); if (!selected) continue; const candles = await preloader.getOptionSession({ instrumentKey: selected.instrumentKey, tradingDate: selected.tradingDate }); const path = new OptionPremiumPathAnalysisService(signal.timestamp, candles); const analytics = path.researchAnalytics({ changeHorizons: [], excursionHorizons: [5], upsideTargets: [], downsideStops: [] }); const exits = new Map<string, OptionExitPolicyEvaluationResult>(); policies.forEach((policy) => exits.set(policyKey(policy), path.evaluate({ type: 'TARGET_STOP', targetPercent: policy.target, stopLossPercent: policy.stop, maximumHoldingMinutes: policy.hold }))); const excursion = analytics.excursions.get(5); pathMap.set(key, { entryPremium: analytics.entryPremium, mfe5: excursion?.mfe ?? null, mae5: excursion?.mae ?? null, exits }); }
    for (const policy of policies) metrics.push(metric(config, signals.flatMap((signal) => { const resolution = pathMap.get(`${signal.direction}\u0000${signal.timestamp.getTime()}`); return resolution ? [{ signal, resolution }] : []; }), policy));
  }
  const byDirection = (direction: V7Direction) => metrics.filter((metric) => metric.config.direction === direction); const ce = analyze('CE', byDirection('CE'), sessions, metrics, allSignals, pathMap); const pe = analyze('PE', byDirection('PE'), sessions, metrics, allSignals, pathMap); const tiers = frequencyTiers(metrics, sessions); const combined = combine(ce.bestBalanced, pe.bestBalanced, sessions, pathMap); const parameterFamilies = familyAnalysis(metrics, sessions); const overlap = overlapReport(ce.bestBalanced ?? pe.bestBalanced, sessions, allSignals); compactSerialization = true;
  mkdirSync(directory, { recursive: true }); write('outcome-grid-results.json', metrics.map((metric) => serializeMetric(metric, sessions, allSignals, pathMap))); write('ce-ranking.json', rankingArtifact(ce, sessions, allSignals, pathMap)); write('pe-ranking.json', rankingArtifact(pe, sessions, allSignals, pathMap)); write('combined-ranking.json', combined); write('frequency-tier-analysis.json', tiers); write('daily-results.json', { CE: leaderDaily(ce, sessions, allSignals, pathMap), PE: leaderDaily(pe, sessions, allSignals, pathMap), combined: combined.daily }); write('monthly-results.json', { CE: leaderRobustness(ce, sessions, allSignals, pathMap), PE: leaderRobustness(pe, sessions, allSignals, pathMap), combined: combined.robustness }); write('time-of-day-analysis.json', { CE: leaderTime(ce, sessions, allSignals, pathMap), PE: leaderTime(pe, sessions, allSignals, pathMap) }); write('parameter-family-analysis.json', parameterFamilies); write('robustness-report.json', { CE: leaderRobustness(ce, sessions, allSignals, pathMap), PE: leaderRobustness(pe, sessions, allSignals, pathMap), combined: combined.robustness }); write('overlap-report.json', overlap); const final = { scope: { start: sessions[0].date, end: sessions.at(-1)?.date, targetSessions: sessions.length }, configurations: { CE: 6400, PE: 6400, total: configs.length }, policiesPerConfiguration: policies.length, totalPolicyEvaluations: metrics.length, coverage, CE: rankingSummary(ce, sessions, allSignals, pathMap), PE: rankingSummary(pe, sessions, allSignals, pathMap), tiers, combined, parameterFamilies, overlap, preloader: { ...preload, optionPathAnalyses: pathMap.size, uniqueConfirmedSignals: allSignals.size }, verdict: verdict(ce, pe) }; write('final-v7-research-summary.json', final);
  console.log('V7 PHASE 2 OUTCOME RESEARCH', { sessions: sessions.length, configs: configs.length, policiesPerConfiguration: policies.length, totalPolicyEvaluations: metrics.length, uniqueConfirmedSignals: allSignals.size, coverage }); console.log('V7 CE', rankingSummary(ce, sessions, allSignals, pathMap)); console.log('V7 PE', rankingSummary(pe, sessions, allSignals, pathMap)); console.log('V7 HIGH-FREQUENCY TIERS', tiers); console.log('V7 COMBINED', combined); console.log('V7 PARAMETER FAMILIES', parameterFamilies); console.log('V7 OVERLAP', overlap); console.log('V7 CACHE/PERFORMANCE', { ...preload, optionPathAnalyses: pathMap.size }); console.log('V7 FINAL VERDICT', verdict(ce, pe));
}

async function buildFeatureMap(entries: readonly ManifestContract[], preloader: HistoricalOptionResearchPreloaderService, engine: IndicatorEngineService): Promise<Map<string, V7OptionPremiumFeature>> { const bySession = new Map<string, V7OptionPremiumFeature[]>(); const result = new Map<string, V7OptionPremiumFeature>(); for (const entry of entries) { const sessionKey = `${entry.instrumentKey}\u0000${entry.tradingDate}`; if (!bySession.has(sessionKey)) { const rows = await preloader.getOptionSession({ instrumentKey: entry.instrumentKey, tradingDate: entry.tradingDate }); bySession.set(sessionKey, buildV7OptionPremiumFeatures(entry.direction, entry.instrumentKey, entry.tradingDate, rows.map((row) => ({ timestamp: new Date(row.candleTime.getTime()), open: row.open, high: row.high, low: row.low, close: row.close, volume: Number(row.volume), openInterest: row.openInterest === undefined ? undefined : Number(row.openInterest) })), engine)); } const features = bySession.get(sessionKey)!; const value = features.find((feature) => feature.availableAt.getTime() === new Date(entry.timestamp).getTime()); if (value) result.set(featureKey(entry.direction, new Date(entry.timestamp).getTime()), value); } return result; }
function metric(config: V7OptionImpulseConfig, trades: readonly CandidateTrade[], policy: Policy): ConfigMetric { const exits = trades.map((trade) => trade.resolution.exits.get(policyKey(policy))).filter((value): value is OptionExitPolicyEvaluationResult => !!value); const settled = exits.filter((exit) => !exit.ambiguous && !exit.unavailable && exit.premiumChangePercent !== null); const returns = settled.map((exit) => exit.premiumChangePercent!); const targetCount = settled.filter((exit) => exit.exitReason === 'TARGET').length; const stopCount = settled.filter((exit) => exit.exitReason === 'STOP_LOSS').length; const timeoutCount = settled.filter((exit) => exit.exitReason === 'TIME_EXIT').length; return { config, policy, resolved: trades.length, settled: settled.length, targetCount, stopCount, timeoutCount, ambiguousCount: exits.filter((exit) => exit.ambiguous).length, unavailableCount: exits.filter((exit) => exit.unavailable).length, grossAverage: avg(returns), grossMedian: median(returns), net20: avg(returns) - .2, net40: avg(returns) - .4, net60: avg(returns) - .6, targetRate: rate(targetCount, settled.length), stopRate: rate(stopCount, settled.length), timeoutRate: rate(timeoutCount, settled.length), ambiguousRate: rate(exits.filter((exit) => exit.ambiguous).length, exits.length), mfe5: avg(trades.map((trade) => trade.resolution.mfe5).filter((value): value is number => value !== null)), mae5: avg(trades.map((trade) => trade.resolution.mae5).filter((value): value is number => value !== null)) }; }
function analyze(direction: V7Direction, values: readonly ConfigMetric[], sessions: readonly CrossSessionPreparedSession[], all: readonly ConfigMetric[], signals: ReadonlyMap<string, V7Signal>, paths: ReadonlyMap<string, Resolution>) { const candidates = values.filter((value) => value.resolved > 0); const credible = candidates.filter(isCredible); const ranked = [...(credible.length ? credible : candidates)].sort(rank); const highestFrequency = [...candidates].sort((a, b) => b.resolved - a.resolved || rank(a, b))[0]; const highestQuality = ranked[0]; const bestBalanced = [...credible.filter((value) => value.resolved / sessions.length >= 1)].sort(rank)[0] ?? highestQuality; return { direction, all: candidates, credibleAfter040: credible.length, ranked: ranked.slice(0, 20), highestFrequency, highestQuality, bestBalanced }; }
function combine(ce: ConfigMetric | undefined, pe: ConfigMetric | undefined, sessions: readonly CrossSessionPreparedSession[], paths: ReadonlyMap<string, Resolution>) { if (!ce || !pe || !isCredible(ce) || !isCredible(pe)) return { status: 'NOT_COMBINED: both directions did not independently meet credibility criteria.' }; const records = [...tradesFor(ce, sessions, paths), ...tradesFor(pe, sessions, paths)].flatMap((trade) => { const exit = trade.resolution.exits.get(policyKey(ce.policy)); return exit && !exit.ambiguous && !exit.unavailable && exit.premiumChangePercent !== null ? [{ ...trade, exit }] : []; }).sort((a, b) => a.signal.timestamp.getTime() - b.signal.timestamp.getTime()); const values = records.map((record) => record.exit.premiumChangePercent!); const daily = new Map<string, number[]>(); records.forEach((record) => daily.set(record.signal.date, [...(daily.get(record.signal.date) ?? []), record.exit.premiumChangePercent!])); return { status: 'COMBINED', trades: records.length, tradesPerSession: round(records.length / sessions.length), activeDays: daily.size, maxTradesPerDay: Math.max(0, ...[...daily.values()].map((value) => value.length)), grossAverage: round(avg(values)), grossMedian: round(median(values)), netAt020: round(avg(values) - .2), netAt040: round(avg(values) - .4), netAt060: round(avg(values) - .6), profitableDayPercent: round([...daily.values()].filter((value) => sum(value) > 0).length / Math.max(1, daily.size) * 100), maxLosingStreak: streak(records.map((record) => record.exit.premiumChangePercent! < 0)), CEContribution: ce.resolved, PEContribution: pe.resolved, daily: [...daily.entries()].map(([date, value]) => ({ date, trades: value.length, gross: round(sum(value)), netAt040: round(sum(value) - .4 * value.length) })), robustness: combinedRobustness(records, sessions) }; }
function tradesFor(metricValue: ConfigMetric, sessions: readonly CrossSessionPreparedSession[], paths: ReadonlyMap<string, Resolution>): CandidateTrade[] { const indicators = phaseIndicators; const signals = generateV7Signals(sessions, metricValue.config, indicators, phaseFeatures); assertV7NoLookAhead(signals); return signals.flatMap((signal) => { const resolution = paths.get(`${signal.direction}\u0000${signal.timestamp.getTime()}`); return resolution ? [{ signal, resolution }] : []; }); }
let phaseIndicators: ReturnType<typeof prepareV7IndicatorContext>; let phaseFeatures: ReadonlyMap<string, V7OptionPremiumFeature>;
function rankingSummary(result: ReturnType<typeof analyze>, sessions: readonly CrossSessionPreparedSession[], signals: ReadonlyMap<string, V7Signal>, paths: ReadonlyMap<string, Resolution>) { compactSerialization = false; return { direction: result.direction, policyCandidates: result.all.length, credibleAfter040: result.credibleAfter040, highestFrequency: result.highestFrequency ? serializeMetric(result.highestFrequency, sessions, signals, paths) : null, highestQuality: result.highestQuality ? serializeMetric(result.highestQuality, sessions, signals, paths) : null, bestBalanced: result.bestBalanced ? serializeMetric(result.bestBalanced, sessions, signals, paths) : null, top20: result.ranked.map((value) => serializeMetric(value, sessions, signals, paths)) }; }
function rankingArtifact(result: ReturnType<typeof analyze>, sessions: readonly CrossSessionPreparedSession[], signals: ReadonlyMap<string, V7Signal>, paths: ReadonlyMap<string, Resolution>) { return rankingSummary(result, sessions, signals, paths); }
function serializeMetric(value: ConfigMetric, sessions: readonly CrossSessionPreparedSession[], signals: ReadonlyMap<string, V7Signal>, paths: ReadonlyMap<string, Resolution>) { if (compactSerialization) return compactMetric(value); const trades = tradesFor(value, sessions, paths); const frequency = dailyFrequency(trades, sessions); return { configKey: v7ConfigKey(value.config), direction: value.config.direction, config: value.config, policy: value.policy, trades: value.resolved, settled: value.settled, tradesPerSession: round(value.resolved / sessions.length), activeSessions: frequency.activeSessions, maxTradesPerDay: frequency.maxTradesPerDay, grossAverage: round(value.grossAverage), grossMedian: round(value.grossMedian), netAt020: round(value.net20), netAt040: round(value.net40), netAt060: round(value.net60), targetRate: round(value.targetRate), stopRate: round(value.stopRate), timeoutRate: round(value.timeoutRate), ambiguousRate: round(value.ambiguousRate), ambiguousCount: value.ambiguousCount, unavailableCount: value.unavailableCount, mfe5: round(value.mfe5), mae5: round(value.mae5), profitableDayPercent: round(profitableDays(trades, value.policy)), maxLosingStreak: streak(settledRecords(trades, value.policy).map((record) => record.exit.premiumChangePercent! < 0)), credibleAt040: isCredible(value), frequency }; }
function compactMetric(value: ConfigMetric) { return { configKey: v7ConfigKey(value.config), direction: value.config.direction, config: value.config, policy: value.policy, trades: value.resolved, settled: value.settled, tradesPerSession: round(value.resolved / 104), grossAverage: round(value.grossAverage), grossMedian: round(value.grossMedian), netAt020: round(value.net20), netAt040: round(value.net40), netAt060: round(value.net60), targetRate: round(value.targetRate), stopRate: round(value.stopRate), timeoutRate: round(value.timeoutRate), ambiguousRate: round(value.ambiguousRate), ambiguousCount: value.ambiguousCount, unavailableCount: value.unavailableCount, mfe5: round(value.mfe5), mae5: round(value.mae5), credibleAt040: isCredible(value) }; }
function leaderDaily(result: ReturnType<typeof analyze>, sessions: readonly CrossSessionPreparedSession[], signals: ReadonlyMap<string, V7Signal>, paths: ReadonlyMap<string, Resolution>) { return result.bestBalanced ? dailyFor(result.bestBalanced, sessions, paths) : []; }
function leaderRobustness(result: ReturnType<typeof analyze>, sessions: readonly CrossSessionPreparedSession[], signals: ReadonlyMap<string, V7Signal>, paths: ReadonlyMap<string, Resolution>) { return result.bestBalanced ? robustness(result.bestBalanced, sessions, paths) : null; }
function leaderTime(result: ReturnType<typeof analyze>, sessions: readonly CrossSessionPreparedSession[], signals: ReadonlyMap<string, V7Signal>, paths: ReadonlyMap<string, Resolution>) { return result.bestBalanced ? timeOfDay(result.bestBalanced, sessions, paths) : []; }
function dailyFor(value: ConfigMetric, sessions: readonly CrossSessionPreparedSession[], paths: ReadonlyMap<string, Resolution>) { const trades = settledRecords(tradesFor(value, sessions, paths), value.policy); return sessions.map((session) => { const values = trades.filter((record) => record.signal.date === session.date).map((record) => record.exit.premiumChangePercent!); return { date: session.date, trades: values.length, grossSum: round(sum(values)), netSumAt040: round(sum(values) - .4 * values.length) }; }); }
function robustness(value: ConfigMetric, sessions: readonly CrossSessionPreparedSession[], paths: ReadonlyMap<string, Resolution>) { const trades = tradesFor(value, sessions, paths); const settled = settledRecords(trades, value.policy); const summary = (records: readonly { signal: V7Signal; exit: OptionExitPolicyEvaluationResult }[]) => { const values = records.map((record) => record.exit.premiumChangePercent!); return { trades: values.length, grossAverage: round(avg(values)), netAt040: round(avg(values) - .4), median: round(median(values)), targetRate: rate(records.filter((record) => record.exit.exitReason === 'TARGET').length, values.length), stopRate: rate(records.filter((record) => record.exit.exitReason === 'STOP_LOSS').length, values.length) }; }; const midpoint = Math.floor(sessions.length / 2); const first = new Set(sessions.slice(0, midpoint).map((session) => session.date)); const returns = settled.map((record) => record.exit.premiumChangePercent!); const ordered = [...returns].sort((a, b) => a - b); return { monthly: [['March', '2026-03'], ['April', '2026-04'], ['May', '2026-05'], ['June', '2026-06'], ['July', '2026-07'], ['Aug 1-4', '2026-08']].map(([month, prefix]) => ({ month, ...summary(trades.filter((trade) => trade.signal.date.startsWith(prefix)).flatMap((trade) => settledRecords([trade], value.policy))) })), halves: [{ period: 'First half', ...summary(settled.filter((record) => first.has(record.signal.date))) }, { period: 'Second half', ...summary(settled.filter((record) => !first.has(record.signal.date))) }], frequency: dailyFrequency(trades, sessions), profitableDayPercent: round(profitableDays(trades, value.policy)), maxConsecutiveLosses: streak(settled.map((record) => record.exit.premiumChangePercent! < 0)), maxLosingDayStreak: streak(dailyFor(value, sessions, paths).map((day) => day.grossSum < 0)), averageExcludingBest5: round(avg(ordered.slice(0, Math.max(0, ordered.length - 5)))), best5ContributionPercent: round(sum(returns.filter((value) => value > 0)) ? sum(ordered.slice(-5).filter((value) => value > 0)) / sum(returns.filter((value) => value > 0)) * 100 : 0), largestWinner: round(ordered.at(-1) ?? 0), largestLoser: round(ordered[0] ?? 0), timeOfDay: timeOfDay(value, sessions, paths) }; }
function timeOfDay(value: ConfigMetric, sessions: readonly CrossSessionPreparedSession[], paths: ReadonlyMap<string, Resolution>) { const ranges: ReadonlyArray<readonly [string, number, number]> = [['09:15-10:30', 555, 630], ['10:30-12:00', 630, 720], ['12:00-13:30', 720, 810], ['13:30-15:30', 810, 930]]; const settled = settledRecords(tradesFor(value, sessions, paths), value.policy); return ranges.map(([bucket, start, end]) => { const rows = settled.filter((record) => { const minute = istMinute(record.signal.timestamp); return minute >= start && minute < end; }); const values = rows.map((row) => row.exit.premiumChangePercent!); return { bucket, trades: rows.length, grossAverage: round(avg(values)), netAt040: round(avg(values) - .4), median: round(median(values)) }; }); }
function frequencyTiers(values: readonly ConfigMetric[], sessions: readonly CrossSessionPreparedSession[]) { return [3, 5, 8, 10].map((threshold) => { const matching = values.filter((value) => value.resolved / sessions.length >= threshold); const positive = matching.filter((value) => value.net40 > 0); const best = [...positive].sort(rank)[0]; return { minimumTradesPerSession: threshold, candidateCount: matching.length, positiveNetAt040Count: positive.length, bestPositiveNetAt040: best ? serializeMetric(best, sessions, new Map(), new Map()) : null }; }); }
function familyAnalysis(values: readonly ConfigMetric[], _sessions: readonly CrossSessionPreparedSession[]) {
  const fields: Array<[string, (value: ConfigMetric) => string]> = [
    ['underlyingTimeframe', (value) => `${value.config.timeframe}m`],
    ['regimeFamily', (value) => value.config.underlying.regimeFamily],
    ['premiumConfirmation', (value) => value.config.premium.confirmation],
    ['minimumPremium', (value) => String(value.config.minimumPremium)],
    ['cooldown', (value) => String(value.config.cooldownMinutes)],
    ['underlyingBreakoutLookback', (value) => String(value.config.underlying.breakoutLookbackBars)],
    ['optionBreakoutLookback', (value) => String(value.config.premium.breakoutLookbackBars ?? 'NONE')],
  ];
  return Object.fromEntries(fields.map(([field, select]) => {
    const groups = [...new Set(values.map(select))];
    const result = Object.fromEntries(groups.map((group) => {
      const rows = values.filter((value) => select(value) === group);
      return [group, { candidates: rows.length, bestNetAt040: round(Math.max(...rows.map((value) => value.net40))), averageNetAt040: round(avg(rows.map((value) => value.net40))), positiveNetAt040: rows.filter((value) => value.net40 > 0).length }];
    }));
    return [field, result];
  }));
}
function combinedRobustness(records: readonly { signal: V7Signal; exit: OptionExitPolicyEvaluationResult }[], sessions: readonly CrossSessionPreparedSession[]) { const summary = (items: readonly { signal: V7Signal; exit: OptionExitPolicyEvaluationResult }[]) => { const values = items.map((item) => item.exit.premiumChangePercent!); return { trades: values.length, grossAverage: round(avg(values)), netAt040: round(avg(values) - .4), median: round(median(values)) }; }; const midpoint = Math.floor(sessions.length / 2); const first = new Set(sessions.slice(0, midpoint).map((session) => session.date)); return { monthly: ['2026-03', '2026-04', '2026-05', '2026-06', '2026-07', '2026-08'].map((prefix) => ({ month: prefix, ...summary(records.filter((record) => record.signal.date.startsWith(prefix))) })), halves: [{ period: 'First half', ...summary(records.filter((record) => first.has(record.signal.date))) }, { period: 'Second half', ...summary(records.filter((record) => !first.has(record.signal.date))) }] }; }
function overlapReport(value: ConfigMetric | undefined, sessions: readonly CrossSessionPreparedSession[], signals: ReadonlyMap<string, V7Signal>) { const artifacts = ['V2', 'V4', 'V5', 'V6'].map((name) => ({ name, available: existsSync(resolve(process.cwd(), 'artifacts', name === 'V6' ? 'v6-sideways-mean-reversion' : name === 'V5' ? 'v5-scalping' : '')) })); return { status: 'SIGNAL_TIMESTAMP_ARTIFACTS_NOT_AVAILABLE', candidate: value ? v7ConfigKey(value.config) : null, note: 'Existing V2/V4/V5/V6 artifacts contain summaries, not complete timestamp sets; no overlap counts were inferred.', artifacts }; }
function coverageOf(manifest: Manifest) { const rows = manifest.globalRequiredSessions; const ce = rows.filter((row) => row.directions.includes('CE')); const pe = rows.filter((row) => row.directions.includes('PE')); return { CE: { required: ce.length, complete: ce.filter((row) => row.completenessState === 'COMPLETE').length, missing: ce.filter((row) => row.completenessState === 'MISSING').length, incomplete: ce.filter((row) => row.completenessState === 'INCOMPLETE').length }, PE: { required: pe.length, complete: pe.filter((row) => row.completenessState === 'COMPLETE').length, missing: pe.filter((row) => row.completenessState === 'MISSING').length, incomplete: pe.filter((row) => row.completenessState === 'INCOMPLETE').length }, global: { required: rows.length, complete: rows.filter((row) => row.completenessState === 'COMPLETE').length, missing: rows.filter((row) => row.completenessState === 'MISSING').length, incomplete: rows.filter((row) => row.completenessState === 'INCOMPLETE').length } }; }
function dailyFrequency(trades: readonly CandidateTrade[], sessions: readonly CrossSessionPreparedSession[]) { const counts = sessions.map((session) => trades.filter((trade) => trade.signal.date === session.date).length); return { activeSessions: counts.filter((value) => value > 0).length, maxTradesPerDay: Math.max(0, ...counts), averageTradesPerActiveSession: round(trades.length / Math.max(1, counts.filter((value) => value > 0).length)), daysWith0: counts.filter((value) => value === 0).length, daysWith1To4: counts.filter((value) => value >= 1 && value <= 4).length, daysWith5To9: counts.filter((value) => value >= 5 && value <= 9).length, daysWith10Plus: counts.filter((value) => value >= 10).length }; }
function profitableDays(trades: readonly CandidateTrade[], policy: Policy) { const byDate = new Map<string, number>(); settledRecords(trades, policy).forEach((record) => byDate.set(record.signal.date, (byDate.get(record.signal.date) ?? 0) + record.exit.premiumChangePercent!)); return [...byDate.values()].filter((value) => value > 0).length / Math.max(1, byDate.size) * 100; }
function settledRecords(trades: readonly CandidateTrade[], policy: Policy) { return trades.flatMap((trade) => { const exit = trade.resolution.exits.get(policyKey(policy)); return exit && !exit.ambiguous && !exit.unavailable && exit.premiumChangePercent !== null ? [{ signal: trade.signal, exit }] : []; }); }
function isCredible(value: ConfigMetric) { return value.resolved >= 30 && value.net40 > 0 && value.grossMedian >= 0 && value.targetRate > value.stopRate; }
function verdict(ce: ReturnType<typeof analyze>, pe: ReturnType<typeof analyze>) { const candidates = [ce.bestBalanced, pe.bestBalanced].filter((value): value is ConfigMetric => !!value && isCredible(value)); if (!candidates.length) return 'REJECT'; if (candidates.some((value) => value.resolved >= 104 && value.net40 > .4)) return 'PROMISING'; return 'WEAK'; }
function rank(a: ConfigMetric, b: ConfigMetric) { return b.net40 - a.net40 || b.grossMedian - a.grossMedian || b.targetRate - a.targetRate || a.stopRate - b.stopRate || b.resolved - a.resolved; }
function policyKey(policy: Policy) { return `${policy.target}|${policy.stop}|${policy.hold}`; }
function avg(values: readonly number[]) { return values.length ? sum(values) / values.length : 0; } function sum(values: readonly number[]) { return values.reduce((total, value) => total + value, 0); } function median(values: readonly number[]) { if (!values.length) return 0; const sorted = [...values].sort((a, b) => a - b); const middle = Math.floor(sorted.length / 2); return sorted.length % 2 ? sorted[middle] : (sorted[middle - 1] + sorted[middle]) / 2; } function rate(value: number, total: number) { return total ? value / total * 100 : 0; } function round(value: number) { return Number(value.toFixed(2)); } function streak(values: readonly boolean[]) { let current = 0; let best = 0; values.forEach((value) => { current = value ? current + 1 : 0; best = Math.max(best, current); }); return best; } function istMinute(value: Date) { const parts = Object.fromEntries(new Intl.DateTimeFormat('en-GB', { timeZone: 'Asia/Kolkata', hour: '2-digit', minute: '2-digit', hourCycle: 'h23' }).formatToParts(value).map((part) => [part.type, part.value])); return Number(parts.hour) * 60 + Number(parts.minute); } function completeSession(candles: readonly { timestamp: Date }[]) { if (candles.length !== 375) return false; const sorted = [...candles].sort((a, b) => a.timestamp.getTime() - b.timestamp.getTime()); return istMinute(sorted[0].timestamp) === 555 && istMinute(sorted[374].timestamp) === 929 && sorted.every((candle, index) => index === 0 || candle.timestamp.getTime() - sorted[index - 1].timestamp.getTime() === 60_000); } function write(name: string, value: unknown) { writeFileSync(resolve(directory, name), `${JSON.stringify(value, null, 2)}\n`); }
run().catch((error) => { console.error('V7 Phase 2 outcome research failed.', error); process.exitCode = 1; });
