import 'dotenv/config';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { PrismaClient } from '@prisma/client';
import HistoricalCandleRepository from '../modules/historical-candles/repositories/historical-candle.repository';
import ResearchSplitService from '../modules/research-validation/services/research-split.service';
import { solveEuropeanImpliedVolatility } from '../modules/research/v11-nifty-iv-skew/implied-volatility';

const NIFTY = 'NSE_INDEX|Nifty 50'; const END = '2026-08-04'; const RATE = .06; const DIVIDEND = 0; const DIRECTORY = resolve(process.cwd(), 'artifacts', 'v11-nifty-iv-skew');
const OBSERVATIONS = ['09:30', '10:30', '12:00', '14:00'] as const;
type Type = 'CE' | 'PE'; type OptionRow = { instrumentKey: string; tradingSymbol: string | null; optionType: string | null; strikePrice: any; expiry: Date | null; candleTime: Date; open: any; high: any; low: any; close: any; volume: bigint; };
type Contract = { instrumentKey: string; optionType: Type; strike: number; expiry: Date; expiryDate: string; rows: OptionRow[] };

async function run(): Promise<void> {
  if (process.env.RESEARCH_LOCAL_ONLY !== 'true') throw new Error('V11 phase-0 audit requires RESEARCH_LOCAL_ONLY=true.');
  const split = JSON.parse(readFileSync(resolve(process.cwd(), 'artifacts/research-validation/nifty-104-split-v1.json'), 'utf8')); const dates: string[] = split.sessions.filter((row: any) => ['TRAIN', 'VALIDATION'].includes(row.split) && row.tradingDate <= END).map((row: any) => row.tradingDate); new ResearchSplitService().assertOutcomeAccess(split, dates, 'TRAIN_VALIDATION_ONLY');
  const underlyingRows = await new HistoricalCandleRepository().findByInstrumentAndTimeframe(NIFTY, '1minute'); const spotByDateTime = new Map<string, number>(); underlyingRows.forEach((row: any) => { const date = istDate(new Date(row.candleTime)); if (dates.includes(date)) spotByDateTime.set(`${date}|${new Date(row.candleTime).getTime()}`, Number(row.close)); });
  const prisma = new PrismaClient(); let rows: OptionRow[] = [];
  try { rows = await prisma.historicalOptionCandle.findMany({ where: { timeframe: '1minute', candleTime: { gte: new Date(`${dates[0]}T00:00:00+05:30`), lte: new Date(`${END}T23:59:59.999+05:30`) } }, select: { instrumentKey: true, tradingSymbol: true, optionType: true, strikePrice: true, expiry: true, candleTime: true, open: true, high: true, low: true, close: true, volume: true } }) as OptionRow[]; } finally { await prisma.$disconnect(); }
  const niftyRows = rows.filter((row) => isNiftyOption(row) && row.optionType && row.strikePrice && row.expiry); const contractsByDate = buildContracts(niftyRows, dates);
  const snapshots: any[] = []; const coverageRows: any[] = []; const ivResults: any[] = []; const featureRows: any[] = []; const requiredSessions = new Set<string>();
  for (const date of dates) for (const time of OBSERVATIONS) {
    const observedAt = istTimestamp(date, time); const premiumAt = new Date(observedAt.getTime() - 60_000); const spot = spotByDateTime.get(`${date}|${premiumAt.getTime()}`);
    const surface = chooseSurface(contractsByDate.get(date) ?? [], date, spot);
    const coverage = assessCoverage(surface, premiumAt, date); const { required, ...coverageForArtifact } = coverage; coverageRows.push({ date, observationIst: formatIst(observedAt), ...coverageForArtifact, ceLegPresent: required.some((contract: Contract) => contract.optionType === 'CE'), peLegPresent: required.some((contract: Contract) => contract.optionType === 'PE') }); required.forEach((contract: Contract) => requiredSessions.add(`${contract.instrumentKey}|${date}`));
    if (!spot || !surface) { snapshots.push({ date, time, status: 'METADATA_OR_SPOT_UNAVAILABLE' }); continue; }
    const ivs = calculateIvSurface(surface, spot, premiumAt); ivResults.push(...ivs.values); const feature = features(surface, ivs.byLabel, spot, observedAt, premiumAt, (at) => spotByDateTime.get(`${date}|${at.getTime()}`)); featureRows.push({ date, observationIst: formatIst(observedAt), ...feature }); snapshots.push({ date, observationIst: formatIst(observedAt), spot, atmStrike: surface.atm, ...coverageForArtifact, ...feature });
  }
  const quality = ivQuality(ivResults); const coverage = coverageSummary(coverageRows, contractsByDate, requiredSessions); const feasibility = featureSummary(featureRows, snapshots);
  const additional = { knownMissingCachedInstrumentDateSessions: coverage.missingLocalSessions, unresolvedSurfaceLegSlots: quality.failures.MISSING_CONTRACT, uniqueInstruments: null, instrumentDateSessions: null, expectedNetworkRequests: null, expectedRowsAt375PerCompleteSession: null, requiredPreparation: 'Fetch/audit the expired-option chain metadata first; local historical-option rows only describe previously cached contracts, so exact missing wing instruments cannot be derived safely from this cache alone.', note: 'No option download was attempted. A count of zero known cache misses does not imply full surface coverage.' };
  const summary = { strategyId: 'V11_NIFTY_IV_SKEW_RISK_REVERSAL', phase: 'PHASE_0_DATA_IV_FEASIBILITY_ONLY', protectedMode: 'TRAIN_VALIDATION_ONLY', sessionsAudited: dates.length, timestampsPerSession: OBSERVATIONS.length, networkRequests: 0, cacheWrites: 0, assumptions: { spot: 'NIFTY one-minute close from the candle completed immediately before the observation timestamp.', optionPremium: 'Option one-minute close from the candle completed immediately before the observation timestamp; no forming candle.', timeToExpiry: 'Exact observation-to-15:30 IST distance on the contract expiry IST date. Persisted expiry metadata is date-only/midnight-like and is normalized only for research clock convention.', riskFreeRateAnnualized: RATE, dividendYield: DIVIDEND, dividendConvention: 'No dividend yield / no historical dividend curve.' }, coverage, ivQuality: quality, featureFeasibility: feasibility, additionalDataEstimate: additional, recommendation: decide(coverage, quality, feasibility) };
  mkdirSync(DIRECTORY, { recursive: true }); write('phase-0-option-coverage.json', { ...coverage, representativeObservations: coverageRows, additionalDataEstimate: additional }); write('phase-0-iv-quality.json', { assumptions: summary.assumptions, ...quality }); write('phase-0-feature-feasibility.json', feasibility); write('phase-0-summary.json', summary);
  console.log(JSON.stringify(summary, null, 2));
}

function buildContracts(rows: readonly OptionRow[], dates: readonly string[]) { const result = new Map<string, Contract[]>(); const grouped = new Map<string, OptionRow[]>(); rows.forEach((row) => { const date = istDate(row.candleTime); if (!dates.includes(date)) return; const key = `${date}|${row.instrumentKey}`; grouped.set(key, [...(grouped.get(key) ?? []), row]); }); grouped.forEach((items, key) => { const [date] = key.split('|'); const first = items[0]; if (!isType(first.optionType) || !first.expiry || first.strikePrice === null) return; const contract: Contract = { instrumentKey: first.instrumentKey, optionType: first.optionType, strike: Number(first.strikePrice), expiry: first.expiry, expiryDate: istDate(first.expiry), rows: [...items].sort((left, right) => left.candleTime.getTime() - right.candleTime.getTime()) }; result.set(date, [...(result.get(date) ?? []), contract]); }); return result; }
function chooseSurface(contracts: readonly Contract[], date: string, spot: number | undefined) { if (!spot) return undefined; const valid = contracts.filter((contract) => contract.expiryDate >= date); const expiryDate = [...new Set(valid.map((contract) => contract.expiryDate))].sort()[0]; if (!expiryDate) return undefined; const expiryContracts = valid.filter((contract) => contract.expiryDate === expiryDate); const strikes = [...new Set(expiryContracts.map((contract) => contract.strike))].sort((left, right) => left - right); const atm = [...strikes].sort((left, right) => Math.abs(left - spot) - Math.abs(right - spot) || left - right)[0]; if (atm === undefined) return undefined; const index = strikes.indexOf(atm); const find = (strike: number | undefined, type: Type) => strike === undefined ? undefined : expiryContracts.find((contract) => contract.strike === strike && contract.optionType === type);
  const byLabel: Record<string, Contract | undefined> = { ATM_CE: find(atm, 'CE'), ATM_PE: find(atm, 'PE'), DOWN1_CE: find(strikes[index - 1], 'CE'), DOWN1_PE: find(strikes[index - 1], 'PE'), UP1_CE: find(strikes[index + 1], 'CE'), UP1_PE: find(strikes[index + 1], 'PE'), DOWN2_CE: find(strikes[index - 2], 'CE'), DOWN2_PE: find(strikes[index - 2], 'PE'), UP2_CE: find(strikes[index + 2], 'CE'), UP2_PE: find(strikes[index + 2], 'PE'), DOWN3_CE: find(strikes[index - 3], 'CE'), DOWN3_PE: find(strikes[index - 3], 'PE'), UP3_CE: find(strikes[index + 3], 'CE'), UP3_PE: find(strikes[index + 3], 'PE') };
  return { expiryDate, expiry: expiryContracts[0].expiry, strikes, atm, byLabel };
}
function assessCoverage(surface: ReturnType<typeof chooseSurface>, timestamp: Date, date: string) { if (!surface) return { status: 'METADATA_UNAVAILABLE', required: [], availableLegs: 0, completeLegs: 0, sparseLegs: 0, missingLegs: 14, symmetricWing: false, expiryDate: null, strikeSpacing: [] as number[] }; const required = Object.values(surface.byLabel).filter((value): value is Contract => !!value); const observations = required.map((contract) => ({ contract, row: contract.rows.find((row) => row.candleTime.getTime() === timestamp.getTime()), complete: complete(contract.rows, date) })); const availableLegs = observations.filter((value) => !!value.row).length; const completeLegs = observations.filter((value) => !!value.row && value.complete).length; const sparseLegs = observations.filter((value) => !!value.row && !value.complete).length; return { status: 'OK', required, availableLegs, completeLegs, sparseLegs, missingLegs: 14 - availableLegs, symmetricWing: !!surface.byLabel.DOWN1_PE && !!surface.byLabel.UP1_CE && !!surface.byLabel.ATM_CE && !!surface.byLabel.ATM_PE, expiryDate: surface.expiryDate, strikeSpacing: surface.strikes.slice(1).map((strike, index) => strike - surface.strikes[index]) }; }
function calculateIvSurface(surface: NonNullable<ReturnType<typeof chooseSurface>>, spot: number, premiumAt: Date) { const values: any[] = []; const byLabel = new Map<string, number>(); Object.entries(surface.byLabel).forEach(([label, contract]) => { if (!contract) { values.push({ label, status: 'MISSING_CONTRACT' }); return; } const row = contract.rows.find((candle) => candle.candleTime.getTime() === premiumAt.getTime()); if (!row || Number(row.close) <= 0) { values.push({ label, status: 'MISSING_PREMIUM', instrumentKey: contract.instrumentKey }); return; } const result = solveEuropeanImpliedVolatility({ optionType: contract.optionType, spot, strike: contract.strike, premium: Number(row.close), timeToExpiryYears: (expiryClose(contract.expiryDate).getTime() - premiumAt.getTime()) / (365 * 24 * 60 * 60_000), riskFreeRate: RATE, dividendYield: DIVIDEND }); values.push({ label, instrumentKey: contract.instrumentKey, optionType: contract.optionType, strike: contract.strike, expiryDate: contract.expiryDate, premium: Number(row.close), ...result }); if (result.converged && result.impliedVolatility !== null) byLabel.set(label, result.impliedVolatility); }); return { values, byLabel }; }
function features(surface: NonNullable<ReturnType<typeof chooseSurface>>, values: ReadonlyMap<string, number>, spot: number, observedAt: Date, premiumAt: Date, spotAt: (timestamp: Date) => number | undefined) { const atmCe = values.get('ATM_CE'); const atmPe = values.get('ATM_PE'); const down = values.get('DOWN1_PE'); const up = values.get('UP1_CE'); if ([atmCe, atmPe, down, up].some((value) => value === undefined)) return { atmIvAvailable: false, downsideSkewAvailable: false, upsideSkewAvailable: false, riskReversalAvailable: false, slopeAvailable: false, delta1mAvailable: false, delta3mAvailable: false, delta5mAvailable: false }; const atm = (atmCe! + atmPe!) / 2; const current = { atm, downside: down! - atm, upside: up! - atm, rr: up! - down!, slope: (up! - down!) / Math.max(1e-9, (surface.byLabel.UP1_CE!.strike - surface.byLabel.DOWN1_PE!.strike) / spot) }; const delta = (minutes: number) => { const priorAt = new Date(premiumAt.getTime() - minutes * 60_000); const priorSpot = spotAt(priorAt); if (!priorSpot) return null; const prior = calculateIvSurface(surface, priorSpot, priorAt).byLabel; const priorAtmCe = prior.get('ATM_CE'); const priorAtmPe = prior.get('ATM_PE'); const priorDown = prior.get('DOWN1_PE'); const priorUp = prior.get('UP1_CE'); return [priorAtmCe, priorAtmPe, priorDown, priorUp].some((value) => value === undefined) ? null : current.rr - (priorUp! - priorDown!); }; return { atmIvAvailable: true, downsideSkewAvailable: true, upsideSkewAvailable: true, riskReversalAvailable: true, slopeAvailable: true, delta1mAvailable: delta(1) !== null, delta3mAvailable: delta(3) !== null, delta5mAvailable: delta(5) !== null, atmIv: atm, downsideSkew: current.downside, upsideSkew: current.upside, riskReversal: current.rr, skewSlope: current.slope, observationTimestamp: observedAt.toISOString() }; }
function coverageSummary(rows: readonly any[], contractsByDate: ReadonlyMap<string, Contract[]>, required: ReadonlySet<string>) { const statuses = rows.filter((row) => row.status === 'OK'); const expectedLegs = rows.length * 14; const available = statuses.reduce((sum, row) => sum + row.availableLegs, 0); const completeLegs = statuses.reduce((sum, row) => sum + row.completeLegs, 0); const sparse = statuses.reduce((sum, row) => sum + row.sparseLegs, 0); const expiry = [...new Set(statuses.map((row) => row.expiryDate).filter(Boolean))]; const spacing = statuses.flatMap((row) => row.strikeSpacing); const completeSessions = [...required].filter((key) => { const boundary = key.lastIndexOf('|'); const instrumentKey = key.slice(0, boundary); const date = key.slice(boundary + 1); return contractsByDate.get(date)?.find((contract) => contract.instrumentKey === instrumentKey && complete(contract.rows, date)); }).length; return { sessionsAudited: new Set(rows.map((row) => row.date)).size, observationsAudited: rows.length, expiriesRepresented: expiry, strikeSpacingObserved: summaryNumbers(spacing), requiredInstrumentDateSessions: required.size, completeLocalSessions: completeSessions, usableSparseSessions: Math.max(0, available - completeLegs), missingLocalSessions: Math.max(0, required.size - completeSessions), metadataUnavailableObservations: rows.filter((row) => row.status !== 'OK').length, expectedLegSlots: expectedLegs, locallyObservableLegs: available, CEcoveragePercent: percent(rows, 'CE'), PEcoveragePercent: percent(rows, 'PE'), symmetricWingCoveragePercent: rows.length ? rows.filter((row) => row.symmetricWing).length / rows.length * 100 : 0, enoughForSkewCalculation: rows.length > 0 && rows.filter((row) => row.symmetricWing).length / rows.length >= .8, persistedMetadataLimitation: 'HistoricalOptionCandle stores metadata only for previously cached contracts; it is not a complete expired-option chain.' }; }
function ivQuality(values: readonly any[]) { const attempted = values.filter((value) => value.status === undefined).length; const converged = values.filter((value) => value.converged).length; const failures = Object.fromEntries(['INVALID_INPUT', 'EXPIRED', 'ARBITRAGE_BOUND', 'NON_CONVERGENT', 'MISSING_PREMIUM', 'MISSING_CONTRACT'].map((reason) => [reason, values.filter((value) => value.failureReason === reason || value.status === reason).length])); const ivs = values.filter((value) => value.converged).map((value) => value.impliedVolatility as number); return { attemptedCalculations: attempted, converged, convergencePercent: attempted ? converged / attempted * 100 : 0, failures, ivDistribution: summaryNumbers(ivs), suspiciousIvCount: ivs.filter((iv) => iv < .01 || iv > 3).length, suspiciousDefinition: 'IV <1% or >300% annualized is flagged; not silently removed.' }; }
function featureSummary(features: readonly any[], snapshots: readonly any[]) { const count = (key: string) => features.filter((row) => row[key] === true).length; return { snapshotsAssessed: snapshots.length, atmIv: { available: count('atmIvAvailable'), percent: percentOf(count('atmIvAvailable'), snapshots.length) }, downsideSkew: { available: count('downsideSkewAvailable'), percent: percentOf(count('downsideSkewAvailable'), snapshots.length) }, upsideSkew: { available: count('upsideSkewAvailable'), percent: percentOf(count('upsideSkewAvailable'), snapshots.length) }, riskReversal: { available: count('riskReversalAvailable'), percent: percentOf(count('riskReversalAvailable'), snapshots.length), rule: 'ATM CE/PE, DOWN1 PE, and UP1 CE must share one expiry.' }, causalFeatureChanges: { delta1m: { available: count('delta1mAvailable'), percent: percentOf(count('delta1mAvailable'), snapshots.length) }, delta3m: { available: count('delta3mAvailable'), percent: percentOf(count('delta3mAvailable'), snapshots.length) }, delta5m: { available: count('delta5mAvailable'), percent: percentOf(count('delta5mAvailable'), snapshots.length) }, noForwardFill: true, noCrossSessionCarry: true } }; }
function decide(coverage: any, quality: any, features: any) { if (quality.convergencePercent < 80 || features.riskReversal.percent < 60 || coverage.metadataUnavailableObservations > 0) return 'READY_AFTER_OPTION_DATA_PREP'; if (!coverage.enoughForSkewCalculation) return 'IV_DATA_NOT_RELIABLE_ENOUGH'; return 'READY_FOR_V11_SIGNAL_RESEARCH'; }
function isNiftyOption(row: OptionRow) { const symbol = row.tradingSymbol?.toUpperCase() ?? ''; return symbol.includes('NIFTY') && !symbol.includes('BANK'); } function isType(value: string | null): value is Type { return value === 'CE' || value === 'PE'; }
function expiryClose(date: string) { return new Date(`${date}T15:30:00+05:30`); } function istTimestamp(date: string, time: string) { return new Date(`${date}T${time}:00+05:30`); } function istDate(value: Date) { const parts = Object.fromEntries(new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Kolkata', year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(value).map((part) => [part.type, part.value])); return `${parts.year}-${parts.month}-${parts.day}`; } function formatIst(value: Date) { return new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Kolkata', dateStyle: 'short', timeStyle: 'short', hourCycle: 'h23' }).format(value); }
function complete(rows: readonly OptionRow[], date: string) { const sorted = [...rows].sort((left, right) => left.candleTime.getTime() - right.candleTime.getTime()); const start = new Date(`${date}T09:15:00+05:30`).getTime(); const end = new Date(`${date}T15:29:00+05:30`).getTime(); return sorted.length === 375 && sorted[0]?.candleTime.getTime() === start && sorted.at(-1)?.candleTime.getTime() === end && sorted.every((row, index) => index === 0 || row.candleTime.getTime() - sorted[index - 1].candleTime.getTime() === 60_000); }
function summaryNumbers(values: readonly number[]) { if (!values.length) return { count: 0, min: null, median: null, p95: null, max: null }; const sorted = [...values].sort((left, right) => left - right); return { count: values.length, min: sorted[0], median: sorted[Math.floor((sorted.length - 1) * .5)], p95: sorted[Math.floor((sorted.length - 1) * .95)], max: sorted.at(-1) }; } function percent(rows: readonly any[], type: Type) { const eligible = rows.filter((row) => row.status === 'OK'); return eligible.length ? eligible.filter((row) => type === 'CE' ? row.ceLegPresent : row.peLegPresent).length / eligible.length * 100 : 0; } function percentOf(value: number, total: number) { return total ? value / total * 100 : 0; } function write(name: string, value: unknown) { writeFileSync(resolve(DIRECTORY, name), `${JSON.stringify(value, null, 2)}\n`); }
void run().catch((error) => { console.error('V11 phase-0 audit failed:', error instanceof Error ? error.stack ?? error.message : String(error)); process.exitCode = 1; });
