import 'dotenv/config';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import HistoricalOptionCandleRepository from '../modules/options/repositories/historical-option-candle.repository';
import OptionPremiumPathAnalysisService from '../modules/options/services/option-premium-path-analysis.service';
import { OptionExitPolicyEvaluationResult } from '../modules/options/dto/option-exit-policy.dto';
import { deflatedSharpeRatio, simplifiedPbo } from '../modules/research-validation';
import { BN_V1_STRATEGY_ID } from '../modules/research/banknifty-v1-opening-range-retest';

const DIRECTORY = 'artifacts/banknifty-v1-opening-range-retest';
const POLICIES = [{ target: 4, stop: 4, hold: 10 }, { target: 4, stop: 4, hold: 15 }, { target: 4, stop: 4, hold: 20 }, { target: 5, stop: 5, hold: 10 }, { target: 5, stop: 5, hold: 15 }, { target: 5, stop: 5, hold: 20 }, { target: 6, stop: 5, hold: 10 }, { target: 6, stop: 5, hold: 15 }, { target: 6, stop: 5, hold: 20 }] as const;
const COSTS = [0.2, 0.4, 0.6, 0.8, 1] as const;
type Policy = typeof POLICIES[number];
type Signal = { date: string; timestamp: string; direction: 'CE' | 'PE'; openingRange: string; breakoutTimestamp: string; };
type Entry = { configKey: string; config: Record<string, unknown>; signalCount: number; signalsPerSession: number; signals: Signal[] };
type DirectionSummary = { signals: number; settledTrades: number; unavailableTrades: number; grossAverage: number; grossMedian: number; netAt040: number; netAt060: number; targetRate: number; stopRate: number; timeoutRate: number; profitableDayPercent: number; maxLosingStreak: number; trainNetAt040: number; validationNetAt040: number; };
type Candidate = { id: string; configKey: string; config: Record<string, unknown>; policy: Policy; totalSignals: number; resolvedTrades: number; settledTrades: number; unavailableTrades: number; targetCount: number; stopCount: number; timeoutCount: number; ambiguousCount: number; grossAverage: number; grossMedian: number; netAt020: number; netAt040: number; netAt060: number; netAt080: number; netAt100: number; targetRate: number; stopRate: number; timeoutRate: number; ambiguousRate: number; unavailableRate: number; profitableDayPercent: number; maxDrawdown: number; maxLosingStreak: number; dailyNet40: number[]; train: Summary; validation: Summary; monthly: Record<string, Summary>; ceTrades: number; peTrades: number; ce: DirectionSummary; pe: DirectionSummary; };
type Summary = { signals: number; resolvedTrades: number; settledTrades: number; unavailableTrades: number; grossAverage: number; grossMedian: number; netAt040: number; targetRate: number; stopRate: number; timeoutRate: number; ambiguousRate: number; unavailableRate: number; };

async function run(): Promise<void> {
  if (process.env.RESEARCH_LOCAL_ONLY !== 'true') throw new Error('BN_V1 outcomes require RESEARCH_LOCAL_ONLY=true.');
  const shards = await Promise.all([0, 1, 2, 3].map((index) => readFile(`${DIRECTORY}/phase-1-shard-${index}.json`, 'utf8').then(JSON.parse)));
  const entries: Entry[] = shards.flatMap((shard) => shard.shardResults);
  if (entries.length !== 7776) throw new Error(`Expected 7776 frozen configurations, found ${entries.length}.`);
  const eligible = JSON.parse(await readFile('artifacts/banknifty-option-prep/research-session-eligibility.json', 'utf8'));
  const dates: string[] = eligible.eligibleDates.slice().sort();
  const policy = eligible.proposedSplit.policy;
  const trainDates = dates.slice(0, policy.train);
  const validationDates = dates.slice(policy.train + policy.embargo1, policy.train + policy.embargo1 + policy.validation);
  const allowed = new Set([...trainDates, ...validationDates]);
  (globalThis as any).__bnDates = dates;
  (globalThis as any).__bnPolicy = policy;
  const split = (date: string) => trainDates.includes(date) ? 'TRAIN' : validationDates.includes(date) ? 'VALIDATION' : 'EXCLUDED';
  const requirements: any[] = (JSON.parse(await readFile('artifacts/banknifty-option-prep/required-option-universe.json', 'utf8')).requirements as any[]).filter((item: any) => item.offset === 'ATM');
  const requirementByKey = new Map(requirements.map((item: any) => [`${item.direction}|${item.tradingDate}`, item]));
  const optionRepository = new HistoricalOptionCandleRepository();
  const localRows = await optionRepository.findByInstrumentDateSessions(requirements.map((item: any) => ({ instrumentKey: item.instrumentKey, tradingDate: item.tradingDate })), '1minute');
  const candlesByKey = new Map<string, any[]>();
  localRows.forEach((row) => { const key = `${row.instrumentKey}|${istDate(row.candleTime)}`; candlesByKey.set(key, [...(candlesByKey.get(key) ?? []), { instrumentKey: row.instrumentKey, candleTime: row.candleTime, open: Number(row.open), high: Number(row.high), low: Number(row.low), close: Number(row.close), volume: row.volume, openInterest: row.openInterest ?? undefined }]); });
  const statusByKey = new Map<string, string>();
  requirements.forEach((item: any) => { const key = `${item.instrumentKey}|${item.tradingDate}`; const rows = candlesByKey.get(key) ?? []; statusByKey.set(`${item.direction}|${item.tradingDate}`, rows.length === 375 ? 'COMPLETE' : rows.length > 0 ? 'USABLE_SPARSE' : 'UNAVAILABLE'); });
  const signalsByConfig = new Map<string, Signal[]>();
  entries.forEach((entry) => signalsByConfig.set(entry.configKey, entry.signals.filter((signal) => allowed.has(signal.date))));
  const resolutions = new Map<string, Map<string, OptionExitPolicyEvaluationResult>>();
  const allSignals = [...new Map(entries.flatMap((entry) => entry.signals).filter((signal) => allowed.has(signal.date)).map((signal) => [`${signal.direction}|${signal.date}|${signal.timestamp}`, signal])).values()];
  allSignals.forEach((signal) => { const requirement = requirementByKey.get(`${signal.direction}|${signal.date}`); const rows = requirement ? candlesByKey.get(`${requirement.instrumentKey}|${signal.date}`) ?? [] : []; const key = `${signal.direction}|${signal.date}|${signal.timestamp}`; const exits = new Map<string, OptionExitPolicyEvaluationResult>(); POLICIES.forEach((policy) => { if (!rows.length) { exits.set(policyKey(policy), unavailable(signal, policy)); return; } try { exits.set(policyKey(policy), new OptionPremiumPathAnalysisService(new Date(signal.timestamp), rows).evaluate({ type: 'TARGET_STOP', targetPercent: policy.target, stopLossPercent: policy.stop, maximumHoldingMinutes: policy.hold })); } catch { exits.set(policyKey(policy), unavailable(signal, policy)); } }); resolutions.set(key, exits); });
  const candidates: Candidate[] = [];
  entries.forEach((entry) => POLICIES.forEach((policy) => candidates.push(metric(entry, policy, signalsByConfig.get(entry.configKey) ?? [], resolutions, dates, split))));
  const groups = groupCandidates(candidates);
  const directionGroups = { CE: directionGroup(candidates, 'ce'), PE: directionGroup(candidates, 'pe') };
  const entryByKey = new Map(entries.map((entry) => [entry.configKey, entry]));
  [...Object.values(groups), ...Object.values(directionGroups).flatMap((group) => Object.values(group))].forEach((candidate: any) => { if (candidate) candidate.monthly = monthlyForCandidate(candidate, entryByKey, resolutions); });
  const tiers = frequencyTiers(candidates);
  const family = familyAnalysis(candidates);
  const multipleTesting = multipleTestingDiagnostics(candidates);
  const walkForward = walkForwardDiagnostics(candidates, dates, split);
  const verdict = finalVerdict(groups, multipleTesting);
  const coverage = { requiredInstrumentDateSessions: requirements.length, complete: [...statusByKey.values()].filter((value) => value === 'COMPLETE').length, usableSparse: [...statusByKey.values()].filter((value) => value === 'USABLE_SPARSE').length, unavailable: [...statusByKey.values()].filter((value) => value === 'UNAVAILABLE').length, optionDownloads: 0, dbFallbackHits: 0 };
  const serializedGroups = Object.fromEntries(Object.entries(groups).map(([name, candidate]) => [name, candidate ? serializeCandidate(candidate) : null]));
  const serializedDirectionGroups = Object.fromEntries(Object.entries(directionGroups).map(([direction, group]) => [direction, Object.fromEntries(Object.entries(group).map(([name, candidate]) => [name, candidate ? serializeDirectionCandidate(candidate, direction as 'CE' | 'PE') : null]))]));
  const validationReport = { mode: 'TRAIN_VALIDATION_ONLY', finalHoldoutAccessed: false, train: trainDates, validation: validationDates, walkForward, multipleTesting, groups: serializedGroups, directionGroups: serializedDirectionGroups, verdict };
  const summary = { strategyId: BN_V1_STRATEGY_ID, phase: 'PHASE_2_OUTCOME_RESEARCH', scope: { underlying: 'NSE_INDEX|Nifty Bank', eligibleSessions: dates.length, evaluatedSessions: allowed.size, trainSessions: trainDates.length, validationSessions: validationDates.length, excluded: 'EMBARGO_1, EMBARGO_2, LEGACY_CONTAMINATED_HOLDOUT' }, configurations: entries.length, policiesPerConfiguration: POLICIES.length, totalPolicyEvaluations: candidates.length, coverage, groups: serializedGroups, directionGroups: serializedDirectionGroups, frequencyTiers: tiers, parameterFamilies: family, walkForward, multipleTesting, verdict, promotion: { shadowRecommendationOnly: true, paperOrLiveIntegration: false } };
  await mkdir(DIRECTORY, { recursive: true });
  await writeFile(`${DIRECTORY}/top-candidates.json`, JSON.stringify({ groups: serializedGroups, directionGroups: serializedDirectionGroups, frequencyTiers: tiers, parameterFamilies: family }, null, 2));
  await writeFile(`${DIRECTORY}/validation-report.json`, JSON.stringify(validationReport, null, 2));
  await writeFile(`${DIRECTORY}/outcome-summary.json`, JSON.stringify(summary, null, 2));
  console.log(JSON.stringify({ ...summary, topCandidates: serializedGroups }, null, 2));
}

function metric(entry: Entry, policy: Policy, signals: readonly Signal[], resolutions: ReadonlyMap<string, ReadonlyMap<string, OptionExitPolicyEvaluationResult>>, dates: readonly string[], split: (date: string) => string): Candidate { const records = signals.map((signal) => ({ signal, exit: resolutions.get(`${signal.direction}|${signal.date}|${signal.timestamp}`)?.get(policyKey(policy)) ?? unavailable(signal, policy) })); const settled = records.filter((record) => !record.exit.ambiguous && !record.exit.unavailable && record.exit.premiumChangePercent !== null); const returns = settled.map((record) => record.exit.premiumChangePercent!); const daily = dates.map(() => 0); const counts = dates.map(() => 0); const dateIndex = new Map(dates.map((date, index) => [date, index])); settled.forEach((record) => { const index = dateIndex.get(record.signal.date); if (index !== undefined) { daily[index] += record.exit.premiumChangePercent!; counts[index] += 1; } }); const train = subset(records, 'TRAIN'); const validation = subset(records, 'VALIDATION'); const targetCount = settled.filter((record) => record.exit.exitReason === 'TARGET').length; const stopCount = settled.filter((record) => record.exit.exitReason === 'STOP_LOSS').length; const timeoutCount = settled.filter((record) => record.exit.exitReason === 'TIME_EXIT').length; const ambiguousCount = records.filter((record) => record.exit.ambiguous).length; const unavailableCount = records.filter((record) => record.exit.unavailable).length; const dayNet40 = daily.map((value, index) => counts[index] ? value - .4 * counts[index] : 0); return { id: `${entry.configKey}|${policyKey(policy)}`, configKey: entry.configKey, config: entry.config, policy, totalSignals: records.length, resolvedTrades: records.length - unavailableCount, settledTrades: settled.length, unavailableTrades: unavailableCount, targetCount, stopCount, timeoutCount, ambiguousCount, grossAverage: average(returns), grossMedian: median(returns), netAt020: returns.length ? average(returns) - .2 : 0, netAt040: returns.length ? average(returns) - .4 : 0, netAt060: returns.length ? average(returns) - .6 : 0, netAt080: returns.length ? average(returns) - .8 : 0, netAt100: returns.length ? average(returns) - 1 : 0, targetRate: rate(targetCount, settled.length), stopRate: rate(stopCount, settled.length), timeoutRate: rate(timeoutCount, settled.length), ambiguousRate: rate(ambiguousCount, records.length), unavailableRate: rate(unavailableCount, records.length), profitableDayPercent: profitableDayPercent(daily), maxDrawdown: maxDrawdown(returns), maxLosingStreak: streak(returns), dailyNet40: dayNet40, train, validation, monthly: {}, ceTrades: settled.filter((record) => record.signal.direction === 'CE').length, peTrades: settled.filter((record) => record.signal.direction === 'PE').length, ce: directionSummary(records, 'CE'), pe: directionSummary(records, 'PE') }; }
function subset(records: readonly any[], wanted: string): Summary { const filtered = records.filter((record) => wanted === splitFor(record.signal.date)); const settled = filtered.filter((record) => !record.exit.ambiguous && !record.exit.unavailable && record.exit.premiumChangePercent !== null); const returns = settled.map((record) => record.exit.premiumChangePercent!); const target = settled.filter((record) => record.exit.exitReason === 'TARGET').length; const stop = settled.filter((record) => record.exit.exitReason === 'STOP_LOSS').length; return { signals: filtered.length, resolvedTrades: filtered.filter((record) => !record.exit.unavailable).length, settledTrades: settled.length, unavailableTrades: filtered.filter((record) => record.exit.unavailable).length, grossAverage: average(returns), grossMedian: median(returns), netAt040: returns.length ? average(returns) - .4 : 0, targetRate: rate(target, settled.length), stopRate: rate(stop, settled.length), timeoutRate: rate(settled.filter((record) => record.exit.exitReason === 'TIME_EXIT').length, settled.length), ambiguousRate: rate(filtered.filter((record) => record.exit.ambiguous).length, filtered.length), unavailableRate: rate(filtered.filter((record) => record.exit.unavailable).length, filtered.length) }; }
// Split assignment is fixed by the prepared eligible-date manifest.
function splitFor(date: string): string { const dates = (globalThis as any).__bnDates as string[] | undefined; const policy = (globalThis as any).__bnPolicy as any | undefined; if (!dates || !policy) return date <= '2026-05-25' ? 'TRAIN' : date <= '2026-06-29' ? 'VALIDATION' : 'EXCLUDED'; const index = dates.indexOf(date); return index < policy.train ? 'TRAIN' : index < policy.train + policy.embargo1 ? 'EMBARGO' : index < policy.train + policy.embargo1 + policy.validation ? 'VALIDATION' : 'EXCLUDED'; }
function monthly(records: readonly any[]): Record<string, Summary> { const groups = new Map<string, any[]>(); records.forEach((record) => { const month = record.signal.date.slice(0, 7); groups.set(month, [...(groups.get(month) ?? []), record]); }); return Object.fromEntries([...groups].map(([month, values]) => [month, subsetLocal(values)])); }
function subsetLocal(records: readonly any[]): Summary { const settled = records.filter((record) => !record.exit.ambiguous && !record.exit.unavailable && record.exit.premiumChangePercent !== null); const returns = settled.map((record) => record.exit.premiumChangePercent!); return { signals: records.length, resolvedTrades: records.filter((record) => !record.exit.unavailable).length, settledTrades: settled.length, unavailableTrades: records.filter((record) => record.exit.unavailable).length, grossAverage: average(returns), grossMedian: median(returns), netAt040: returns.length ? average(returns) - .4 : 0, targetRate: rate(settled.filter((r) => r.exit.exitReason === 'TARGET').length, settled.length), stopRate: rate(settled.filter((r) => r.exit.exitReason === 'STOP_LOSS').length, settled.length), timeoutRate: rate(settled.filter((r) => r.exit.exitReason === 'TIME_EXIT').length, settled.length), ambiguousRate: rate(records.filter((r) => r.exit.ambiguous).length, records.length), unavailableRate: rate(records.filter((r) => r.exit.unavailable).length, records.length) }; }
function directionSummary(records: readonly any[], direction: 'CE' | 'PE'): DirectionSummary { const selected = records.filter((record) => record.signal.direction === direction); const settled = selected.filter((record) => !record.exit.ambiguous && !record.exit.unavailable && record.exit.premiumChangePercent !== null); const returns = settled.map((record) => record.exit.premiumChangePercent!); const daily = new Map<string, number>(); settled.forEach((record) => daily.set(record.signal.date, (daily.get(record.signal.date) ?? 0) + record.exit.premiumChangePercent!)); const splitNet = (name: string) => { const values = settled.filter((record) => splitFor(record.signal.date) === name).map((record) => record.exit.premiumChangePercent!); return values.length ? average(values) - .4 : 0; }; return { signals: selected.length, settledTrades: settled.length, unavailableTrades: selected.filter((record) => record.exit.unavailable).length, grossAverage: average(returns), grossMedian: median(returns), netAt040: returns.length ? average(returns) - .4 : 0, netAt060: returns.length ? average(returns) - .6 : 0, targetRate: rate(settled.filter((record) => record.exit.exitReason === 'TARGET').length, settled.length), stopRate: rate(settled.filter((record) => record.exit.exitReason === 'STOP_LOSS').length, settled.length), timeoutRate: rate(settled.filter((record) => record.exit.exitReason === 'TIME_EXIT').length, settled.length), profitableDayPercent: profitableDayPercent([...daily.values()]), maxLosingStreak: streak(returns), trainNetAt040: splitNet('TRAIN'), validationNetAt040: splitNet('VALIDATION') }; }
function directionGroup(metrics: readonly Candidate[], direction: 'ce' | 'pe') { const quality = metrics.filter((metric) => metric[direction].settledTrades >= 20); const rank = (a: Candidate, b: Candidate) => b[direction].netAt040 - a[direction].netAt040 || b[direction].grossMedian - a[direction].grossMedian || b[direction].settledTrades - a[direction].settledTrades; const freq = [...metrics].sort((a, b) => b[direction].settledTrades - a[direction].settledTrades); const balanced = [...quality].sort((a, b) => rank(a, b)); const robust = [...quality].sort((a, b) => b[direction].netAt060 - a[direction].netAt060 || rank(a, b)); return { highestFrequency: freq[0], highestQuality: [...quality].sort(rank)[0], bestBalanced: balanced[0], bestCostRobustness: robust[0] }; }
function serializeDirectionCandidate(candidate: Candidate, direction: 'CE' | 'PE') { const key = direction === 'CE' ? 'ce' : 'pe'; return { id: candidate.id, configKey: candidate.configKey, config: candidate.config, policy: candidate.policy, direction, ...candidate[key], totalSignals: candidate[key].signals, resolvedTrades: candidate[key].settledTrades + candidate[key].unavailableTrades, netAt020: candidate[key].grossAverage ? candidate[key].grossAverage - .2 : 0, netAt080: candidate[key].grossAverage ? candidate[key].grossAverage - .8 : 0, netAt100: candidate[key].grossAverage ? candidate[key].grossAverage - 1 : 0, monthly: candidate.monthly }; }
function monthlyForCandidate(candidate: Candidate, entries: Map<string, Entry>, resolutions: ReadonlyMap<string, ReadonlyMap<string, OptionExitPolicyEvaluationResult>>) { const entry = entries.get(candidate.configKey); if (!entry) return {}; const records = entry.signals.filter((signal) => allowedDate(signal.date)).map((signal) => ({ signal, exit: resolutions.get(`${signal.direction}|${signal.date}|${signal.timestamp}`)?.get(policyKey(candidate.policy)) ?? unavailable(signal, candidate.policy) })); return monthly(records); }
function allowedDate(date: string) { return splitFor(date) === 'TRAIN' || splitFor(date) === 'VALIDATION'; }
function groupCandidates(metrics: readonly Candidate[]) { const quality = metrics.filter((metric) => metric.settledTrades >= 30); const rank = [...quality].sort((a, b) => b.netAt040 - a.netAt040 || b.grossMedian - a.grossMedian || b.validation.netAt040 - a.validation.netAt040 || b.settledTrades - a.settledTrades); const freq = [...metrics].sort((a, b) => b.settledTrades - a.settledTrades); const balanced = [...quality].sort((a, b) => (b.netAt040 + b.validation.netAt040 + b.grossMedian) - (a.netAt040 + a.validation.netAt040 + a.grossMedian) || b.settledTrades - a.settledTrades); const stable = [...quality].sort((a, b) => Math.abs(a.train.netAt040 - a.validation.netAt040) - Math.abs(b.train.netAt040 - b.validation.netAt040)); const robust = [...quality].sort((a, b) => b.netAt060 - a.netAt060 || b.validation.netAt040 - a.validation.netAt040); return { highestFrequency: freq[0], highestQuality: rank[0], bestBalanced: balanced[0], bestValidationStability: stable[0], bestCostRobustness: robust[0] }; }
function frequencyTiers(metrics: readonly Candidate[]) { return Object.fromEntries([.5, 1, 2, 3, 5, 8].map((tier) => { const eligible = metrics.filter((metric) => metric.resolvedTrades / 75 >= tier); const positive40 = eligible.filter((metric) => metric.netAt040 > 0); const positive60 = eligible.filter((metric) => metric.netAt060 > 0); return [String(tier), { candidateCount: eligible.length, positiveAt040: positive40.length, positiveAt060: positive60.length, bestAt040: positive40.sort((a, b) => b.netAt040 - a.netAt040)[0] ? serializeCandidate(positive40[0]) : null, bestAt060: positive60.sort((a, b) => b.netAt060 - a.netAt060)[0] ? serializeCandidate(positive60[0]) : null }]; })); }
function familyAnalysis(metrics: readonly Candidate[]) { const dimensions = ['openingRange', 'timeframe', 'breakoutBufferAtr', 'retestToleranceAtr', 'confirmationBodyAtr', 'regimeMode', 'retestExpiryBars', 'cooldownMinutes', 'target', 'stop', 'hold']; return Object.fromEntries(dimensions.map((dimension) => { const groups = new Map<string, number[]>(); metrics.forEach((metric) => { const key = dimension in metric.config ? String(metric.config[dimension]) : dimension in metric.policy ? String((metric.policy as any)[dimension]) : ''; const values = groups.get(key); if (values) values.push(metric.netAt040); else groups.set(key, [metric.netAt040]); }); return [dimension, Object.fromEntries([...groups].map(([key, values]) => [key, { count: values.length, average: average(values), median: median(values) }]))]; })); }
function walkForwardDiagnostics(metrics: readonly Candidate[], dates: readonly string[], split: (date: string) => string) { const folds = []; for (let start = 0; start + 20 <= dates.length; start += 10) { const train = dates.slice(start, start + 10); const validation = dates.slice(start + 12, start + 20); const best = metrics.filter((metric) => metric.dailyNet40.some((_, index) => train.includes(dates[index]))).sort((a, b) => b.netAt040 - a.netAt040)[0]; folds.push({ fold: folds.length + 1, trainStart: train[0], trainEnd: train.at(-1), embargo: dates.slice(start + 10, start + 12), validationStart: validation[0], validationEnd: validation.at(-1), selectedConfig: best?.id ?? null, trainNetAt040: best?.train.netAt040 ?? 0, validationNetAt040: best?.validation.netAt040 ?? 0, signConsistent: (best?.train.netAt040 ?? 0) > 0 === (best?.validation.netAt040 ?? 0) > 0 }); } return folds; }
function multipleTestingDiagnostics(metrics: readonly Candidate[]) { const best = [...metrics].sort((a, b) => b.netAt040 - a.netAt040)[0]; const trials = metrics.length; const sharpe = best ? average(best.dailyNet40) / (standardDeviation(best.dailyNet40) || 1) * Math.sqrt(75) : 0; const configurations = [...new Set(metrics.map((metric) => metric.configKey))]; const byConfig = new Map<string, Candidate>(); metrics.forEach((metric) => { if (!byConfig.has(metric.configKey)) byConfig.set(metric.configKey, metric); }); const matrix = { version: 'research-result-matrix-v1', sessions: Array.from({ length: 75 }, (_, index) => String(index)), configurations, costPercent: .4, values: Array.from({ length: 75 }, (_, row) => configurations.map((key) => byConfig.get(key)?.dailyNet40[row] ?? 0)) }; return { observedSharpeLike: sharpe, dsr: deflatedSharpeRatio({ observedSharpe: sharpe, numberOfTrials: trials, sampleLength: 75, skewness: 0, kurtosis: 3 }), simplifiedPbo: simplifiedPbo(matrix), trialCountSensitivity: [trials, 1000, 10000].map((trialCount) => ({ trialCount, dsr: deflatedSharpeRatio({ observedSharpe: sharpe, numberOfTrials: trialCount, sampleLength: 75, skewness: 0, kurtosis: 3 }) })), interpretation: best && best.validation.netAt040 <= 0 ? 'HIGH_OVERFIT_RISK' : 'MODERATE_OVERFIT_RISK' }; }
function finalVerdict(groups: any, testing: any) { const candidate = groups.bestBalanced; if (!candidate || candidate.settledTrades < 50 || candidate.netAt040 <= 0 || candidate.validation.netAt040 <= 0) return 'REJECTED'; if (testing.interpretation === 'HIGH_OVERFIT_RISK') return 'WEAK'; return candidate.netAt060 > 0 ? 'PROMISING' : 'WEAK'; }
function serializeCandidate(candidate: Candidate | undefined) { if (!candidate) return null; return { ...candidate, dailyNet40: undefined }; }
function policyKey(policy: Policy) { return `${policy.target}|${policy.stop}|${policy.hold}`; }
function unavailable(signal: Signal, policy: Policy): OptionExitPolicyEvaluationResult { return { signalTimestamp: new Date(signal.timestamp), entryPremium: 0, exitTimestamp: null, exitPremium: null, exitReason: 'UNAVAILABLE', holdingMinutes: null, premiumChange: null, premiumChangePercent: null, targetPremium: 0, stopPremium: 0, ambiguous: false, unavailable: true }; }
function istDate(date: Date) { const parts = Object.fromEntries(new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Kolkata', year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(date).map((part) => [part.type, part.value])); return `${parts.year}-${parts.month}-${parts.day}`; }
function average(values: readonly number[]) { return values.length ? values.reduce((a, b) => a + b, 0) / values.length : 0; }
function median(values: readonly number[]) { if (!values.length) return 0; const sorted = [...values].sort((a, b) => a - b); const middle = Math.floor(sorted.length / 2); return sorted.length % 2 ? sorted[middle] : (sorted[middle - 1] + sorted[middle]) / 2; }
function rate(value: number, total: number) { return total ? value / total * 100 : 0; }
function maxDrawdown(values: readonly number[]) { let equity = 0; let peak = 0; let drawdown = 0; values.forEach((value) => { equity += value; peak = Math.max(peak, equity); drawdown = Math.max(drawdown, peak - equity); }); return drawdown; }
function streak(values: readonly number[]) { let current = 0; let best = 0; values.forEach((value) => { current = value < 0 ? current + 1 : 0; best = Math.max(best, current); }); return best; }
function profitableDayPercent(values: readonly number[]) { const active = values.filter((value) => value !== 0); return rate(active.filter((value) => value > 0).length, active.length); }
function standardDeviation(values: readonly number[]) { const mean = average(values); return values.length > 1 ? Math.sqrt(values.reduce((sum, value) => sum + (value - mean) ** 2, 0) / (values.length - 1)) : 0; }

void run().catch((error) => { console.error('BANK NIFTY BN_V1 outcomes failed:', error instanceof Error ? error.message : String(error)); process.exitCode = 1; });
