import dotenv from 'dotenv';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import logger from '../core/logger/logger';
import HistoricalCandleRepository from '../modules/historical-candles/repositories/historical-candle.repository';
import CandleTimeframeAggregatorService from '../modules/indicators/services/candle-timeframe-aggregator.service';
import IndicatorEngineService from '../modules/indicators/services/indicator-engine.service';
import { Candle } from '../modules/indicators/types';
import AdaptiveMarketRegimeService from '../modules/adaptive-intraday/services/adaptive-market-regime.service';
import { AdaptivePrimaryMarketRegime } from '../modules/adaptive-intraday/types/adaptive-market-regime.types';
import UpstoxExpiredOptionClient from '../modules/options/client/upstox-expired-option.client';
import UpstoxExpiredOptionCandleClient from '../modules/options/client/upstox-expired-option-candle.client';
import HistoricalOptionCandleRepository from '../modules/options/repositories/historical-option-candle.repository';
import HistoricalOptionCandleCacheService from '../modules/options/services/historical-option-candle-cache.service';
import HistoricalOptionResearchPreloaderService from '../modules/options/services/historical-option-research-preloader.service';
import OptionContractSelectorService from '../modules/options/services/option-contract-selector.service';
import OptionPremiumPathAnalysisService from '../modules/options/services/option-premium-path-analysis.service';
import { OptionExitPolicyEvaluationResult } from '../modules/options/dto/option-exit-policy.dto';
import { OptionContract, OptionContractSelectionSignal } from '../modules/options/types';
import { StrategySignal } from '../modules/strategies/dto/strategy-signal.dto';
import { CrossSessionPreparedSession, filterCrossSessionResearchTargets, isCooldownEligible, prepareCrossSessionIndicatorWarmup } from './helpers/cross-session-indicator-warmup';
import { PreparedOptionSignalResolution, prepareOptionSignalResolution } from './helpers/prepared-option-signal-resolution';
import { SidewaysEntryFamily, matchesSidewaysOptionEntry } from './helpers/sideways-option-entry';
import { summarizeSidewaysCachePreparation } from './helpers/sideways-cache-preparation-summary';

dotenv.config(); logger.silent = true;
const underlying = 'NSE_INDEX|Nifty 50'; const timeframes = [1, 2, 3, 5] as const; const lookbacks = [4, 6, 8, 10] as const; const thresholds = [0.05, 0.10, 0.15] as const; const reclaims = [0, 0.05] as const; const cooldowns = [0, 5, 10] as const; const targetStopPairs = [[5, 5], [7.5, 5], [10, 5], [10, 7.5], [15, 7.5], [15, 10], [20, 10]] as const; const holds = [3, 5, 10, 15] as const;
type Timeframe = typeof timeframes[number]; type Direction = 'CE' | 'PE'; type Rsi = 'NO_RSI_FILTER' | 'RSI_GT_40' | 'RSI_GT_45' | 'RSI_GT_50' | 'RSI_LT_60' | 'RSI_LT_55' | 'RSI_LT_50';
interface Config { family: SidewaysEntryFamily; timeframe: Timeframe; lookback: number; threshold?: number; reclaim?: number; rsi: Rsi; cooldown: number; }
interface Signal { id: string; config: Config; date: string; timestamp: Date; spotPrice: number; direction: Direction; regimeAvailableAt: Date; }
interface Resolution { entryPremium: number; changes: Map<number, number | null>; mfe5: number | null; mae5: number | null; exits: Map<string, OptionExitPolicyEvaluationResult>; }
interface Report { config: Config; signals: Signal[]; resolved: Array<{ signal: Signal; value: Resolution }>; plus1: Metric; plus3: Metric; plus5: Metric; mfe5: number; mae5: number; policy: Policy; }
interface Metric { count: number; positivePercent: number; average: number; median: number; }
interface Policy { target: number; stop: number; hold: number; targetRate: number; stopRate: number; time: number; ambiguous: number; unavailable: number; average: number; median: number; }
const formatter = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Kolkata', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hourCycle: 'h23' });
const average = (values: readonly number[]) => values.length === 0 ? 0 : values.reduce((sum, value) => sum + value, 0) / values.length;
const median = (values: readonly number[]) => { if (values.length === 0) return 0; const sorted = [...values].sort((a, b) => a - b); const i = Math.floor(sorted.length / 2); return sorted.length % 2 ? sorted[i] : (sorted[i - 1] + sorted[i]) / 2; };
const key = (signal: Pick<Signal, 'timestamp' | 'direction'>) => `${signal.direction}|${signal.timestamp.getTime()}`;
const configKey = (config: Config) => `${config.family}|${config.timeframe}|${config.lookback}|${config.threshold ?? ''}|${config.reclaim ?? ''}|${config.rsi}|${config.cooldown}`;
const policyKey = (target: number, stop: number, hold: number) => `${target}|${stop}|${hold}`;
function ist(timestamp: Date): { date: string; minute: number } { const parts = Object.fromEntries(formatter.formatToParts(timestamp).map((part) => [part.type, part.value])); return { date: `${parts.year}-${parts.month}-${parts.day}`, minute: Number(parts.hour) * 60 + Number(parts.minute) }; }
function complete(candles: readonly Candle[]): boolean { return candles.length === 375 && candles.every((candle, index) => index === 0 || candle.timestamp.getTime() - candles[index - 1].timestamp.getTime() === 60_000); }
function parseEndDate(value: string | undefined): string | undefined { if (!value?.trim()) return undefined; if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) throw new Error('RESEARCH_END_DATE must use YYYY-MM-DD.'); return value; }
function latestRegime(session: CrossSessionPreparedSession, timestamp: Date) { return [...session.regimePoints].reverse().find((point) => point.availableAt.getTime() <= timestamp.getTime()); }
function rsiMatches(filter: Rsi, rsi: number): boolean { if (filter === 'NO_RSI_FILTER') return true; const threshold = Number(filter.slice(-2)); return filter.includes('_GT_') ? rsi > threshold : rsi < threshold; }
function direction(family: SidewaysEntryFamily): Direction { return family.endsWith('_CE') ? 'CE' : 'PE'; }
function signalType(value: Direction): OptionContractSelectionSignal { return value === 'CE' ? StrategySignal.BUY_CE : StrategySignal.BUY_PE; }
function configs(): Config[] {
  const falseConfigs = (family: 'FALSE_BREAKOUT_DOWN_CE' | 'FALSE_BREAKOUT_UP_PE', filters: readonly Rsi[]) => timeframes.flatMap((timeframe) => lookbacks.flatMap((lookback) => thresholds.flatMap((threshold) => reclaims.flatMap((reclaim) => filters.flatMap((rsi) => cooldowns.map((cooldown) => ({ family, timeframe, lookback, threshold, reclaim, rsi, cooldown })))))));
  const controls = (family: 'SUPPORT_BOUNCE_CE' | 'RESISTANCE_REJECTION_PE') => timeframes.flatMap((timeframe) => [5, 10].map((cooldown) => ({ family, timeframe, lookback: 6, rsi: 'NO_RSI_FILTER' as Rsi, cooldown })));
  return [...falseConfigs('FALSE_BREAKOUT_DOWN_CE', ['NO_RSI_FILTER', 'RSI_GT_40', 'RSI_GT_45', 'RSI_GT_50']), ...falseConfigs('FALSE_BREAKOUT_UP_PE', ['NO_RSI_FILTER', 'RSI_LT_60', 'RSI_LT_55', 'RSI_LT_50']), ...controls('SUPPORT_BOUNCE_CE'), ...controls('RESISTANCE_REJECTION_PE')];
}
function generate(session: readonly CrossSessionPreparedSession[], config: Config): Signal[] {
  const values: Signal[] = []; session.forEach((current) => { let last: number | undefined; const frame = current.frames[config.timeframe]; frame.candles.forEach((candle, index) => { if (index < config.lookback) return; const timestamp = new Date(candle.timestamp.getTime() + config.timeframe * 60_000); const regime = latestRegime(current, timestamp); if (regime?.regime !== AdaptivePrimaryMarketRegime.SIDEWAYS || regime.availableAt.getTime() > timestamp.getTime()) return; const rsi = frame.rsi14.get(candle.timestamp.getTime()); if (rsi === undefined || !rsiMatches(config.rsi, rsi)) return; const matches = matchesSidewaysOptionEntry({ family: config.family, candle, priorCandles: frame.candles.slice(index - config.lookback, index), breakThresholdPercent: config.threshold, reclaimPercent: config.reclaim, proximityPercent: 0.10 }); if (!matches || !isCooldownEligible(last, timestamp.getTime(), config.cooldown)) return; const value: Signal = { id: '', config, date: current.date, timestamp, spotPrice: candle.close, direction: direction(config.family), regimeAvailableAt: regime.availableAt }; value.id = `${configKey(config)}|${key(value)}`; values.push(value); last = timestamp.getTime(); }); }); return values;
}
async function retryMetadata<T>(create: () => Promise<T>): Promise<T> { let failure: unknown; for (let attempt = 1; attempt <= 3; attempt += 1) { try { return await create(); } catch (error) { failure = error; if (attempt < 3) await new Promise<void>((resolve) => setTimeout(resolve, attempt * 500)); } } throw failure; }
function getOrCreate<T>(cache: Map<string, Promise<T>>, cacheKey: string, create: () => Promise<T>): Promise<T> { const existing = cache.get(cacheKey); if (existing) return existing; const pending = retryMetadata(create).catch((error) => { cache.delete(cacheKey); throw error; }); cache.set(cacheKey, pending); return pending; }
function chooseExpiry(expiries: readonly string[], date: string): string { const expiry = expiries.filter((value) => value >= date).sort()[0]; if (!expiry) throw new Error(`No expired expiry exists on or after ${date}.`); return expiry; }
async function concurrent<T, R>(values: readonly T[], work: (value: T) => Promise<R>, limit = 12): Promise<R[]> { const out = new Array<R>(values.length); let next = 0; await Promise.all(Array.from({ length: Math.min(limit, values.length) }, async () => { while (next < values.length) { const index = next++; out[index] = await work(values[index]); } })); return out; }
async function prepare(signal: Signal, client: UpstoxExpiredOptionClient, selector: OptionContractSelectorService, expiryCache: Map<string, Promise<string[]>>, contractsCache: Map<string, Promise<OptionContract[]>>): Promise<PreparedOptionSignalResolution<Signal>> { const expiries = await getOrCreate(expiryCache, underlying, () => client.fetchAvailableExpiries(underlying)); const expiry = chooseExpiry(expiries, signal.date); const contracts = await getOrCreate(contractsCache, `${underlying}|${expiry}`, () => client.fetchExpiredOptionContracts(underlying, expiry)); const name = contracts[0]?.underlying; if (!name) throw new Error('Expired option contract metadata lacked its underlying.'); const selected = selector.select({ underlying: name, spotPrice: signal.spotPrice, signal: signalType(signal.direction), timestamp: signal.timestamp, contracts }); const contract = contracts.find((entry) => entry.instrumentKey === selected.instrumentKey); if (!contract) throw new Error('Selected historical ATM contract was absent.'); return prepareOptionSignalResolution(signal, contract, signal.date); }
function metric(values: readonly number[]): Metric { return { count: values.length, positivePercent: values.length === 0 ? 0 : values.filter((value) => value > 0).length / values.length * 100, average: average(values), median: median(values) }; }
function policy(records: readonly { signal: Signal; value: Resolution }[], target: number, stop: number, hold: number): Policy { const exits = records.map((record) => record.value.exits.get(policyKey(target, stop, hold))).filter((value): value is OptionExitPolicyEvaluationResult => value !== undefined); const resolved = exits.filter((exit) => !exit.unavailable && !exit.ambiguous && exit.premiumChangePercent !== null); const returns = resolved.map((exit) => exit.premiumChangePercent as number); return { target, stop, hold, targetRate: resolved.length === 0 ? 0 : exits.filter((exit) => exit.exitReason === 'TARGET').length / resolved.length * 100, stopRate: resolved.length === 0 ? 0 : exits.filter((exit) => exit.exitReason === 'STOP_LOSS').length / resolved.length * 100, time: exits.filter((exit) => exit.exitReason === 'TIME_EXIT').length, ambiguous: exits.filter((exit) => exit.ambiguous).length, unavailable: exits.filter((exit) => exit.unavailable).length, average: average(returns), median: median(returns) }; }
function report(config: Config, signals: Signal[], all: Map<string, Resolution | Error>): Report { const resolved = signals.flatMap((signal) => { const value = all.get(key(signal)); return value instanceof Error || !value ? [] : [{ signal, value }]; }); const values = (horizon: number) => resolved.map((record) => record.value.changes.get(horizon)).filter((value): value is number => value !== null && value !== undefined); const policies = targetStopPairs.flatMap(([target, stop]) => holds.map((hold) => policy(resolved, target, stop, hold))).sort((a, b) => b.targetRate - a.targetRate || a.stopRate - b.stopRate || b.average - a.average); return { config, signals, resolved, plus1: metric(values(1)), plus3: metric(values(3)), plus5: metric(values(5)), mfe5: average(resolved.map((record) => record.value.mfe5).filter((value): value is number => value !== null)), mae5: average(resolved.map((record) => record.value.mae5).filter((value): value is number => value !== null)), policy: policies[0] }; }
function fmt(config: Config): string { return `${config.family} ${config.timeframe}m lookback=${config.lookback}${config.threshold === undefined ? ' proximity=0.10%' : ` break=${config.threshold.toFixed(2)}% reclaim=${config.reclaim?.toFixed(2)}%`} ${config.rsi} cooldown=${config.cooldown}m`; }
function rank(a: Report, b: Report): number { return b.plus3.positivePercent - a.plus3.positivePercent || b.plus5.positivePercent - a.plus5.positivePercent || b.plus5.median - a.plus5.median || b.policy.targetRate - a.policy.targetRate || a.policy.stopRate - b.policy.stopRate || b.resolved.length - a.resolved.length; }
function classify(reports: readonly Report[], sessions: number): 'STRONG' | 'PROMISING' | 'WEAK' | 'REJECT' { const best = [...reports].filter((report) => report.resolved.length >= 30).sort(rank)[0]; if (!best || best.plus5.average <= 0 || best.plus5.median <= 0) return 'REJECT'; if (best.resolved.length / sessions >= 1 && best.plus3.positivePercent > 55 && best.plus5.positivePercent > 55 && best.policy.targetRate > best.policy.stopRate) return 'PROMISING'; return 'WEAK'; }

async function run(): Promise<void> {
  const started = Date.now(); const token = process.env.UPSTOX_ACCESS_TOKEN?.trim(); if (!token) throw new Error('Set UPSTOX_ACCESS_TOKEN in .env before running this research.'); const repository = new HistoricalCandleRepository(); const options = new HistoricalOptionCandleRepository(); const cache = new HistoricalOptionCandleCacheService(options, new UpstoxExpiredOptionCandleClient(token)); const preloader = new HistoricalOptionResearchPreloaderService(repository, options, cache); const optionClient = new UpstoxExpiredOptionClient(token); const selector = new OptionContractSelectorService();
  const raw = await preloader.preloadUnderlying(underlying, '1minute'); const completeSessions = [...raw.underlyingByDate.entries()].filter(([, candles]) => complete(candles)).sort(([a], [b]) => a.localeCompare(b)); const prepared = prepareCrossSessionIndicatorWarmup(completeSessions.map(([date, candles]) => ({ date, candles })), new CandleTimeframeAggregatorService(), new IndicatorEngineService(), new AdaptiveMarketRegimeService({ trendStrengthThreshold: 20, emaProximityPercent: 0.05, highVolatilityThreshold: 0.10, lowVolatilityThreshold: 0.05 })); const sessions = filterCrossSessionResearchTargets(prepared, parseEndDate(process.env.RESEARCH_END_DATE)); if (sessions.length === 0) throw new Error('No target research sessions.');
  const allConfigs = configs(); const byConfig = new Map(allConfigs.map((config) => [configKey(config), generate(sessions, config)])); const unique = [...new Map([...byConfig.values()].flat().map((signal) => [key(signal), signal])).values()]; const ce = unique.filter((signal) => signal.direction === 'CE'); const pe = unique.filter((signal) => signal.direction === 'PE'); console.log('SIDEWAYS SIGNAL PREPARATION', { targetSessions: sessions.length, configurations: allConfigs.length, uniqueSignals: unique.length, uniqueCeSignals: ce.length, uniquePeSignals: pe.length, noLookAhead: true }); const expiryCache = new Map<string, Promise<string[]>>(); const contractsCache = new Map<string, Promise<OptionContract[]>>(); const required = await concurrent(unique, (signal) => prepare(signal, optionClient, selector, expiryCache, contractsCache));
  const ceRequests = required.filter((item) => item.signal.direction === 'CE'); const peRequests = required.filter((item) => item.signal.direction === 'PE'); const inspection = await preloader.inspectLocalOptionSessions(required); const byDirection = (items: readonly PreparedOptionSignalResolution<Signal>[]) => { const keys = new Set(items.map((item) => `${item.instrumentKey}|${item.tradingDate}`)); const matching = inspection.sessions.filter((session) => keys.has(`${session.instrumentKey}|${session.tradingDate}`)); return { requiredSessions: matching.length, complete: matching.filter((session) => session.complete).length, incompleteOrOverfull: matching.filter((session) => !session.complete && session.locallyAvailableCandleCount > 0).length, missing: matching.filter((session) => session.locallyAvailableCandleCount === 0).length, missingOrIncomplete: matching.filter((session) => !session.complete) }; }; const global = summarizeSidewaysCachePreparation(ceRequests, peRequests, inspection.sessions);
  const diagnostics = { targetSessions: sessions.length, configurations: allConfigs.length, uniqueSignals: unique.length, uniqueCeSignals: ce.length, uniquePeSignals: pe.length, CE: byDirection(ceRequests), PE: byDirection(peRequests), GLOBAL: global, noLookAhead: sessions.every((session) => session.regimePoints.every((point) => point.availableAt.getTime() > 0)), optionCandleDownloads: 0 }; const manifestPath = process.env.RESEARCH_PREPARE_MANIFEST_PATH; if (manifestPath) { await mkdir(dirname(manifestPath), { recursive: true }); await writeFile(manifestPath, JSON.stringify({ scopeEndDate: process.env.RESEARCH_END_DATE, generatedAt: new Date().toISOString(), missingSessions: global.missingSessions }, null, 2)); }
  console.log('SIDEWAYS RESEARCH DATA PREPARATION DIAGNOSTICS', JSON.stringify({ ...diagnostics, manifestPath: manifestPath ?? null }));
  if (process.env.RESEARCH_PREPARE_DIAGNOSTICS === 'true') return;
  if (process.env.RESEARCH_LOCAL_ONLY === 'true' && inspection.missingLocalSessions + inspection.incompleteLocalSessions > 0) throw new Error('SIDEWAYS local option cache is incomplete; run diagnostics-only preparation and fill only its exact missing sessions.');
  await preloader.preloadOptionSessions(required); const preparedByKey = new Map(required.map((item) => [key(item.signal), item])); const resolvedValues = await concurrent<Signal, readonly [string, Resolution | Error]>(unique, async (signal) => { try { const preparedSignal = preparedByKey.get(key(signal)); if (!preparedSignal) throw new Error('Missing prepared option resolution.'); const candles = await preloader.getOptionSession({ instrumentKey: preparedSignal.instrumentKey, tradingDate: preparedSignal.tradingDate, metadata: preparedSignal.metadata }); const path = new OptionPremiumPathAnalysisService(signal.timestamp, candles); const analytics = path.researchAnalytics({ changeHorizons: [1, 3, 5], excursionHorizons: [5], upsideTargets: [], downsideStops: [] }); const exits = new Map<string, OptionExitPolicyEvaluationResult>(); targetStopPairs.forEach(([target, stop]) => holds.forEach((hold) => exits.set(policyKey(target, stop, hold), path.evaluate({ type: 'TARGET_STOP', targetPercent: target, stopLossPercent: stop, maximumHoldingMinutes: hold })))); return [key(signal), { entryPremium: analytics.entryPremium, changes: analytics.changes as Map<number, number | null>, mfe5: analytics.excursions.get(5)?.mfe ?? null, mae5: analytics.excursions.get(5)?.mae ?? null, exits }] as const; } catch (error) { return [key(signal), error instanceof Error ? error : new Error(String(error))] as const; } }); const resolutions = new Map<string, Resolution | Error>(resolvedValues); const reports = allConfigs.map((config) => report(config, byConfig.get(configKey(config)) ?? [], resolutions));
  (['FALSE_BREAKOUT_DOWN_CE', 'FALSE_BREAKOUT_UP_PE', 'SUPPORT_BOUNCE_CE', 'RESISTANCE_REJECTION_PE'] as const).forEach((family) => { const familyReports = reports.filter((item) => item.config.family === family); const quality = [...familyReports].filter((item) => item.resolved.length >= 30).sort(rank)[0]; const frequency = [...familyReports].sort((a, b) => b.resolved.length - a.resolved.length)[0]; const balanced = [...familyReports].filter((item) => item.resolved.length / sessions.length >= 1).sort(rank)[0]; console.log(`\n${family}`, { highestFrequency: frequency && fmt(frequency.config), highestQuality: quality && fmt(quality.config), bestBalanced: balanced && fmt(balanced.config), classification: classify(familyReports, sessions.length) }); }); const quality = reports.filter((item) => item.resolved.length >= 30).sort(rank); console.log('\nSIDEWAYS FAST-TRADE QUALITY RANKING', quality.slice(0, 20).map((item) => ({ config: fmt(item.config), resolved: item.resolved.length, perSession: item.resolved.length / sessions.length, plus1: item.plus1.positivePercent, plus3: item.plus3.positivePercent, plus5: item.plus5.positivePercent, avg5: item.plus5.average, median5: item.plus5.median, mfe5: item.mfe5, mae5: item.mae5, policy: item.policy }))); console.log('BEST SIDEWAYS SETUP', quality[0] && { config: fmt(quality[0].config), policy: quality[0].policy }); console.log('PERFORMANCE PROFILE', { totalDurationMs: Date.now() - started, uniqueSignals: unique.length, optionPaths: resolutions.size, preload: preloader.getStats(started) });
}
run().catch((error) => { console.error('SIDEWAYS multi-timeframe option-premium research failed.', error); process.exitCode = 1; });
