import assert from 'node:assert/strict';
import test from 'node:test';
import { blackScholesPrice, solveEuropeanImpliedVolatility } from '../modules/research/v11-nifty-iv-skew/implied-volatility';

const base = { spot: 25_000, strike: 25_000, timeToExpiryYears: 14 / 365, riskFreeRate: .06, dividendYield: 0 };
test('recovers a known CE Black-Scholes implied volatility deterministically', () => { const premium = blackScholesPrice({ ...base, optionType: 'CE', volatility: .2 }); const first = solveEuropeanImpliedVolatility({ ...base, optionType: 'CE', premium }); const second = solveEuropeanImpliedVolatility({ ...base, optionType: 'CE', premium }); assert.equal(first.converged, true); assert.ok(Math.abs(first.impliedVolatility! - .2) < 1e-5); assert.deepEqual(second, first); });
test('recovers a known PE Black-Scholes implied volatility', () => { const premium = blackScholesPrice({ ...base, optionType: 'PE', strike: 24_800, volatility: .31 }); const result = solveEuropeanImpliedVolatility({ ...base, optionType: 'PE', strike: 24_800, premium }); assert.equal(result.converged, true); assert.ok(Math.abs(result.impliedVolatility! - .31) < 1e-5); });
test('rejects invalid, expired, and no-arbitrage-violating premiums', () => { assert.equal(solveEuropeanImpliedVolatility({ ...base, optionType: 'CE', premium: 0 }).failureReason, 'INVALID_INPUT'); assert.equal(solveEuropeanImpliedVolatility({ ...base, optionType: 'PE', premium: 20, timeToExpiryYears: 0 }).failureReason, 'EXPIRED'); assert.equal(solveEuropeanImpliedVolatility({ ...base, optionType: 'CE', premium: 30_000 }).failureReason, 'ARBITRAGE_BOUND'); });
test('symmetric strike legs must have one shared expiry for risk reversal', () => { const sameExpiry = (left: string, right: string) => left === right; assert.equal(sameExpiry('2026-03-05', '2026-03-05'), true); assert.equal(sameExpiry('2026-03-05', '2026-03-12'), false); });
test('missing historical leg leaves skew delta unavailable rather than forward-filled', () => { const delta = (current?: number, prior?: number) => current === undefined || prior === undefined ? null : current - prior; assert.equal(delta(.2, undefined), null); assert.ok(Math.abs(delta(.21, .2)! - .01) < 1e-12); });
