import assert from 'node:assert/strict';
import test from 'node:test';
import { AdaptivePrimaryMarketRegime } from '../modules/adaptive-intraday/types/adaptive-market-regime.types';
import { Candle } from '../modules/indicators/types';
import { CrossSessionPreparedSession } from './helpers/cross-session-indicator-warmup';
import { assertV6NoLookAhead, createV6SidewaysConfigs, generateV6Signals, V6Indicators } from './helpers/v6-sideways-mean-reversion-signal-generation';

const start = new Date('2026-03-02T09:15:00+05:30').getTime();
function candle(index:number,open:number,high:number,low:number,close:number):Candle{return{timestamp:new Date(start+index*120000),open,high,low,close,volume:100};}
function session(candles:Candle[],regime:AdaptivePrimaryMarketRegime):CrossSessionPreparedSession{const frame={minutes:2 as const,candles,allCandles:candles,ema15:new Map<number,number>(),ema35:new Map<number,number>(),rsi14:new Map<number,number>()};return{date:'2026-03-02',oneMinute:candles,frames:{1:{...frame,minutes:1},2:frame,3:{...frame,minutes:3},5:{...frame,minutes:5}},regimePoints:[{availableAt:new Date(start),regime}],readiness:{at0915:true,at0920:true,at0930:true}};}
function context(candles:Candle[],rsi:number):ReadonlyMap<string,V6Indicators>{return new Map([['2026-03-02',{ema20:new Map(candles.map((x)=>[x.timestamp.getTime(),100])),rsi14:new Map(candles.map((x)=>[x.timestamp.getTime(),rsi])),atr14:new Map(candles.map((x)=>[x.timestamp.getTime(),1]))}]])}
function config(direction:'CE'|'PE',confirmation:'NONE'|'REVERSAL_CLOSE'|'PRIOR_HIGH_LOW_RECLAIM'|'EMA_DIRECTION_RECLAIM',cooldown:0|2|3|5|10=0){const found=createV6SidewaysConfigs().find((x)=>x.direction===direction&&x.ema20DistancePercent===.1&&x.rsiThreshold===(direction==='CE'?40:60)&&x.minimumDistanceAtr===.5&&x.confirmation===confirmation&&x.extremeLookbackBars===2&&x.cooldownMinutes===cooldown);assert.ok(found);return found;}

test('V6 bounded grid is symmetrical: 5,760 CE + 5,760 PE configurations',()=>{const configs=createV6SidewaysConfigs();assert.equal(configs.length,11520);assert.equal(configs.filter((x)=>x.direction==='CE').length,5760);assert.equal(configs.filter((x)=>x.direction==='PE').length,5760);});
test('V6 CE enters only SIDEWAYS downside EMA20/ATR/RSI extremes, on a completed 2m candle',()=>{const candles=[candle(0,100,100.2,99.8,100),candle(1,99,99.2,98.7,99)];const signals=generateV6Signals([session(candles,AdaptivePrimaryMarketRegime.SIDEWAYS)],config('CE','NONE'),context(candles,35));assert.equal(signals.length,1);assert.equal(signals[0].direction,'CE');assert.equal(signals[0].timestamp.getTime(),candles[1].timestamp.getTime()+120000);assertV6NoLookAhead(signals);});
test('V6 PE is symmetric and TREND_UP/TREND_DOWN regimes are blocked',()=>{const candles=[candle(0,100,100.2,99.8,100),candle(1,101,101.3,100.9,101)];assert.equal(generateV6Signals([session(candles,AdaptivePrimaryMarketRegime.SIDEWAYS)],config('PE','NONE'),context(candles,65)).length,1);assert.equal(generateV6Signals([session(candles,AdaptivePrimaryMarketRegime.TREND_UP)],config('PE','NONE'),context(candles,65)).length,0);assert.equal(generateV6Signals([session(candles,AdaptivePrimaryMarketRegime.TREND_DOWN)],config('PE','NONE'),context(candles,65)).length,0);});
test('V6 reversal confirmation families use current or prior completed candles only',()=>{const candles=[candle(0,100,100.1,99.9,100),candle(1,99,99.2,98.6,99),candle(2,98.8,100.4,98.7,100.3)];const input=[session(candles,AdaptivePrimaryMarketRegime.SIDEWAYS)];const values=context(candles,35);assert.equal(generateV6Signals(input,config('CE','REVERSAL_CLOSE'),values).length,1);assert.equal(generateV6Signals(input,config('CE','PRIOR_HIGH_LOW_RECLAIM'),values).length,1);assert.equal(generateV6Signals(input,config('CE','EMA_DIRECTION_RECLAIM'),values).length,1);});
test('V6 episode suppression and cooldown prevent duplicate consecutive-extreme entries',()=>{const candles=[candle(0,100,100.1,99.9,100),candle(1,99,99.2,98.7,99),candle(2,99,99.1,98.6,99),candle(3,100,100.2,99.8,100),candle(4,99,99.2,98.7,99)];const signals=generateV6Signals([session(candles,AdaptivePrimaryMarketRegime.SIDEWAYS)],config('CE','NONE',5),context(candles,35));assert.equal(signals.length,1);});
test('V6 no-look-ahead rejects a regime made available after the 2m signal timestamp',()=>{assert.throws(()=>assertV6NoLookAhead([{configKey:'x',date:'2026-03-02',timestamp:new Date(start+120000),spotPrice:100,direction:'CE',regimeAvailableAt:new Date(start+120001),entryCandleStartedAt:new Date(start),extremeCandleStartedAt:new Date(start),ema20:100,distancePercent:.1,atr14:1,distanceAtr:.5,rsi14:35,confirmation:'NONE'}]),/look-ahead/);});
