-- Durable broker-neutral execution lifecycle. No broker API integration is
-- introduced by this migration; these tables support paper execution state,
-- idempotency, and restart reconciliation.
CREATE TABLE `ExecutionOrder` (
  `executionOrderId` VARCHAR(191) NOT NULL,
  `intentId` VARCHAR(191) NOT NULL,
  `strategyId` VARCHAR(191) NOT NULL,
  `runtimeId` VARCHAR(191) NOT NULL,
  `sessionDate` VARCHAR(191) NOT NULL,
  `instrumentKey` VARCHAR(191) NOT NULL,
  `side` VARCHAR(191) NOT NULL,
  `quantity` INTEGER NOT NULL,
  `requestedPrice` DECIMAL(20, 8) NULL,
  `executionMode` VARCHAR(191) NOT NULL,
  `status` VARCHAR(191) NOT NULL,
  `cumulativeFilledQuantity` INTEGER NOT NULL DEFAULT 0,
  `cumulativeExitQuantity` INTEGER NOT NULL DEFAULT 0,
  `remainingQuantity` INTEGER NOT NULL,
  `averageFillPrice` DECIMAL(20, 8) NULL,
  `averageExitPrice` DECIMAL(20, 8) NULL,
  `correlationId` VARCHAR(191) NOT NULL,
  `version` INTEGER NOT NULL DEFAULT 0,
  `externalOrderId` VARCHAR(191) NULL,
  `paperOrderId` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `ExecutionOrder_intentId_key`(`intentId`),
  UNIQUE INDEX `ExecutionOrder_externalOrderId_key`(`externalOrderId`),
  UNIQUE INDEX `ExecutionOrder_paperOrderId_key`(`paperOrderId`),
  INDEX `ExecutionOrder_sessionDate_status_idx`(`sessionDate`, `status`),
  INDEX `ExecutionOrder_strategyId_sessionDate_idx`(`strategyId`, `sessionDate`),
  INDEX `ExecutionOrder_instrumentKey_sessionDate_idx`(`instrumentKey`, `sessionDate`),
  PRIMARY KEY (`executionOrderId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `ExecutionFill` (
  `fillId` VARCHAR(191) NOT NULL,
  `executionOrderId` VARCHAR(191) NOT NULL,
  `leg` VARCHAR(191) NOT NULL,
  `quantity` INTEGER NOT NULL,
  `price` DECIMAL(20, 8) NOT NULL,
  `timestamp` DATETIME(3) NOT NULL,
  `source` VARCHAR(191) NOT NULL,
  `quoteQuality` VARCHAR(191) NOT NULL,
  `slippage` DECIMAL(20, 8) NOT NULL,
  `correlationId` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX `ExecutionFill_executionOrderId_timestamp_idx`(`executionOrderId`, `timestamp`),
  PRIMARY KEY (`fillId`),
  CONSTRAINT `ExecutionFill_executionOrderId_fkey` FOREIGN KEY (`executionOrderId`) REFERENCES `ExecutionOrder`(`executionOrderId`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `ExecutionStateTransition` (
  `transitionId` VARCHAR(191) NOT NULL,
  `executionOrderId` VARCHAR(191) NOT NULL,
  `previousState` VARCHAR(191) NULL,
  `nextState` VARCHAR(191) NOT NULL,
  `timestamp` DATETIME(3) NOT NULL,
  `reason` VARCHAR(191) NULL,
  `correlationId` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX `ExecutionStateTransition_executionOrderId_timestamp_idx`(`executionOrderId`, `timestamp`),
  PRIMARY KEY (`transitionId`),
  CONSTRAINT `ExecutionStateTransition_executionOrderId_fkey` FOREIGN KEY (`executionOrderId`) REFERENCES `ExecutionOrder`(`executionOrderId`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `PaperPortfolioPosition` (
  `positionId` VARCHAR(191) NOT NULL,
  `executionOrderId` VARCHAR(191) NOT NULL,
  `originatingIntentId` VARCHAR(191) NOT NULL,
  `originatingOrderId` VARCHAR(191) NOT NULL,
  `strategyId` VARCHAR(191) NOT NULL,
  `sessionDate` VARCHAR(191) NOT NULL,
  `instrumentKey` VARCHAR(191) NOT NULL,
  `underlying` VARCHAR(191) NOT NULL,
  `side` VARCHAR(191) NOT NULL,
  `quantity` INTEGER NOT NULL,
  `entryTimestamp` DATETIME(3) NOT NULL,
  `entryPrice` DECIMAL(20, 8) NOT NULL,
  `currentMarkPrice` DECIMAL(20, 8) NULL,
  `realizedPnl` DECIMAL(20, 8) NOT NULL DEFAULT 0,
  `unrealizedPnl` DECIMAL(20, 8) NULL,
  `status` VARCHAR(191) NOT NULL,
  `correlationId` VARCHAR(191) NOT NULL,
  `exitTimestamp` DATETIME(3) NULL,
  `exitPrice` DECIMAL(20, 8) NULL,
  `exitReason` VARCHAR(191) NULL,
  `stateVersion` INTEGER NOT NULL DEFAULT 0,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `PaperPortfolioPosition_executionOrderId_key`(`executionOrderId`),
  UNIQUE INDEX `PaperPortfolioPosition_originatingIntentId_key`(`originatingIntentId`),
  UNIQUE INDEX `PaperPortfolioPosition_originatingOrderId_key`(`originatingOrderId`),
  INDEX `PaperPortfolioPosition_sessionDate_status_idx`(`sessionDate`, `status`),
  INDEX `PaperPortfolioPosition_strategyId_sessionDate_idx`(`strategyId`, `sessionDate`),
  INDEX `PaperPortfolioPosition_instrumentKey_sessionDate_idx`(`instrumentKey`, `sessionDate`),
  PRIMARY KEY (`positionId`),
  CONSTRAINT `PaperPortfolioPosition_executionOrderId_fkey` FOREIGN KEY (`executionOrderId`) REFERENCES `ExecutionOrder`(`executionOrderId`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `PaperPortfolioFill` (
  `paperFillId` VARCHAR(191) NOT NULL,
  `positionId` VARCHAR(191) NOT NULL,
  `executionFillId` VARCHAR(191) NOT NULL,
  `type` VARCHAR(191) NOT NULL,
  `timestamp` DATETIME(3) NOT NULL,
  `price` DECIMAL(20, 8) NOT NULL,
  `quantity` INTEGER NOT NULL,
  `source` VARCHAR(191) NOT NULL,
  `exitReason` VARCHAR(191) NULL,
  `fillQuality` VARCHAR(191) NULL,
  `slippage` DECIMAL(20, 8) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `PaperPortfolioFill_executionFillId_key`(`executionFillId`),
  INDEX `PaperPortfolioFill_positionId_timestamp_idx`(`positionId`, `timestamp`),
  PRIMARY KEY (`paperFillId`),
  CONSTRAINT `PaperPortfolioFill_positionId_fkey` FOREIGN KEY (`positionId`) REFERENCES `PaperPortfolioPosition`(`positionId`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
