import assert from 'node:assert/strict';
import test from 'node:test';
import V4MomentumShadowTrackerService, { assertV4ShadowRuntimeGuards } from './v4-momentum-shadow-tracker.service';
import { v4MomentumShadowConfig, v4MomentumShadowPolicy } from './v4-nifty-momentum-shadow-evaluator.service';
import { OptionContract } from '../../options/types';

const contract: OptionContract = { instrumentKey: 'NSE_FO|shadow', tradingSymbol: 'SHADOWPE', underlying: 'NIFTY 50', strikePrice: 25_000, expiry: new Date('2026-08-13T00:00:00+05:30'), optionType: 'PE', exchange: 'NSE', segment: 'FO' };
test('frozen V4 shadow constants preserve the researched Momentum and exit policy', () => { assert.deepEqual(v4MomentumShadowConfig, { timeframeMinutes: 3, direction: 'PE', compressionBars: 3, compressionRangeAtrMaximum: 2, bodyAtrMinimum: 1, breakoutAtr: .1, requirePrimaryRegimeAlignment: true, cooldownMinutes: 5 }); assert.deepEqual(v4MomentumShadowPolicy, { targetPercent: 5, stopLossPercent: 5, maximumHoldingMinutes: 15 }); });
test('shadow runtime guard refuses any non-shadow or non-paper-only process before market observation starts', () => { assert.throws(() => assertV4ShadowRuntimeGuards({ SHADOW_ONLY: 'false', PAPER_TRADING_ONLY: 'true' }), /SHADOW_ONLY/); assert.throws(() => assertV4ShadowRuntimeGuards({ SHADOW_ONLY: 'true', PAPER_TRADING_ONLY: 'false' }), /PAPER_TRADING_ONLY/); assert.doesNotThrow(() => assertV4ShadowRuntimeGuards({ SHADOW_ONLY: 'true', PAPER_TRADING_ONLY: 'true' })); });
test('shadow tracker tracks target, stop, and timeout without creating any order object', () => { const tracker=new V4MomentumShadowTrackerService(); const at=new Date('2026-08-12T10:00:00+05:30'); tracker.registerSignal(at,contract); assert.equal(tracker.observePremium(contract.instrumentKey,100,at).length,0); const target=tracker.observePremium(contract.instrumentKey,105,new Date(at.getTime()+60_000))[0]; assert.equal(target.exitReason,'TARGET'); assert.equal(target.grossReturnPercent,5); tracker.registerSignal(new Date(at.getTime()+20*60_000),contract); tracker.observePremium(contract.instrumentKey,100,new Date(at.getTime()+20*60_000)); const stop=tracker.observePremium(contract.instrumentKey,95,new Date(at.getTime()+21*60_000))[0]; assert.equal(stop.exitReason,'STOP_LOSS'); tracker.registerSignal(new Date(at.getTime()+40*60_000),contract); tracker.observePremium(contract.instrumentKey,100,new Date(at.getTime()+40*60_000)); const timeout=tracker.advance(new Date(at.getTime()+55*60_000))[0]; assert.equal(timeout.exitReason,'TIMEOUT'); assert.equal(tracker.getOpenCount(),0); });
test('a range crossing both frozen barriers is journaled as ambiguous without inventing a return', () => { const tracker = new V4MomentumShadowTrackerService(); const at = new Date('2026-08-12T10:00:00+05:30'); tracker.registerSignal(at, contract); tracker.observePremium(contract.instrumentKey, 100, at); const value = tracker.observeRange(contract.instrumentKey, 94, 106, new Date(at.getTime() + 60_000))[0]; assert.equal(value.exitReason, 'AMBIGUOUS'); assert.equal(value.grossReturnPercent, null); });
test('V4 EOD closes an observed shadow with existing TIMEOUT semantics and stays orderless', () => { const tracker = new V4MomentumShadowTrackerService(); const at = new Date('2026-08-12T15:25:00+05:30'); tracker.registerSignal(at, contract); tracker.observePremium(contract.instrumentKey, 100, at); const closed = tracker.closeAtSessionEnd(new Date('2026-08-12T15:30:00+05:30')); assert.equal(closed.length, 1); assert.equal(closed[0].exitReason, 'TIMEOUT'); assert.equal(closed[0].exitPremium, 100); assert.equal(tracker.getOpenCount(), 0); assert.equal(tracker.getOpenedCount(), 1); });
