import assert from 'node:assert/strict';
import test from 'node:test';
import { PDFDocument } from 'pdf-lib';
import { MAX_RAW_SOURCE_BYTES, MIN_RAW_PDF_BYTES, RawSourceContentValidationError, assertValidRawPdfBytes } from './raw-source-content-validator';
import { sha256HexOfBuffer } from './file-checksum';

/**
 * FIX-2 regression suite. Exercises the REAL production validator end to
 * end -- `pdf-lib`'s `PDFDocument.load` is never mocked here, matching task
 * section 10 ("This test must exercise the real production validator. Do
 * not mock the PDF parser in this regression test.").
 */

/**
 * An INDEPENDENTLY hand-assembled, standards-valid minimal PDF: a real
 * Catalog -> Pages -> Page object graph with a byte-accurate xref table and
 * trailer, computed here via plain string/offset arithmetic -- NOT
 * generated by `pdf-lib` or any PDF library (task section 12: "avoid a
 * circular test that proves only the library accepts its own output").
 */
function buildIndependentMinimalPdf(): Buffer {
  const header = '%PDF-1.4\n';
  const obj1 = '1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n';
  const obj2 = '2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n';
  const obj3 = '3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] /Resources << >> >>\nendobj\n';

  let body = header;
  const offsets: number[] = [0];
  for (const obj of [obj1, obj2, obj3]) {
    offsets.push(Buffer.byteLength(body, 'ascii'));
    body += obj;
  }
  const xrefOffset = Buffer.byteLength(body, 'ascii');
  const pad10 = (n: number): string => String(n).padStart(10, '0');

  let xref = 'xref\n0 4\n0000000000 65535 f \n';
  for (let i = 1; i <= 3; i += 1) xref += `${pad10(offsets[i])} 00000 n \n`;
  const trailer = `trailer\n<< /Size 4 /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;

  return Buffer.from(body + xref + trailer, 'ascii');
}

/** Secondary, non-independent valid fixture (built BY `pdf-lib` itself) -- included in addition to, never instead of, the independent fixture above. Proves ordinary real-world-generated PDFs are accepted too. */
async function buildPdfLibGeneratedPdf(): Promise<Buffer> {
  const doc = await PDFDocument.create({ updateMetadata: false });
  const page = doc.addPage([200, 200]);
  page.drawText('synthetic test document', { x: 20, y: 100 });
  return Buffer.from(await doc.save());
}

/** The EXACT critical regression class from task section 10/2: a plausible `%PDF-x.y` header, arbitrary padding, and a trailing `%%EOF` -- with NO real PDF object/xref/trailer syntax anywhere. This is precisely what FIX-1's checks (header format + min length + %%EOF presence) let through unchanged. */
function buildBareTerraFakeBytes(): Buffer {
  const header = '%PDF-1.7\n';
  const padding = 'arbitrary padding bytes that are not any kind of valid pdf object or xref structure at all, repeated. '.repeat(3);
  const eof = '\n%%EOF\n';
  return Buffer.from(header + padding + eof, 'ascii');
}

/** A variant of the Terra fake that additionally throws in fake `trailer`/`/Root` text (still no real objects behind it) -- proves the validator isn't fooled by surface-level trailer-shaped text either. */
function buildTerraFakeWithFakeTrailerBytes(): Buffer {
  const header = '%PDF-1.7\n';
  const padding = '%synthetic bounded structural test padding content\n'.repeat(4);
  const trailer = 'trailer\n<< /Root 1 0 R >>\n%%EOF\n';
  return Buffer.from(header + padding + trailer, 'ascii');
}

/** A real, otherwise-valid PDF object graph with one dictionary's content replaced by garbage -- exercises the PARSER's own rejection (not the cheap pre-checks: header/length/EOF are all still intact and valid). */
function buildCorruptedRealPdfBytes(): Buffer {
  const good = buildIndependentMinimalPdf().toString('ascii');
  const corrupted = good.replace('<< /Type /Pages /Kids [3 0 R] /Count 1 >>', '<< GARBAGE NOT A REAL DICTIONARY @@@@ >>');
  return Buffer.from(corrupted, 'ascii');
}

/** Valid `%PDF-` header and a trailing `%%EOF` marker (clearing every cheap pre-parser check) around pure random binary content -- proves the parser layer, not just the cheap framing checks, is what rejects arbitrary binary data. */
function buildBinaryGarbageWithValidFramingBytes(): Buffer {
  const header = Buffer.from('%PDF-1.7\n', 'ascii');
  const randomMiddle = Buffer.from(Array.from({ length: 200 }, () => Math.floor(Math.random() * 256)));
  const eof = Buffer.from('\n%%EOF\n', 'ascii');
  return Buffer.concat([header, randomMiddle, eof]);
}

async function expectCode(fn: () => Promise<unknown>, code: string): Promise<void> {
  try {
    await fn();
  } catch (error) {
    assert.ok(error instanceof RawSourceContentValidationError, `Expected RawSourceContentValidationError, got ${error}`);
    assert.equal((error as RawSourceContentValidationError).code, code);
    return;
  }
  assert.fail(`Expected RawSourceContentValidationError with code ${code}, but no error was thrown.`);
}

// ---- A: valid real minimal PDF ----

test('(A) an independently hand-assembled, standards-valid minimal PDF is ACCEPTED', async () => {
  await assert.doesNotReject(() => assertValidRawPdfBytes(buildIndependentMinimalPdf()));
});

test('(A, secondary) a pdf-lib-generated valid PDF is also ACCEPTED', async () => {
  const bytes = await buildPdfLibGeneratedPdf();
  await assert.doesNotReject(() => assertValidRawPdfBytes(bytes));
});

// ---- B: Terra fake -- THE required critical regression ----

test('(B/10) TRIVIAL_FAKE_REJECTED: the exact Terra fake ("%PDF-1.7" + arbitrary padding + "%%EOF", no real object graph) is REJECTED by the real production validator', async () => {
  await expectCode(() => assertValidRawPdfBytes(buildBareTerraFakeBytes()), 'PDF_PARSE_FAILED');
});

test('(B) a Terra-fake variant with fake trailer/Root text (still no real backing objects) is also REJECTED', async () => {
  await expectCode(() => assertValidRawPdfBytes(buildTerraFakeWithFakeTrailerBytes()), 'PDF_PARSE_FAILED');
});

// ---- C: header-only ----

test('(C) a header-only body is REJECTED (too short to even reach the parser)', async () => {
  await expectCode(() => assertValidRawPdfBytes(Buffer.from('%PDF-1.4\n%%EOF\n', 'ascii')), 'BODY_TOO_SHORT');
});

// ---- D: "%PDF-" garbage (bad header version format) ----

test('(D) "%PDF-" followed by arbitrary garbage (bad header version format) is REJECTED', async () => {
  const bytes = Buffer.from('%PDF-this-is-not-a-real-document padded out well past the minimum length threshold with trailing %%EOF', 'ascii');
  await expectCode(() => assertValidRawPdfBytes(bytes), 'INVALID_PDF_HEADER');
});

// ---- E: missing EOF / truncated / corrupted real PDF ----

test('(E) a well-formed header padded to a sane length but missing a trailing %%EOF marker is REJECTED before the parser runs', async () => {
  const bytes = Buffer.from('%PDF-1.4\n' + 'padding content with no eof marker at all here, repeated a few times.\n'.repeat(4), 'ascii');
  assert.ok(bytes.length >= MIN_RAW_PDF_BYTES);
  await expectCode(() => assertValidRawPdfBytes(bytes), 'MISSING_EOF_MARKER');
});

test('(E) a real PDF with valid framing (header/length/%%EOF all intact) but a corrupted internal object is REJECTED by the parser itself', async () => {
  await expectCode(() => assertValidRawPdfBytes(buildCorruptedRealPdfBytes()), 'PDF_PARSE_FAILED');
});

// ---- F/G: HTML / challenge pages ----

test('(F) an HTML page is REJECTED even though it is non-empty and could carry HTTP 200', async () => {
  await expectCode(() => assertValidRawPdfBytes(Buffer.from('<!DOCTYPE html><html><head><title>Access Denied</title></head></html>', 'ascii')), 'HTML_CHALLENGE_PAGE_DETECTED');
});

test('(G) an NSE/browser-challenge-like body is REJECTED', async () => {
  await expectCode(() => assertValidRawPdfBytes(Buffer.from('<html><body>Are you a human? Please complete the CAPTCHA.</body></html>', 'ascii')), 'HTML_CHALLENGE_PAGE_DETECTED');
});

test('an HTML body is rejected even if it happens to be long enough to otherwise pass the length check', async () => {
  const bytes = Buffer.from('<html><body>' + 'padding '.repeat(20) + '</body></html>', 'ascii');
  await expectCode(() => assertValidRawPdfBytes(bytes), 'HTML_CHALLENGE_PAGE_DETECTED');
});

// ---- H: arbitrary binary data ----

test('(H) arbitrary binary data with otherwise-valid PDF framing (header + %%EOF) is REJECTED by the real parser, not merely by the cheap framing checks', async () => {
  const bytes = buildBinaryGarbageWithValidFramingBytes();
  assert.ok(bytes.length >= MIN_RAW_PDF_BYTES);
  await expectCode(() => assertValidRawPdfBytes(bytes), 'PDF_PARSE_FAILED');
});

test('a non-PDF plain-text body is REJECTED at the cheap magic-byte check', async () => {
  const bytes = Buffer.from('just some plain text, not a pdf, padded out well past the minimum length threshold so only the missing magic bytes are at fault here', 'ascii');
  await expectCode(() => assertValidRawPdfBytes(bytes), 'NOT_A_PDF');
});

// ---- empty / oversized ----

test('an empty response is REJECTED', async () => {
  await expectCode(() => assertValidRawPdfBytes(Buffer.alloc(0)), 'EMPTY_BODY');
});

test('maximum-size protection REJECTS a body over the limit before the parser ever runs', async () => {
  const base = buildIndependentMinimalPdf();
  const oversized = Buffer.concat([base.subarray(0, base.length - 6), Buffer.alloc(MAX_RAW_SOURCE_BYTES, 0x41), Buffer.from('\n%%EOF\n')]);
  await expectCode(() => assertValidRawPdfBytes(oversized), 'RESPONSE_TOO_LARGE');
});

// ---- K/L: byte/hash immutability across validation ----

test('(K) a valid PDF is not mutated by validation -- buffer bytes are identical before and after', async () => {
  const bytes = buildIndependentMinimalPdf();
  const before = Buffer.from(bytes);
  await assertValidRawPdfBytes(bytes);
  assert.ok(bytes.equals(before), 'assertValidRawPdfBytes must not mutate the input buffer.');
});

test('(K) the Terra fake buffer is not mutated even though validation rejects it', async () => {
  const bytes = buildBareTerraFakeBytes();
  const before = Buffer.from(bytes);
  await expectCode(() => assertValidRawPdfBytes(bytes), 'PDF_PARSE_FAILED');
  assert.ok(bytes.equals(before), 'assertValidRawPdfBytes must not mutate the input buffer even on rejection.');
});

test('(L) SHA-256 computed before validation equals SHA-256 computed after validation, for an accepted document', async () => {
  const bytes = buildIndependentMinimalPdf();
  const hashBefore = sha256HexOfBuffer(bytes);
  await assertValidRawPdfBytes(bytes);
  const hashAfter = sha256HexOfBuffer(bytes);
  assert.equal(hashBefore, hashAfter);
});

// ---- zero-page document ----

test('a PDF that parses but reports zero pages is REJECTED', async () => {
  const doc = await PDFDocument.create({ updateMetadata: false });
  assert.equal(doc.getPageCount(), 0);
  // `save()` defaults to `addDefaultPage: true`, which would silently inject
  // a page into the output bytes -- disable it to produce genuinely
  // zero-page bytes for this test.
  const bytes = Buffer.from(await doc.save({ addDefaultPage: false }));
  await expectCode(() => assertValidRawPdfBytes(bytes), 'PDF_ZERO_PAGES');
});
