import assert from 'node:assert/strict';
import test from 'node:test';
import PaperEntryQuoteWaiterService, { PaperEntryQuoteWaitError } from './paper-entry-quote-waiter.service';
import { ExecutionQuoteSnapshot } from '../dto/paper-fill-model.dto';

const executionQuote = (overrides: Partial<ExecutionQuoteSnapshot> = {}): ExecutionQuoteSnapshot => ({ instrumentKey:'OPT', sourceTimestamp:'1970-01-01T00:00:00.000Z', receivedTimestamp:'1970-01-01T00:00:00.000Z', quoteAgeMs:2, ltpSourceTimestamp:'1970-01-01T00:00:00.000Z', ltpReceivedTimestamp:'1970-01-01T00:00:00.000Z', ltpAgeMs:2, bidSourceTimestamp:'1970-01-01T00:00:00.000Z', bidReceivedTimestamp:'1970-01-01T00:00:00.000Z', bidAgeMs:2, askSourceTimestamp:'1970-01-01T00:00:00.000Z', askReceivedTimestamp:'1970-01-01T00:00:00.000Z', askAgeMs:2, depthSourceTimestamp:'1970-01-01T00:00:00.000Z', depthReceivedTimestamp:'1970-01-01T00:00:00.000Z', depthAgeMs:2, ltp:100, bestBid:99, bestAsk:101, bidSize:10, askSize:10, depthLevels:[], spreadAbsolute:2, spreadPercent:2, connectionGenerationId:1, dataQuality:'FRESH_TOP_OF_BOOK', ...overrides });

test('waits for a fresh bid/ask snapshot after subscription', async()=>{ let now=0; let calls=0; const waiter=new PaperEntryQuoteWaiterService({timeoutMs:100,pollMs:1,now:()=>now,sleep:async()=>{now+=1;},abortReason:()=>undefined,getSnapshot:()=>++calls<2?undefined:{ltp:100,bid:99,ask:101,receivedAtMs:now}}); const quote=await waiter.waitForFreshQuote('OPT');assert.equal(quote.ask,101); });
test('quote timeout fails closed and stale snapshots are never accepted', async()=>{ let now=0; const waiter=new PaperEntryQuoteWaiterService({timeoutMs:2,pollMs:1,maxQuoteAgeMs:2,now:()=>now,sleep:async()=>{now+=1;},abortReason:()=>undefined,getSnapshot:()=>({ltp:100,bid:99,ask:101,receivedAtMs:-10})}); await assert.rejects(()=>waiter.waitForFreshQuote('OPT'),(error:unknown)=>error instanceof PaperEntryQuoteWaitError&&error.reason==='STALE_QUOTE'); });
test('reconnect, EOD, kill switch and halt abort quote waiting immediately', async()=>{ for(const reason of ['MARKET_DATA_NOT_READY','EOD_BLOCK','KILL_SWITCH_ACTIVE','RUNTIME_DEGRADED'] as const){const waiter=new PaperEntryQuoteWaiterService({abortReason:()=>reason,getSnapshot:()=>undefined});await assert.rejects(()=>waiter.waitForFreshQuote('OPT'),(error:unknown)=>error instanceof PaperEntryQuoteWaitError&&error.reason===reason);}});

test('canonical executable wait accepts fresh bid/ask and returns the exact immutable snapshot', async()=>{ const snapshot=Object.freeze(executionQuote({snapshotId:'fresh'})); const waiter=new PaperEntryQuoteWaiterService({getSnapshot:()=>undefined,getExecutionSnapshot:()=>snapshot,abortReason:()=>undefined,now:()=>2}); assert.equal(await waiter.waitForFreshExecutionQuote('OPT'),snapshot); });
test('fresh LTP cannot make stale executable depth pass the bounded entry wait', async()=>{ let now=0; const snapshot=executionQuote({snapshotId:'stale-depth',ltpAgeMs:1,bidAgeMs:2_001,askAgeMs:2_001,depthAgeMs:2_001,quoteAgeMs:2_001,dataQuality:'STALE'}); const waiter=new PaperEntryQuoteWaiterService({timeoutMs:0,pollMs:1,getSnapshot:()=>undefined,getExecutionSnapshot:()=>snapshot,abortReason:()=>undefined,now:()=>now,sleep:async()=>{now+=1;}}); await assert.rejects(()=>waiter.waitForFreshExecutionQuote('OPT'),(error:unknown)=>error instanceof PaperEntryQuoteWaitError&&error.reason==='STALE_QUOTE'); });
test('fresh executable depth with a stale LTP fails closed before V2 builds a risk intent', async()=>{ let now=0; const snapshot=executionQuote({snapshotId:'stale-ltp',ltpAgeMs:2_001,bidAgeMs:1,askAgeMs:1,depthAgeMs:1,quoteAgeMs:1,dataQuality:'FRESH_TOP_OF_BOOK'}); const waiter=new PaperEntryQuoteWaiterService({timeoutMs:0,pollMs:1,getSnapshot:()=>undefined,getExecutionSnapshot:()=>snapshot,abortReason:()=>undefined,now:()=>now,sleep:async()=>{now+=1;}}); await assert.rejects(()=>waiter.waitForFreshExecutionQuote('OPT'),(error:unknown)=>error instanceof PaperEntryQuoteWaitError&&error.reason==='STALE_QUOTE'); });
test('missing executable bid or ask fails closed even when LTP is fresh', async()=>{ let now=0; const snapshot=executionQuote({ltpAgeMs:1,quoteAgeMs:null,bestAsk:null,askAgeMs:null,dataQuality:'LTP_ONLY'}); const waiter=new PaperEntryQuoteWaiterService({timeoutMs:0,pollMs:1,getSnapshot:()=>undefined,getExecutionSnapshot:()=>snapshot,abortReason:()=>undefined,now:()=>now,sleep:async()=>{now+=1;}}); await assert.rejects(()=>waiter.waitForFreshExecutionQuote('OPT'),(error:unknown)=>error instanceof PaperEntryQuoteWaitError&&error.reason==='STALE_QUOTE'); });
