import HistoricalCandleRepository from '../../historical-candles/repositories/historical-candle.repository';
import { Candle } from '../../indicators/types';
import { ExpiredOptionCandleDto } from '../dto/upstox-expired-option-candle.dto';
import { HistoricalOptionResearchDataset, HistoricalOptionResearchPreloadStats, HistoricalOptionResearchSessionRequest } from '../dto/historical-option-research-preloader.dto';
import HistoricalOptionCandleRepository from '../repositories/historical-option-candle.repository';
import HistoricalOptionCandleCacheService from './historical-option-candle-cache.service';

const day = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Kolkata', year: 'numeric', month: '2-digit', day: '2-digit' });
export default class HistoricalOptionResearchPreloaderService {
  private readonly optionSessions = new Map<string, readonly ExpiredOptionCandleDto[]>(); private readonly inFlight = new Map<string, Promise<readonly ExpiredOptionCandleDto[]>>(); private readonly startedAt = Date.now(); private preloadDurationMs = 0; private readonly stats = { underlyingRowsLoaded: 0, optionSessionsLoadedFromMySql: 0, optionCandlesLoadedFromMySql: 0, upstoxMissingSessionDownloads: 0, newlyStoredOptionCandles: 0, inMemoryLookupHits: 0, dbFallbackHits: 0 };
  constructor(private readonly underlyingRepository: HistoricalCandleRepository, private readonly optionRepository: HistoricalOptionCandleRepository, private readonly cache: HistoricalOptionCandleCacheService, private readonly localOnly = process.env.RESEARCH_LOCAL_ONLY === 'true') {}
  async preloadUnderlying(instrumentKey: string, timeframe: string): Promise<HistoricalOptionResearchDataset> { const started = Date.now(); const rows = await this.underlyingRepository.findByInstrumentAndTimeframe(instrumentKey, timeframe); const byDate = new Map<string, Candle[]>(); const byTimestamp = new Map<number, Candle>(); rows.forEach((row) => { const candle: Candle = { timestamp: new Date(row.candleTime.getTime()), open: Number(row.open), high: Number(row.high), low: Number(row.low), close: Number(row.close), volume: Number(row.volume), openInterest: row.openInterest === null ? undefined : Number(row.openInterest) }; const key = date(candle.timestamp); byDate.set(key, [...(byDate.get(key) ?? []), candle]); byTimestamp.set(candle.timestamp.getTime(), candle); }); this.stats.underlyingRowsLoaded = rows.length; this.preloadDurationMs += Date.now() - started; return { underlyingByDate: byDate, underlyingByTimestamp: byTimestamp }; }
  async preloadOptionSessions(requests: readonly HistoricalOptionResearchSessionRequest[]): Promise<void> { const unique = Array.from(new Map(requests.map((request) => [key(request.instrumentKey, request.tradingDate), request])).values()); if (unique.length === 0) return; const started = Date.now(); const dates = unique.map((request) => request.tradingDate).sort(); const rows = await this.optionRepository.findByInstrumentKeysAndRange(Array.from(new Set(unique.map((request) => request.instrumentKey))), '1minute', new Date(`${dates[0]}T00:00:00+05:30`), new Date(`${dates[dates.length - 1]}T23:59:59.999+05:30`)); const grouped = new Map<string, ExpiredOptionCandleDto[]>(); rows.forEach((row) => { const value = { instrumentKey: row.instrumentKey, candleTime: new Date(row.candleTime.getTime()), open: Number(row.open), high: Number(row.high), low: Number(row.low), close: Number(row.close), volume: row.volume, openInterest: row.openInterest ?? undefined }; const groupKey = key(value.instrumentKey, date(value.candleTime)); grouped.set(groupKey, [...(grouped.get(groupKey) ?? []), value]); }); unique.forEach((request) => { const candles = grouped.get(key(request.instrumentKey, request.tradingDate)); if (candles && complete(candles, request.tradingDate)) { this.optionSessions.set(key(request.instrumentKey, request.tradingDate), candles); this.stats.optionSessionsLoadedFromMySql += 1; this.stats.optionCandlesLoadedFromMySql += candles.length; } }); this.preloadDurationMs += Date.now() - started; }
  async getOptionSession(request: HistoricalOptionResearchSessionRequest): Promise<readonly ExpiredOptionCandleDto[]> { const sessionKey = key(request.instrumentKey, request.tradingDate); const found = this.optionSessions.get(sessionKey); if (found) { this.stats.inMemoryLookupHits += 1; return found; } const pending = this.inFlight.get(sessionKey); if (pending) return pending; const load = this.loadOptionSession(request).finally(() => this.inFlight.delete(sessionKey)); this.inFlight.set(sessionKey, load); return load; }
  getStats(researchStartedAt?: number): HistoricalOptionResearchPreloadStats { const researchDurationMs = researchStartedAt === undefined ? 0 : Date.now() - researchStartedAt; return { ...this.stats, preloadDurationMs: this.preloadDurationMs, researchDurationMs, totalDurationMs: Date.now() - this.startedAt }; }
  private async loadOptionSession(request: HistoricalOptionResearchSessionRequest): Promise<readonly ExpiredOptionCandleDto[]> { const from = new Date(`${request.tradingDate}T00:00:00+05:30`); const to = new Date(`${request.tradingDate}T23:59:59.999+05:30`); const cached = await this.optionRepository.findRange(request.instrumentKey, '1minute', from, to); const mapped = cached.map((row) => ({ instrumentKey: row.instrumentKey, candleTime: new Date(row.candleTime.getTime()), open: Number(row.open), high: Number(row.high), low: Number(row.low), close: Number(row.close), volume: row.volume, openInterest: row.openInterest ?? undefined })); if (complete(mapped, request.tradingDate)) { this.stats.dbFallbackHits += 1; this.optionSessions.set(key(request.instrumentKey, request.tradingDate), mapped); return mapped; } if (this.localOnly) throw new Error(`RESEARCH_LOCAL_ONLY cache miss: instrumentKey=${request.instrumentKey} tradingDate=${request.tradingDate} expected=375 continuous 1minute candles locallyAvailable=${mapped.length}`); const before = this.cache.getStats(); const candles = await this.cache.getCandles(request.instrumentKey, request.tradingDate, request.metadata); const after = this.cache.getStats(); this.stats.upstoxMissingSessionDownloads += after.misses - before.misses; this.stats.newlyStoredOptionCandles += after.stored - before.stored; this.optionSessions.set(key(request.instrumentKey, request.tradingDate), candles.map(clone)); return this.optionSessions.get(key(request.instrumentKey, request.tradingDate))!; }
}
function key(instrumentKey: string, tradingDate: string): string { return `${instrumentKey}|${tradingDate}`; }
function date(timestamp: Date): string { const parts = Object.fromEntries(day.formatToParts(timestamp).map((part) => [part.type, part.value])); return `${parts.year}-${parts.month}-${parts.day}`; }
function complete(candles: readonly ExpiredOptionCandleDto[], tradingDate: string): boolean { if (candles.length !== 375) return false; const ordered = [...candles].sort((a, b) => a.candleTime.getTime() - b.candleTime.getTime()); const first = ordered[0].candleTime; const last = ordered[374].candleTime; return date(first) === tradingDate && date(last) === tradingDate && ordered.every((candle, index) => index === 0 || candle.candleTime.getTime() - ordered[index - 1].candleTime.getTime() === 60_000); }
function clone(candle: ExpiredOptionCandleDto): ExpiredOptionCandleDto { return { ...candle, candleTime: new Date(candle.candleTime.getTime()) }; }
