import { ExpiredOptionCandleDto } from '../dto/upstox-expired-option-candle.dto';
import { OptionExitPolicyEvaluationResult, TargetStopOptionExitPolicy } from '../dto/option-exit-policy.dto';

export default class OptionPremiumPathAnalysisService {
  private readonly byOffset = new Map<number, ExpiredOptionCandleDto>();
  constructor(private readonly signalTimestamp: Date, private readonly entryPremium: number, candles: readonly ExpiredOptionCandleDto[]) {
    const date = marketDate(signalTimestamp);
    candles.filter((candle) => marketDate(candle.candleTime) === date).forEach((candle) => { const offset = (candle.candleTime.getTime() - signalTimestamp.getTime()) / 60_000; if (Number.isInteger(offset)) this.byOffset.set(offset, candle); });
  }
  candleAt(offset: number): ExpiredOptionCandleDto | undefined { return this.byOffset.get(offset); }
  evaluate(policy: TargetStopOptionExitPolicy): OptionExitPolicyEvaluationResult { const targetPremium = this.entryPremium * (1 + policy.targetPercent / 100); const stopPremium = this.entryPremium * (1 - policy.stopLossPercent / 100); for (let offset = 1; offset <= policy.maximumHoldingMinutes; offset += 1) { const candle = this.byOffset.get(offset); if (!candle) continue; const target = candle.high >= targetPremium; const stop = candle.low <= stopPremium; if (target && stop) return this.ambiguous(candle, targetPremium, stopPremium); if (target) return this.result(candle, targetPremium, 'TARGET', targetPremium, stopPremium); if (stop) return this.result(candle, stopPremium, 'STOP_LOSS', targetPremium, stopPremium); } const time = this.byOffset.get(policy.maximumHoldingMinutes); return time ? this.result(time, time.close, 'TIME_EXIT', targetPremium, stopPremium) : this.unavailable(targetPremium, stopPremium); }
  private result(candle: ExpiredOptionCandleDto, premium: number, reason: 'TARGET' | 'STOP_LOSS' | 'TIME_EXIT', targetPremium: number, stopPremium: number): OptionExitPolicyEvaluationResult { const change = premium - this.entryPremium; return { signalTimestamp: this.signalTimestamp, entryPremium: this.entryPremium, exitTimestamp: new Date(candle.candleTime.getTime()), exitPremium: premium, exitReason: reason, holdingMinutes: (candle.candleTime.getTime() - this.signalTimestamp.getTime()) / 60_000, premiumChange: change, premiumChangePercent: change / this.entryPremium * 100, targetPremium, stopPremium, ambiguous: false, unavailable: false }; }
  private ambiguous(candle: ExpiredOptionCandleDto, targetPremium: number, stopPremium: number): OptionExitPolicyEvaluationResult { return { ...this.unavailable(targetPremium, stopPremium), exitTimestamp: new Date(candle.candleTime.getTime()), exitReason: 'AMBIGUOUS', holdingMinutes: (candle.candleTime.getTime() - this.signalTimestamp.getTime()) / 60_000, ambiguous: true, unavailable: false }; }
  private unavailable(targetPremium: number, stopPremium: number): OptionExitPolicyEvaluationResult { return { signalTimestamp: this.signalTimestamp, entryPremium: this.entryPremium, exitTimestamp: null, exitPremium: null, exitReason: 'UNAVAILABLE', holdingMinutes: null, premiumChange: null, premiumChangePercent: null, targetPremium, stopPremium, ambiguous: false, unavailable: true }; }
}
function marketDate(timestamp: Date): string { const p = Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(timestamp).map(x=>[x.type,x.value])); return `${p.year}-${p.month}-${p.day}`; }
