import { ResearchResultMatrix } from '../types/research-validation.types';
import { average, sampleStandardDeviation } from './research-metrics.service';

export interface DeflatedSharpeInput {
  observedSharpe: number;
  numberOfTrials: number;
  sampleLength: number;
  skewness?: number;
  kurtosis?: number;
}

export interface SimplifiedPboResult {
  method: 'SIMPLIFIED_CPCV';
  combinations: number;
  evaluatedCombinations: number;
  overfitCount: number;
  pbo: number;
  note: string;
}

/**
 * Bailey/Lopez de Prado-style deflated Sharpe approximation. Returns a
 * probability, not a p-value: it is the probability that the observed Sharpe
 * exceeds the estimated maximum Sharpe generated by the trial count.
 * Skewness and excess-kurtosis are assumed to be zero when omitted.
 */
export function deflatedSharpeRatio(input: DeflatedSharpeInput): number {
  const trials = Math.max(1, input.numberOfTrials);
  const n = Math.max(2, input.sampleLength);
  const skew = input.skewness ?? 0;
  const excessKurtosis = (input.kurtosis ?? 3) - 3;
  const gamma = 0.5772156649015329;
  const expectedMax = (1 - gamma) * normalQuantile(1 - 1 / trials) + gamma * normalQuantile(1 - 1 / (trials * Math.E));
  const variance = Math.max(1e-12, 1 - skew * input.observedSharpe + ((excessKurtosis) / 4) * input.observedSharpe ** 2);
  return normalCdf((input.observedSharpe - expectedMax) * Math.sqrt((n - 1) / variance));
}

/**
 * A deliberately conservative, simplified CPCV-style PBO estimate. It uses
 * chronological half splits (train first/validation second and the reverse),
 * selects the best train column, and counts selections below the validation
 * median. It is a diagnostic estimate, not a claim of exact statistical power.
 */
export function simplifiedPbo(matrix: ResearchResultMatrix): SimplifiedPboResult {
  if (!matrix.values.length || !matrix.configurations.length) return { method: 'SIMPLIFIED_CPCV', combinations: 0, evaluatedCombinations: 0, overfitCount: 0, pbo: 0, note: 'Empty result matrix.' };
  const midpoint = Math.floor(matrix.values.length / 2);
  const partitions = [
    { trainStart: 0, trainEnd: midpoint, validationStart: midpoint, validationEnd: matrix.values.length },
    { trainStart: midpoint, trainEnd: matrix.values.length, validationStart: 0, validationEnd: midpoint },
  ] as const;
  let overfitCount = 0;
  let evaluatedCombinations = 0;
  partitions.forEach(({ trainStart, trainEnd, validationStart, validationEnd }) => {
    const trainRows = matrix.values.slice(trainStart, trainEnd);
    const validationRows = matrix.values.slice(validationStart, validationEnd);
    if (!trainRows.length || !validationRows.length) return;
    const trainMeans = matrix.configurations.map((_, column) => average(trainRows.map((row) => row[column] ?? 0)));
    const selected = trainMeans.reduce((best, value, column) => value > trainMeans[best] ? column : best, 0);
    const validationMeans = matrix.configurations.map((_, column) => average(validationRows.map((row) => row[column] ?? 0)));
    const sorted = [...validationMeans].sort((a, b) => a - b);
    const median = sorted.length % 2 ? sorted[Math.floor(sorted.length / 2)] : (sorted[sorted.length / 2 - 1] + sorted[sorted.length / 2]) / 2;
    evaluatedCombinations += 1;
    if (validationMeans[selected] < median) overfitCount += 1;
  });
  return { method: 'SIMPLIFIED_CPCV', combinations: 2, evaluatedCombinations, overfitCount, pbo: overfitCount / Math.max(1, evaluatedCombinations), note: 'Chronological two-half estimator; use for ranking diagnostics only, not statistical precision.' };
}

export function resultMatrix(
  sessions: readonly string[],
  configurations: readonly string[],
  dailyReturns: ReadonlyMap<string, ReadonlyMap<string, number>>,
  costPercent: number
): ResearchResultMatrix {
  return { version: 'research-result-matrix-v1', sessions: [...sessions], configurations: [...configurations], costPercent, values: sessions.map((date) => configurations.map((config) => dailyReturns.get(date)?.get(config) ?? 0)) };
}

function normalCdf(value: number): number { return 0.5 * (1 + erf(value / Math.sqrt(2))); }
function erf(value: number): number {
  const sign = value < 0 ? -1 : 1;
  const x = Math.abs(value);
  const t = 1 / (1 + 0.3275911 * x);
  const polynomial = 1 - (((((1.061405429 * t - 1.453152027) * t + 1.421413741) * t - 0.284496736) * t + 0.254829592) * t * Math.exp(-x * x));
  return sign * polynomial;
}
function normalQuantile(value: number): number {
  if (value <= 0 || value >= 1) return value === 0 ? -Infinity : Infinity;
  const a = [-39.6968302866538, 220.946098424521, -275.928510446969, 138.357751867269, -30.6647980661472, 2.50662827745924];
  const b = [-54.4760987982241, 161.585836858041, -155.698979859887, 66.8013118877197, -13.2806815528857];
  const c = [-0.00778489400243029, -0.322396458041136, -2.40075827716184, -2.54973253934373, 4.37466414146497, 2.93816398269878];
  const d = [0.00778469570904146, 0.32246712907004, 2.445134137143, 3.75440866190742];
  const pLow = 0.02425;
  const pHigh = 1 - pLow;
  const rational = (q: number): number => {
    const numerator = (((((c[0] * q + c[1]) * q + c[2]) * q + c[3]) * q + c[4]) * q + c[5]);
    const denominator = ((((d[0] * q + d[1]) * q + d[2]) * q + d[3]) * q + 1);
    return numerator / denominator;
  };
  if (value < pLow) return rational(Math.sqrt(-2 * Math.log(value)));
  if (value > pHigh) return -rational(Math.sqrt(-2 * Math.log(1 - value)));
  const q = value - 0.5;
  const r = q * q;
  const numerator = (((((a[0] * r + a[1]) * r + a[2]) * r + a[3]) * r + a[4]) * r + a[5]) * q;
  const denominator = ((((b[0] * r + b[1]) * r + b[2]) * r + b[3]) * r + b[4]) * r + 1;
  return numerator / denominator;
}
